### ISSUE TITLE
Add support for controllers

### ISSUE THREAD

**Issue by ClxS** [Pathoschild/SMAPI#14]

**Comment by tstaples** [comment]
Hasn't this been done now? I think controller support was added a while ago.

**Comment by vgturtle127** [comment]
@ClxS @tstaples Call me crazy, but isn't "controller support" kind of silly since the controller controls the cursor? So, in effect, it already has support?

**Comment by tstaples** [comment]
@vgturtle127 I assume he means game pads, which are supported.

**Comment by ClxS** [comment]
Controller support is partially in, but no events exist for the analogue sticks yet.

**Comment by vgturtle127** [comment]
@ClxS @tstaples Gotcha.

**Comment by AdvizeGH** [comment]
You guys sure it doesn't? I mean I think you can simply by using Microsoft.Xna.Framework.Input

![Image](http://i.imgur.com/hAT9tWL.png)

**Comment by Pathoschild** [comment]
SMAPI does support controller input, so I'll close this ticket. Feel free to submit specific suggestions as separate tickets.
