### ISSUE TITLE
Mod update check service

### ISSUE THREAD

**Issue by Pathoschild** [Pathoschild/SMAPI#181]
Provide some mechanism for SMAPI to automatically to check for new mod versions and notify the users. 

Very few mods do this (which means many player issues are caused by using old mod versions), and there's a patchwork of custom solutions for those mods that do.

**Comment by Pathoschild** [comment]
Here's one possible approach:

1. The mod could optionally specify two URLs in their `manifest.json`: one would return a JSON payload with the version number, and the other would link the user to the mod page.
   ```json
   {
      "Name": "Lookup Anything",
      "Version": {
         "MajorVersion": 1,
         "MinorVersion": 7,
         "PatchVersion": 0,
         "Build": ""
      },
      "LatestVersionApi": "https://raw.githubusercontent.com/Pathoschild/LookupAnything/master/LookupAnything/manifest.json",
      "LatestVersionLink": "http://www.nexusmods.com/stardewvalley/mods/541/"
   }
   ```
   The API URL would return a JSON object containing a version number. The version number could be one of several recognised formats (including the `manifest.json` format, so mods can just link to the file in their release branch).
2. When the game loads, SMAPI would fetch the mod's latest-version API URL and parse it into a semantic version.
3. If the latest version was newer, SMAPI would show an update-available message with a download link.

Technically a mod could link to the [GitHub latest-release API](https://developer.github.com/v3/repos/releases/#get-the-latest-release) instead, but we should discourage that since [GitHub only allows 60 API calls per hour per IP](https://developer.github.com/v3/#rate-limiting).

**Comment by catamari** [comment]
Would the update message only appear in the console? I know LookupAnything also displays an in-game tool-tip but I would imagine that would get cluttered quite quickly with lots of mods. 

I suppose something like a separate UI that could be brought up with a key press or something could display a list of loaded mods and which are out-dated. Then there could still be a tool-tip stating that some of the current mods are out of date.

Another idea could be to integrate this into Farmhand's mod menu which is accessible from the main menu and displays info about all the loaded mods. If this is easily back-portable then that might be a decent alternative.

**Comment by Pathoschild** [comment]
This will probably be shown in the console log, and maybe show a message like "4 mods have updates ready; see the console for details" in-game.

Backporting Farmhand's mod menu is a possibility, though we'll need to change several things to make that possible (including preventing mods from doing anything until the save is loaded).

**Comment by Pathoschild** [comment]
The main limitation is the GitHub API rate limit of 60 requests per hour per IP. One solution is a simple proxy server that  fetches the release with an authenticated API client (which has a rate limit of 5000/hour), caches them, and returns only the data needed. This could also support batching, e.g.:

```json
GET /api/versions?mods=LookupAnything,ChestsAnywhere

{
   "LookupAnything": 1.9,
   "ChestsAnywhere": 1.8
}

**Comment by miketweaver** [comment]
Or use a GitHub CDN: 
https://rawgit.com/ 
https://gitcdn.xyz/
https://raw.githack.com/

**Comment by Entoarox** [comment]
I wish to see the following functionality in any build-in SMAPI version checker:

- The ability for the external JSON to specifiy where to get the update (Author changes their primary location, or a place like SDVMods could mess with the manifest)
- The ability to list mod versions for multiple SDV versions, so that people can keep using older SDV versions if they want.
- The ability for the external JSON to prevent versions older then a certain minimum from being used (Separately for each SDV version)
- The ability to have a certain (possible not the latest) version as the "recommended" version, with it being preferred over the latest if installed (A less explicit "Update available" message?)

**Comment by Pathoschild** [comment]
This ticket covers too much ground, so I'm closing it in favour of a more phased approach:

1. With #336, mods can set their Nexus mod ID in `manifest.json` and SMAPI will check for updates through the Nexus API.
2. We can add support for for ModDrop and Chucklefish IDs once those APIs are available / figured out.
3. We can consider supporting the more complicated use cases (like Entoarox's comment above) in a future version if there's demand for it.
