### ISSUE TITLE
Show warning instead of error for non-mod directory

### ISSUE THREAD

**Issue by Entoarox** [Pathoschild/SMAPI#186]
This assumption leads to errors in the console whenever there is a directory that isnt a mod, some people like myself use a subdirectory to store mods they want to "disable" rather then going the mod manager route.
It would also be much more helpfull to just print a "Found non-mod directory X" message as info, this makes it clear that it didnt detect a mod, but doesnt imply there to be a major problem as a error would.

**Comment by Pathoschild** [comment]
Done in the upcoming 1.4 release:
![screenshot of warning](https://cloud.githubusercontent.com/assets/230581/20946671/a993dd58-bbd9-11e6-8e55-9f6da20cf626.png)
