### ISSUE TITLE
Question about a mod I want to make..

### ISSUE THREAD

**Issue by ShadowKitty42** [Pathoschild/SMAPI#190]
Ok, here's the situation, and I need to know how difficult it might be. I want to add a new Blueprint to the game, that is an upgrade from an existing building. I've looked through the object browser in VS2015 and I can't find a way to modify the game's list of Blueprints, so that Robin's carpentry menu will read it. Have I missed something, or is that not possible right now? If not, could an update to SMAPI create a way to do this? (I've already made the necessary xnb file changes to create the blueprint, but her menu doesn't show it.)

If not, I would have to create a much more crude way of doing it, that, as of right now, I'm not even sure would work like I want lol

**Comment by Pathoschild** [comment]
Hi @ShadowKitty42. You'll have much better luck asking the [modding community on Discord](https://discord.gg/kH55QXP). The issues on GitHub are for problems with the SMAPI code itself, so most modders don't watch these. :)

**Comment by ShadowKitty42** [comment]
Oh I was just trying to ask you directly, since you're the main contributor on SMAPI. I just couldn't find a better way to message you.

**Comment by Pathoschild** [comment]
No problem. You can ping me directly on Discord, though I don't know the answer to your question. Other modders there probably do. :)
