### ISSUE TITLE
wierd crash when opening mailbox

### ISSUE THREAD

**Issue by mightydanp** [Pathoschild/SMAPI#205]
![crash](https://cloud.githubusercontent.com/assets/4637469/21490443/4279e928-cbba-11e6-9133-dc05f37c7c78.PNG)
only happens when i open mail box

**Comment by mightydanp** [comment]
![crash](https://cloud.githubusercontent.com/assets/4637469/21490465/7927ed44-cbba-11e6-8fa2-e509d01e5dcb.PNG)

**Comment by Pathoschild** [comment]
Hi @mightydanp. If you have the Steam version, try [verifying the game integrity](https://support.steampowered.com/kb_article.php?ref=2037-QEUH-3335) to reset your game files to default. This won't affect SMAPI mods, but any XNB mods will be removed.

**Comment by mightydanp** [comment]
alright i have and when i add the more crops mod is when i cannot access my mail box

**Comment by Pathoschild** [comment]
I suggest reporting the problem to the More Crops mod author to look into it. :)
