### ISSUE TITLE
SMAPI not ''reading'' edited config.json files

### ISSUE THREAD

**Issue by PublicMenace** [Pathoschild/SMAPI#210]
When I edit the config.json of any mod SMAPI ignores that and just reads the standard config settings.
I'm on Mac OS and I think this could be a PEBKAC.

**Comment by PublicMenace** [comment]
When I close and reopen the given config file the settings that I made are saved so i think it must be SMAPI not recognising the changes.
Thanks in advance,
Johan

**Comment by Tondorian** [comment]
most mods only read the config once in Entry(IModHelper helper) and write it if the mod gets unloaded. If SMAPI is running your changes would be lost

**Comment by PublicMenace** [comment]
Does that mean I can't just edit the config.json to apply changes?

**Comment by Tondorian** [comment]
if your game is running i don't think so

**Comment by PublicMenace** [comment]
My game is always closed when i edit the config files so it should work...

**Comment by Tondorian** [comment]
maybe the mod you are using is buggy i just checked config on my own mod and it works as expected

**Comment by PublicMenace** [comment]
I tried on many mods and it didn't work. I'll try again later. Thanks anyways :)

**Comment by Pathoschild** [comment]
Hi @PublicMenace. If this is still happening, [come ask on Discord](https://discord.gg/kH55QXP) and we'll help figure it out. I'll close this since the GitHub issues are really for planned tasks. :)
