### ISSUE TITLE
SMAPI rewrite fails when mod is updated, but game is run from a custom non-installed folder

### ISSUE THREAD

**Issue by ekffie** [Pathoschild/SMAPI#221]
When playing from a different folder than the steam default folder using steam, 
smapi can find dlls only when they are in the default stardew folder on first run

If you run once per starting StardewModdingApi.exe in the correct folder the config will be fixed and you can start through steam without problems.
For details see tests in Zip with logs and Readme therein.

[SteamPathTests.zip](https://github.com/Pathoschild/SMAPI/files/718104/SteamPathTests.zip)

**Comment by Pathoschild** [comment]
Tentatively fixed in `develop` via #229 for the upcoming 1.8 release. Pending confirmation.

**Comment by Pathoschild** [comment]
@ekffie confirmed this is fixed. Thanks!
