### ISSUE TITLE
"TerrainFeature Broken" / "TerrainFeature Removed" event

### ISSUE THREAD

**Issue by kd8lvt** [Pathoschild/SMAPI#224]
Emitted whenever a TerrainFeature (like debris, trees, bushes, etc) are broken. Args would include the feature broken, as well as with what tool (you can break the little bush debris with all the tools except fishing rod) This would allow for mods to add new skills, like logging. Could also be cancellable to prevent vanilla XP gain (?). Just a quick little idea that popped into my head :) This is as far as I have thought into it.

**Comment by LeonBlade** [comment]
@kd8lvt You can use the `CollectionChanged` events on the `terrainFeatures` to get this sort of information.

**Comment by Pathoschild** [comment]
Closed per @LeonBlade's comment.
