### ISSUE TITLE
[Linux] SMAPI doesn't work with terminator

### ISSUE THREAD

**Issue by RfzVd** [Pathoschild/SMAPI#227]
When x-terminal-emulator is set to terminator, the launching fails with message (on the opened terminator window) "unable to find a shell". My terminator is version 0.97 (from Debian repos), newer versions are not necessarily affected. I believe other users have encountered similar problems with terminator and it may simply be a bug in terminator.

I resolved this problem by modifying the StardewValley file to use xterm instead.

**Comment by Pathoschild** [comment]
I don't think there's anything SMAPI can do about that, since it's a bug with a particular distro or shell. If you can think of a simple solution that works cross-distro, let me know. :)

**Comment by 2E0PGS** [comment]
I have patched this: https://github.com/Pathoschild/SMAPI/pull/419
