### ISSUE TITLE
SMAPI causes the game to crash with the new update!

### ISSUE THREAD

**Issue by MayDonutLover** [Pathoschild/SMAPI#232]
This is the error message I got (it was too long to try to type out)
Edit: I should state that the new update to Stardew Valley causes SMAPI to crash, not the new update to SMAPI.
![smapi issue](https://cloud.githubusercontent.com/assets/21248264/22726085/ff4c05e2-ed96-11e6-8c07-64a4f1fa824a.png)

**Comment by Pathoschild** [comment]
SMAPI isn't officially compatible with Stardew Valley 1.2 beta yet. See the [SMAPI discussion thread](http://community.playstarbound.com/threads/smapi-stardew-modding-api.108375/page-61#post-3110413) for a preview version of SMAPI that works with the beta.

**Comment by MayDonutLover** [comment]
Oh, cool!  Thank you!  I Googled for relevant topics and couldn't find it.  Thank you very much.
