### ISSUE TITLE
Remove SDV `Console` calls from console output

### ISSUE THREAD

**Issue by Entoarox** [Pathoschild/SMAPI#233]
This requires the following steps:

- Save the stream in `Console.Out` in a place where the IMonitor instances can access it
- Use `Console.SetOut(null)` to disable console output

Then, in the Log method for the console (And similar) we do the following:
- Use `Console.SetOut` with the stream we saved
- Log to the console whatever we want
- Use `Console.SetOut(null)` again to disable console output

**Comment by Pathoschild** [comment]
Done in `release/1.9`.

I think suppressing console output entirely would be confusing to developers, who might write to the console and wonder why nothing is happening. Instead direct console output is now redirected to trace messages.
