### ISSUE TITLE
Steam overlay not working

### ISSUE THREAD

**Issue by Smolcoffeekid** [Pathoschild/SMAPI#239]
I have windows 7 64 bit and version 1.1 of Stardew Valley and when I install version 1.8 of the API a windows error came up and said that there was a compatibility error and I could use recommended settings or I could just say it installed correctly. I tried both and it still didn't work. I also tried downloading the API files again and reinstalling it but that didn't work either. I've tried launching it with no mods in the mods folder. The steam overlay didn't work for me when I used version 1.5 of the API either and when I launch the base game the overlay works fine.
[MODDED_ProgramLog.Log_LATEST.txt](https://github.com/Pathoschild/SMAPI/files/786220/MODDED_ProgramLog.Log_LATEST.txt)

**Comment by Pathoschild** [comment]
@Smolcoffeekid I just rewrote the [SMAPI install instructions](http://canimod.com/for-players/install-smapi#on-windows); they now suggest a different way of configuring Steam that works for more users. Do the new instructions work for you?

**Comment by Smolcoffeekid** [comment]
@Pathoschild yes it worked thank you!
