### ISSUE TITLE
my game wont start please help!!

### ISSUE THREAD

**Issue by trinityseven** [Pathoschild/SMAPI#245]
Unhandled Exception: System.MissingFieldException: Field not found: 'StardewValley.Game1.version'.
   at StardewModdingAPI.Program.Main(String[] args)

please help me solve this problem !!!

**Comment by Pathoschild** [comment]
Hi @trinityseven. Make sure you have the [correct version of SMAPI](https://github.com/Pathoschild/SMAPI/releases):
* If you have Stardew Valley 1.11 (not beta), use SMAPI 1.8.
* If you have Stardew Valley 1.2 beta, use SMAPI 1.9 beta.

If the issue still happens, please [post in the support thread](http://community.playstarbound.com/threads/smapi-stardew-modding-api.108375) or [come ask on Discord](https://discord.gg/kH55QXP). :)
