### ISSUE TITLE
Starting StardewModdingAPI

### ISSUE THREAD

**Issue by YouTubeLikerin** [Pathoschild/SMAPI#250]
After I try to start it Windows says it is not working anymore and there is a text saying this : Unbehandelte Ausnahme: System.MissingFieldException: Feld nicht gefunden: "StardewValley.Game1.version".
   bei StardewModdingAPI.Program.Main(String[] args)  
So what can I do to get this working?

**Comment by Pathoschild** [comment]
Hi @YouTubeLikerin. If you have Stardew Valley 1.2 beta, you need to use SMAPI 1.9 beta. (There's a link to it on the [SMAPI download page](https://github.com/Pathoschild/SMAPI/releases).)
