### ISSUE TITLE
Back up save files

### ISSUE THREAD

**Issue by andrewzah** [Pathoschild/SMAPI#253]
It's pretty rare to have a corrupted save file due to a mod, but it still would be nice.

**Comment by Pathoschild** [comment]
Tentatively planned for SMAPI 2.6. Spoke with @janavarro95 who created the [Save Backup mod](https://www.nexusmods.com/stardewvalley/mods/435), and they have no objection to SMAPI providing its own version. ❤️

The current plan is to implement this as a SMAPI mod bundled alongside Console Commands.

**Comment by Pathoschild** [comment]
Done in `develop` for the upcoming SMAPI 2.6-beta.13.
