### ISSUE TITLE
Constants.SaveFolderName isn't set in afterdaystarted on the very first day of a brand new game

### ISSUE THREAD

**Issue by primevaltitmouse** [Pathoschild/SMAPI#261]
Steps to reproduce:

Add a handler to TimeEvents.AfterDayStarted

Have the handler log Constants.SaveFolderName

Start a new game and check the box for "Skip Intro"

Observe that Constants.SaveFolderName isn't set right!

**Comment by Pathoschild** [comment]
Fixed in `develop` for the next SMAPI release.
