### ISSUE TITLE
Cant get SMAPI 1.9 to start 

### ISSUE THREAD

**Issue by angelsco** [Pathoschild/SMAPI#262]
Hello, I decided I would try to download mods for the first time. I have version 1.11 of Stardew Valley so download SMAPI 1.9. When I try to start it, it shows the error message I have attached. I did some research and tried two suggestions I saw, one was to delete the file in question, restart the computer then re-add it to the folder. That did not work. I also tried downloading Process Explorer and looking to see what programs are using that file and it only shows SMAPI (picture also included). I tried closing that down and reopening it and still nothing. Please help!!

**Comment by angelsco** [comment]
![error message](https://cloud.githubusercontent.com/assets/27900064/25307662/b5f44d6c-2772-11e7-8bc6-982043b256d2.png)

**Comment by angelsco** [comment]
[](url)
![process explorer](https://cloud.githubusercontent.com/assets/27900064/25307664/c385587c-2772-11e7-83fb-fb3d596a1546.png)

**Comment by Pathoschild** [comment]
Come ask for help in [the #modding channel on the Stardew Valley Discord](https://discord.gg/kH55QXP), and we'll help you figure it out. You can also post in the [support forum thread](http://community.playstarbound.com/threads/smapi-stardew-modding-api.108375), but it'll take longer that way. :)
