### ISSUE TITLE
Add support for automatically creating steam launch options to installer

### ISSUE THREAD

**Issue by Entoarox** [Pathoschild/SMAPI#267]
This requires the https://github.com/shravan2x/Gameloop.Vdf library that works similar to newtonsoft in that it lets you serialize/deserialize the vdf structure

With this, you need to deserialize the file `,,Steam\userdata\<USERID>\config\localconfig.vdf`

Then, in that file go to the `UserLocalConfigStore ~ Software ~ Valve ~ Steam ~ apps ~ 413150` group node, and add a new value node called `LaunchOptions` the value of this node is what steam uses as the launch options.

It should be noted that steam might need to be turned off while the installer edits this file, as steam constantly updates it while its running.

**Comment by Pathoschild** [comment]
I have no current plans to implement this, but I'd be interested in a pull request if it worked well.
