### ISSUE TITLE
crash upon having a sleep event.

### ISSUE THREAD

**Issue by fxmodder** [Pathoschild/SMAPI#270]
hi, i want to report an issues that prevent me from playing the smapi , when i sleep and there is a fairy coming to grow a crop , after the cutscene the game just stop working and do not save and crashes, my mod folder is empty because i thought it was another mod causing this but it seem it wasn't the case because it tried another of my save file and slept without having a special event going on and it saved the game just fine without crashing.

**Comment by fxmodder** [comment]
if you need a picture of the error
![untitled](https://cloud.githubusercontent.com/assets/10413094/25356660/02de5b58-2909-11e7-8d83-fc1bf29a4dcf.png)

**Comment by Pathoschild** [comment]
This seems to be a bug in Stardew Valley. You can report the error in the [Stardew Valley support forums](http://community.playstarbound.com/forums/stardew-support/). :)
