### ISSUE TITLE
Unable to start Multiplayer Game from previous saves

### ISSUE THREAD

**Issue by richardli4824** [Pathoschild/SMAPI#271]
Host screen is just black and freezes when starting after the client joins.

Error log below:

https://drive.google.com/file/d/0B_Bml70ftVz6bmUwT0NwR3k3b0U/view?usp=sharing

Am I missing something or did I not install SMAPI correctly? Same versions and mods are being used.

**Comment by Pathoschild** [comment]
That looks like a bug in the recent Stardew Valley 1.2.26 update; see [this reddit thread](https://www.reddit.com/r/StardewValley/comments/67hntx/stardew_valley_12_problems_fixes/) for details. If the fixes there don't help, try asking the author for help in [#multiplayer-mod in the Stardew Valley Discord](https://discord.gg/HFFAJ3H) or in [the mod's support thread](http://community.playstarbound.com/threads/makeshift-multiplayer.119076).
