### ISSUE TITLE
Marraige breaks game save

### ISSUE THREAD

**Issue by ShortCircuit908** [Pathoschild/SMAPI#272]
Marraige before upgrading the house breaks the save due to a map file not existing
[SMAPI-latest.txt](https://github.com/Pathoschild/SMAPI/files/960578/SMAPI-latest.txt)

**Comment by Pathoschild** [comment]
That isn't related to SMAPI. It looks like you're missing some of the game files; you can [verify the game integrity](https://support.steampowered.com/kb_article.php?ref=2037-QEUH-3335) to reset your XNB files to default. (That will remove any XNB mods, so you'll need to reinstall those.) If that doesn't fix it, you can try posting in the [Stardew Valley support forums](http://community.playstarbound.com/forums/stardew-support/).
