### ISSUE TITLE
SMAPI will only install to one game folder

### ISSUE THREAD

**Issue by Sakorona** [Pathoschild/SMAPI#274]
If you have both a GoG and Steam install, it doesn't ask you which to install, which means it won't always install to the one you may be actively using.

**Comment by Pathoschild** [comment]
The best way to handle that might be to show a message like this:

```
SMAPI found multiple copies of the game. Where do you want to install SMAPI?

[1] Install to C:\Program Files (x86)\GalaxyClient\Games\Stardew Valley.
[2] Install to C:\Program Files (x86)\Steam\steamapps\common\Stardew Valley.
[A] Install to all copies.

What do you want to do? Type 1, 2, or A, then press enter.
```

What do you think?

**Comment by Sakorona** [comment]
That would make the most sense.

Since usually I don't mod my Steam install, for example. I use it to test on a "vanilla" one

**Comment by Pathoschild** [comment]
Done in `develop` for the next SMAPI release.
