### ISSUE TITLE
Consider default content source for content.Load<T>

### ISSUE THREAD

**Issue by Pathoschild** [Pathoschild/SMAPI#276]
The content API added by #257 lets you load content from the mod folder or game content:
```cs
helper.Content.Load<T>("asset key", ContentSource.ModFolder);
helper.Content.Load<T>("asset key", ContentSource.GameContent);
```

Per request, should it assume the mod folder if you don't specify a content source?
```cs
helper.Content.Load<T>("asset key");
helper.Content.Load<T>("asset key", ContentSource.GameContent);
```

**Comment by Entoarox** [comment]
:+1: from me, as the content API matures and eventually Farmhand becomes available, more and more content will be loaded from mods, having to explicitly define "I want my content from mods" is counter-intuitive in my opinion.

**Comment by Pathoschild** [comment]
The consensus on Discord is in favour. Done in `develop` for the next SMAPI release. :)
