### ISSUE TITLE
A request from a Chinese player of SV

### ISSUE THREAD

**Issue by song195617** [Pathoschild/SMAPI#289]
Hello Pathoschild, I'm a Chinese player of Stardew Valley. Firstly I express my sincerely gratitude to you and your useful mod "LookUpAnything". I send you this message for the purpose of translating this mod into Chinese.

If you agree with me to do it, I will express my gratitude again. If not, sorry for disturbing you. AND...forgive my bad English and my begining programing.

I want to translate the text of the mod's interface from English into Chinese. I open "LookupAnything.dll" by a software named "dotPeek" and see several groups of data such as "components", "framework.constants","framework.Data". Which one should I modify? 

If you want more supplementary explanation, just ask me. Thank you very much.

**Comment by Pathoschild** [comment]
Hi @song195617. All my mods are now available in Chinese (and other languages). :)
