### ISSUE TITLE
Let mods load .tbin files through the content API

### ISSUE THREAD

**Issue by Platonymous** [Pathoschild/SMAPI#291]
This would allow mods to load maps without having to pack them into xnb files.

https://github.com/Platonymous/SMAPI/commit/4dbb64cfa8af7f2f3ccf0e669521f0ae2dfdb381

**Comment by Pathoschild** [comment]
Thanks! As we discussed, I'll keep this on hold for a bit until the game devs fix [a related bug](http://community.playstarbound.com/threads/multi-language-open-beta-available.130058/page-27#post-3160113).

**Comment by Pathoschild** [comment]
Tentatively merged into `develop` via pull request #298. Thanks!
