### ISSUE TITLE
Add API for per-save JSON data

### ISSUE THREAD

**Issue by Pathoschild** [Pathoschild/SMAPI#293]
Extend the JSON API (#292) to support per-save JSON files, which will be stored automatically in the save folder to allow GOG/Steam cloud sync.

**Comment by Pathoschild** [comment]
Possible usage:
```cs
// save to <app data>/Saves/mod data/<mod id>/data.json
helper.Data.Write("data.json", data);

// save to <app data>/Saves/mod data/<mod id>/Name_0123456789_data.json
helper.Data.Write("data.json", data, perSave: true);
```

Possibly combine with `config.json`:

```cs
// read config.json
TModel config = helper.Data.ReadConfig<TModel>();

// write config.json
helper.Data.WriteConfig(config);
````

**Comment by spacechase0** [comment]
I thought this was going to go into individual save folder so that it would cloud sync?

**Comment by Pathoschild** [comment]
If I recall correctly, we tested it and cloud sync saves everything under `<app data>/Saves`?

**Comment by Pathoschild** [comment]
Closing in favor of #468.
