### ISSUE TITLE
SMAPI 1.13.1 crashing: Unhandled Exception Language Code?

### ISSUE THREAD

**Issue by lizanne2014** [Pathoschild/SMAPI#295]
I recently decided to finally update to the newest version of SMAPI (1.13.1)my game was working perfectly before I just wanted to add new mods that required the updated version. I downloaded the new SMAPI as directed but now when I go to laugh the StardewModdingAPI I get this message and cannot launch my game :( any help would be amazing. Thank you!
![smapi](https://cloud.githubusercontent.com/assets/28827294/26276935/06a467d6-3d50-11e7-9c08-1ed8dd64fab9.JPG)

**Comment by Pathoschild** [comment]
Hi @lizanne2014. The latest versions of SMAPI need Stardew Valley 1.2.26+. You can fix the error by updating your game to the latest version, or installing SMAPI 1.8 if you prefer to keep an older version. If you need help, feel free to [post in the support thread](http://community.playstarbound.com/threads/108375/) or [come chat on Discord](https://discord.gg/kH55QXP). :)
