### ISSUE TITLE
Show when Game1.debugOutput changes in the console

### ISSUE THREAD

**Issue by spacechase0** [Pathoschild/SMAPI#297]
Some of the game's debug commands, such as `where <NPC>`, give output by setting Game1.debugOutput. It could be helpful to print this to the console.

There would probably need to be some messages filtered out though, as the game uses it in other places as well. The main "spammy" cases I can see are:
* Farmer.UpdateIfOtherPlayer (which admittedly is never used except with the MP mod)
* DayTimeMoneyBox.updatePosition (which is called in several places, including at the beginning of the draw method)
* Slingshot.tickUpdate
* IClickableMenu.moveCursorInDirection
* Possibly GameLocation.addClouds, GameLocation.spawnWeedsAndStones, Bush.performPlayerEntryAction
There are some other cases as well, such as when dismounting a horse, some unused stuff, and some things that you'd probably want to know about anyways (such as exceptions during saving/loading startup preferences, or certain stages of game saving/loading).

**Comment by Pathoschild** [comment]
Fixed in `develop` for the upcoming release. SMAPI will now print any `debug` command output to the console:
> ![](https://cloud.githubusercontent.com/assets/230581/26526164/e1ec7204-433e-11e7-95a9-35cbe4a4406b.png)


This is specific to the `debug` console command; SMAPI won't log `Game1.debugOutput` any other time.
