### ISSUE TITLE
1.13.1 Crashing on Startup

### ISSUE THREAD

**Issue by AshxAffliction** [Pathoschild/SMAPI#299]
So far I haven't tested this on my other computer to eliminate my hardware as a potential cause of this issue. What I have done is tried launching without any mods in the Mods folder to check if it was a mod causing it, which it isn't, and I tried using the normal 1.13 version of SMAPI, which works perfectly for me.

**Comment by Pathoschild** [comment]
Hi @AshxAffliction. Can you post a message in the [SMAPI support thread](http://community.playstarbound.com/threads/smapi-stardew-modding-api.108375/), and attach [your latest SMAPI log](http://canimod.com/for-players/faqs#smapi-log) after it crashes?
