### ISSUE TITLE
Reinstall bug with SMAPI!

### ISSUE THREAD

**Issue by ThreadedSkurt** [Pathoschild/SMAPI#305]
i uninstaled SMAPI and installed it again but it got me an error so i restarted my computer but it still sending that massage i need help to get it up and running i guess i will play more with no mods #defuq happen?

**Comment by Pathoschild** [comment]
Hi @NuCreeper. Can you post a message in the [SMAPI support thread](http://community.playstarbound.com/threads/smapi-stardew-modding-api.108375)? Make sure to include a screenshot of the error and [your latest SMAPI log](http://canimod.com/for-players/faqs#smapi-log) after it happens.
