### ISSUE TITLE
XML missing/error 

### ISSUE THREAD

**Issue by SrNukee** [Pathoschild/SMAPI#312]
![image](https://user-images.githubusercontent.com/29734440/27594787-278249e2-5b31-11e7-97f9-843f3dedf4a5.png) 
![image](https://user-images.githubusercontent.com/29734440/27594804-330180a8-5b31-11e7-8faf-7920f268c3af.png)

**Comment by Pathoschild** [comment]
@SrNukee It looks like your `startup_preferences` file is broken (not an issue with SMAPI). You can fix it by [finding your saves folder](http://stardewvalleywiki.com/Modding:Player_FAQs#Save_files), navigating up one folder, and deleting the `startup_preferences` file. It will be regenerated when you launch the game.

If you need any other help, feel free to post a message in [the SMAPI support thread](http://community.playstarbound.com/threads/108375). :)
