### ISSUE TITLE
When parsing JSON fails, add friendly error if curly quotes are detected

### ISSUE THREAD

**Issue by webxro** [Pathoschild/SMAPI#314]
Add a warning for people that replaced straight quotation marks with curly quotation marks by accident. 

Maybe a line listing all the JSON files that contain curly quotation marks ? Or something because there might be some that have it by design.

**Comment by Pathoschild** [comment]
Done in `develop` for the upcoming SMAPI release.

Here's the previous error for reference:
> ![](https://user-images.githubusercontent.com/230581/27774218-a94db758-5f5b-11e7-9580-370a3964c6ab.png)

Here's the new error when parsing JSON fails (with the curly quote part conditional on finding curly quotes):
> ![](https://user-images.githubusercontent.com/230581/27774259-67503596-5f5c-11e7-9fc1-02b9c147b61b.png)
