### ISSUE TITLE
Rename installer package to reduce confusion

### ISSUE THREAD

**Issue by Pathoschild** [Pathoschild/SMAPI#324]
Players sometimes try to run SMAPI from `<installer package>/internal/Windows`. Rename the main folder to avoid confusion.

To do:
* [x] Make sure it won't break mod managers:

  client  | status
  ------- | ------
  ModDrop | ✓ not affected.
  SDVMM   | ✓ affected but easy fix.
  SVPM    | ✓ no response on Discord 2017-07-10, sent second message through Nexus 2017-08-02.

* [x] Rename the main folder and zip from `SMAPI 2.0` to `SMAPI 2.0 installer` to reduce confusion.

**Comment by Entoarox** [comment]
I would recommend having the final files bundled into the installer as resources, windows & the .net framework both have API's for reading those resources out of other files, so mod managers should be able to handle that.

This would also allow you to just distribute a single file in the zip, confusion: perma-fixed

**Comment by Pathoschild** [comment]
Renamed in `develop` for the upcoming 2.0 release.

Bundling the files as assembly resources is out of scope for now, but it's worth considering for a future release.
