### ISSUE TITLE
Crash on launch

### ISSUE THREAD

**Issue by paradox0s** [Pathoschild/SMAPI#326]
I downloaded SMAPI a few days ago, installed a few mods and everything was working just fine. Right up until this morning. Now whenever I start to load it up I get the following error:

![heck](https://user-images.githubusercontent.com/13956627/28064825-aab58606-65fb-11e7-83da-f9afea65b123.jpg)

No idea how to fix this. :( The game seems to work just fine if I load it up without SMAPI, it's just SMAPI itself. I'm pretty technically illiterate so there's potentially something super obvious I'm missing here.

**Comment by Pathoschild** [comment]
Hello @paradox0s. See [this FAQs entry](http://stardewvalleywiki.com/Modding:Player_FAQs#SEHException:_External_component_has_thrown_an_exception) for some possible fixes. If you still need help, post a message in [the SMAPI support thread](http://community.playstarbound.com/threads/108375). :)
