### ISSUE TITLE
Fix SMAPI taskbar icon on Linux/Mac

### ISSUE THREAD

**Issue by Pathoschild** [Pathoschild/SMAPI#329]
Apparently Mono only accepts `icon.bmp`, not the current `icon.ico`.

Solution reported by Nanogamer7 on Discord.

**Comment by Pathoschild** [comment]
I poked at this a bit and couldn't get it to work on Linux, regardless of including an `icon.bmp` or `Icon.bmp`, setting it as the application icon, or including it in the build output. The launcher icon works (it worked fine with `icon.ico` too), but the taskbar icon is unchanged:

> ![](https://user-images.githubusercontent.com/230581/28858173-bbc0f020-771c-11e7-8f30-7305208850e2.png)

**Comment by Pathoschild** [comment]
See [proposed fix in reddit discussion](https://www.reddit.com/r/StardewValley/comments/7q3rkm/is_this_the_normal_icon_for_the_smapiapi_stardew/).

**Comment by Pathoschild** [comment]
The fixes I've tried haven't worked, and I have no plans to investigate further, so I'm shelving this. I'd be open to considering a pull request to fix it, though.

**Comment by Saklad5** [comment]
OK, on a Mac, it definitely is being changed during launch. It starts with the correct icon, then changes to that. What I don’t understand is where that icon is even coming from.

**Comment by Saklad5** [comment]
I’ve figured out the problem: http://community.monogame.net/t/app-icon/8283/3

Can you try setting the icon as an Embedded Resource?

**Comment by Pathoschild** [comment]
Well that's progress, thanks! I added an embedded `Icon.bmp`, and the taskbar icon disappeared:
> ![](https://user-images.githubusercontent.com/230581/39952408-19de0e7e-5564-11e8-89ff-af0800973306.png)

**Comment by Saklad5** [comment]
That’s definitely better than an incorrect icon, at least. Is it possible to build and test that without having to install the 1.3 beta? If so, I can do it now to see if the macOS dock icon is fixed.

**Comment by Pathoschild** [comment]
Yep, you can checkout the `stable` branch (which is for Stardew Valley 1.2) and cherry-pick the commit from the `wip-linuxmac-icon` branch.

**Comment by Saklad5** [comment]
Turns out the compiling process is way less intuitive than I expected. I can’t figure out what to give as an argument to `mono`. I really don’t want to install Visual Studio for this, so I’m giving up on that.

**Comment by Pathoschild** [comment]
Several attempts to change the default icon have failed for various reasons, and I have no current plans to address this, so I'll close it as _won't fix_. Pull requests are still welcome if someone wants to contribute a fix, but otherwise I think we can just accept the default icon.

**Comment by Pathoschild** [comment]
Fixed via #910 for the upcoming SMAPI 3.18.5. Thanks to @Datrio for the fix!
