### ISSUE TITLE
AfterDayStarted should not fire during the new-game intro

### ISSUE THREAD

**Issue by Sakorona** [Pathoschild/SMAPI#332]
As the tin says. Also stops a error with SDate on new games.

**Comment by Pathoschild** [comment]
As we discussed on Discord, we don't have a use case yet for an `AfterNewGameIntroStarted` event. I'll prevent `AfterDayStarted` from being raised on spring 0 (and prevent `Context.IsWorldReady` from being set), and we can discuss adding an event or context flag later if needed.

**Comment by Pathoschild** [comment]
Done in `develop` for the SMAPI 2.0 release.
