### ISSUE TITLE
Launch installer with arguments/start options 

### ISSUE THREAD

**Issue by yuukiw** [Pathoschild/SMAPI#337]
Would it be possible for the smapi installer to be able to be launched with the path (and if needed also the OS) as an argument. This would would sdvmm and other possible future mod Manger to send the game folders to the installer which then could install smapi to that location without any additional user input. Of course if the installer is launched manually it still should work like it does now.  

This would make the Manager more prone to errors due changes in the update folder structure 

_Sent from my Samsung SM-G925F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Pathoschild** [comment]
Done in `develop` for the SMAPI 2.0 release. To install SMAPI automatically, you can run something like this:
```bash
./install.exe --install --game-path "D:\Steam\steamapps\common\Stardew Valley"
```

You can also uninstall automatically if needed:
```bash
./install.exe --uninstall
```

See [documentation](https://github.com/Pathoschild/SMAPI#command-line-arguments) for more details.
