### ISSUE TITLE
Consider asset helpers for map files

### ISSUE THREAD

**Issue by Pathoschild** [Pathoschild/SMAPI#342]
Consider creating an `asset.AsMap()` helper to simplify map operations when editing map files.

**Comment by Pathoschild** [comment]
Keep in mind helpers for editing maps would also be useful when editing an already-loaded map.

**Comment by smokingfish** [comment]
I started playing around and will add to it as I get a better understanding about how everything works.
https://github.com/smokingfish/SMAPI/tree/develop/src/MarcusUndAnneMod

There is a simple extension for merging. I want to add some more content layers for other parts too.

AsMap().Merge(newMap)  -  works fine with simple tile edits and replacing the warps, lots of work still to do :)

**Comment by Pathoschild** [comment]
I have no current plans to implement this, but I'd be interested in a pull request if it worked well.
