### ISSUE TITLE
Detect dangerous mods and warn user

### ISSUE THREAD

**Issue by Pathoschild** [Pathoschild/SMAPI#347]
Detect SMAPI mods which are dangerous (e.g. can patch the game, break your save, use `unsafe` code, or crash to desktop) and show a warning in the console. This should use a combination of heuristic detection (e.g. check if they reference Harmony) and a list of known mods.

**Comment by Zaneo** [comment]
Do you also want to do a check for includes of Sockets/Http/Web related items?

**Comment by Pathoschild** [comment]
Nope, HTTP connections have pretty common legitimate uses (e.g. update checks). The purpose is really to detect mods that can destabilise the game, not detect possible malicious code (which would be very difficult).

**Comment by Pathoschild** [comment]
Done in `develop` for the upcoming 2.0 release. SMAPI currently detects two cases:
* Mods using Harmony to patch the game:
  > {Mod name} patches the game, which may impact game stability. If you encounter problems, try removing this mod first.
* Mods replacing a save serialiser:
  > {Mod name} seems to change the save serialiser. It may change your saves in such a way that they won't work without this mod in the future.
