### ISSUE TITLE
SMAPI installer fails to set launcher as executable [LINUX]

### ISSUE THREAD

**Issue by ghost** [Pathoschild/SMAPI#349]
The installer fails to set the new 'StardewValley' launcher as executable. You have to manually find the launcher inside the game folder and mark it as executable. I'm almost 80% certain that this _wasn't_ the case before. This isn't a big thing at all, but I'm sure some people will wonder why things aren't working after installing SMAPI.

OS: Manjaro KDE
Kernel: 4.9.40-1
SMAPI: 1.15.1
Stardew Valley: 1.2.33

**Comment by Pathoschild** [comment]
@Bersham It's working fine for me in ZorinOS. The installer itself doesn't set the launcher as executable, it's prepackaged with the right permissions in the download zip. Could it be something with the way you unzip the installer?

**Comment by ghost** [comment]
@Pathoschild Sorry, I was away for a while. I'm almost 99% sure it was a KDE issue. I remember some Linux Distros prevent all executable files downloaded from browsers from launching without manual intervention, including those that are compressed. And this is a fresh install of KDE, so who knows anymore.

I can't find a reasonable explanation though. I've looked through my terminal history and re-downloaded all zip files from _SMAPI 1.15.1_ to _1.15.4_ and found nothing wrong. It was probably an issue with my extraction program or a corrupt download. I'll close the issue. 👍

I rarely, if ever, have permission issues, so I might have become overly paranoid. Sorry.
