### ISSUE TITLE
Request Chinese language development authorization

### ISSUE THREAD

**Issue by coofly** [Pathoschild/SMAPI#350]
Hello, I'm sorry, I would like to make a Chinese language version based on your work and reissue in the Chinese forum. Can I ask you?
I will keep the author's name, will not modify the function, but I will mark the cultural author is me, can you?

The above is the translation of Google translation work, thank you

**Comment by Pathoschild** [comment]
Hi @coofly. Yes, you can release a Chinese version of SMAPI as long as you follow the [licensing terms](https://github.com/Pathoschild/SMAPI/blob/develop/LICENSE).
