### ISSUE TITLE
New content api doesn't seem to fully function

### ISSUE THREAD

**Issue by Midaychi** [Pathoschild/SMAPI#353]
Example, with XNB loader (Which now implements the content api), which intercepts and redirects calls to vanilla content with its own.

Let's say you put a portrait mod in XNB loader. XNB loader uses the content api to redirect calls to the portraits to its own internal folder on load, but then after load, stardew seems to un-redirect or otherwise replace these portraits back with the vanilla content folder, with the end result that the un-modified portraits are used.

**Comment by Midaychi** [comment]
recent commits in a current pre-alpha build provided by Pathoschild seem to fix the issue at least with XNBloader.

**Comment by Pathoschild** [comment]
@Midaychi Thanks for testing! As you noted, the upcoming 1.15.4 revamps the content API a bit to fix that sort of issue. Feedback on the alpha is welcome in the [SMAPI discussion thread](https://community.playstarbound.com/threads/smapi-stardew-modding-api.108375/).
