### ISSUE TITLE
a  mod does not work 

### ISSUE THREAD

**Issue by yoshifan8001** [Pathoschild/SMAPI#357]
Sebastian_GIRL becasuse it replaes seb modles

**Comment by Pathoschild** [comment]
Hello @yoshifan8001. [Sebastien_GIRL](http://www.nexusmods.com/stardewvalley/mods/463) isn't a SMAPI mod, so you need to install it by replacing files in the game's `Content` folder. See the [player FAQs](https://stardewvalleywiki.com/Modding:Player_FAQs) for more info about XNB vs SMAPI mods.

**Comment by yoshifan8001** [comment]
it was mod from smpai i went on a blocking discord  they help me fix it
srooy

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
