### ISSUE TITLE
Add SMAPI log parser

### ISSUE THREAD

**Issue by Entoarox** [Pathoschild/SMAPI#358]
A private back-end for the SMAPI log parser, for now, please with the header `Access-Control-Allow-Origin: http://host.kvdk.net` so that the host.kvdk.net/smapi/ app can stay where it is during the debugging phase

**Comment by Entoarox** [comment]
Some notes btw:
- The front-end uses a javascript based compression algorithm called `lz-string` to compress logs
- Javascript strings are in `utf16` format, and the compression uses the full capacity of that character range in the output

Just some notes that I think are important for the back-end development, I feel that keeping the lz-string compression in place would really help, since in average it compresses a log down to half size, thus allowing a lot more data to be pushed to the back-end, and the data to be send to the front-end faster.

**Comment by Pathoschild** [comment]
@Entoarox Can you post the current code for the log parser? I'd like to add it to SMAPI's web services and do a review/refactor/release cycle before further development. You'll need to release the code under the [same LGPL license as SMAPI](https://github.com/Pathoschild/SMAPI/blob/develop/LICENSE.txt), though.

**Comment by Entoarox** [comment]
You are welcome to take it from the dev url, everything is there, it is currently unlicenced but you are welcome to put up any licence for it.

**Comment by Pathoschild** [comment]
Thanks! Added in develop and pushed to [log.smapi.io](https://log.smapi.io).

The new backend brings a few benefits:
* HTTPS.
* Pretty URLs (e.g. `log.smapi.io/FML5re1r`).
* ≈85% better compression (in the one sample I compared), to enable longer logs.
* No longer needs third-party CORS proxies.
* The Pastebin dev key no longer needs to be public.

[Original prototype attached](https://github.com/Pathoschild/SMAPI/files/1425620/2017-10-29.original.prototype.zip) for the record.
