### ISSUE TITLE
SMAPI's SDate.Now() still throws an error on Spring 0 Year 1

### ISSUE THREAD

**Issue by Sakorona** [Pathoschild/SMAPI#369]
As the title says. You may want to have mods not trigger or something during that day.(the intro scene)

Edit: Steps to repro

1. have something that calls in MenuEvents_MenuChanged SDate.Now()

**Comment by Pathoschild** [comment]
Fixed in `develop` for the upcoming SMAPI 2.0 release. `SDate.Now()` will now work fine during the intro.
