### ISSUE TITLE
Problem with SMAPI start up!

### ISSUE THREAD

**Issue by TheRetroGaymer** [Pathoschild/SMAPI#372]
So I recently came back to Stardew Valley after a few weeks and now I cant use SMAPI. It used to work perfectly fine but when I try now it just freezes (Image below). I have uninstalled and reinstalled but still no luck. Anyone else have this issue? If so have you managed to fix it?

![smapi error](https://user-images.githubusercontent.com/33000741/31861882-cbc42f8c-b72c-11e7-82b1-0eb6041c6fdd.png)

**Comment by Pathoschild** [comment]
Hi @TheRetroGaymer. There's something wrong with your game's executable; try [resetting all game files](https://stardewvalleywiki.com/Modding:Player_FAQs#Reset_your_content_files) to fix that. If you're using a pirated version of the game, note that some of those change the `Stardew Valley.exe` in an incompatible way for some reason.

If you still need help, feel free to ask in [the SMAPI support thread](http://community.playstarbound.com/threads/108375) or [#modding on Discord](https://discordapp.com/invite/StardewValley). :)
