### ISSUE TITLE
Review events during new-game intro

### ISSUE THREAD

**Issue by Pathoschild** [Pathoschild/SMAPI#374]
Some world events are suppressed during the new-game intro by design (see #332), but some events are still raised which causes errors in some mods. Review and fix as needed.

**Comment by Pathoschild** [comment]
Thanks to @AdvizeGH for testing the event order in SMAPI 2.0:
> ![current order](https://user-images.githubusercontent.com/230581/31955706-2f819fb0-b8b7-11e7-8ee8-65cbbcf24fc1.png)

I suggest suppressing all save and world events until the game actually starts:
> ![](https://user-images.githubusercontent.com/230581/31955763-60c9b904-b8b7-11e7-839f-06d4f5f87c78.png)

**Comment by AdvizeGH** [comment]
## For further clarity:
![unknown 1](https://user-images.githubusercontent.com/18037818/31958583-df3ca512-b8b7-11e7-91d5-a66e7a11a770.png)

## The ideal solution would result in:
![unknown 3](https://user-images.githubusercontent.com/18037818/31958617-f6d1b348-b8b7-11e7-9343-e6af9c99bc0b.png)

A small mod that prints event execution order to the log (can be used with all SMAPI versions):
[EventOrderTestMod 1.0.zip](https://github.com/Pathoschild/SMAPI/files/1411880/EventOrderTestMod.1.0.zip)

**Comment by Pathoschild** [comment]
Done in `develop` for the upcoming SMAPI 2.1.
