### ISSUE TITLE
Old mods which doesn't updated by modder auto disabled in NEW SMAPI.

### ISSUE THREAD

**Issue by Dainishi** [Pathoschild/SMAPI#376]
It's kind of annoying, but the modder still doesn't update mod and i will not use that mod again ?
Naah..
I just use NEW SMAPI only for CHECKING new updates, and then go back to OLD SMAPI.

**Comment by Pathoschild** [comment]
Hi @Dainishi. Most mods are already compatible, but let me know if that mod isn't listed on the [compatibility list](https://stardewvalleywiki.com/Modding:SMAPI_2.0).
