### ISSUE TITLE
EventArgsInput.SuppressButton doesn't suppress mouse clicks

### ISSUE THREAD

**Issue by YonKuma** [Pathoschild/SMAPI#384]
Currently SuppressButton is rolling back keyboard presses and controller inputs, but is not rolling back mouse buttons.

**Comment by YonKuma** [comment]
I've been doing some research, and this seems like a complex issue. It's fairly easy to add code that sets the `oldMouseState` to be pressed, but doing this will only suppress some left click actions, and will not suppress any right click actions. This is because some actions (particularly pressing the action button) do not check for the previous state to decide whether to activate. This is probably so that they can be continually activated by holding down the button.

At this point, I'm honestly not sure what, if anything, can be done to stop those actions from triggering.

**Comment by Pathoschild** [comment]
Fixed in `develop` for the upcoming SMAPI 2.2 release. Thanks!
