### ISSUE TITLE
Expose version checking service in SMAPI

### ISSUE THREAD

**Issue by spacechase0** [Pathoschild/SMAPI#388]
It would be useful for letting a mod have sub-mods be version checked as well.

**Comment by Pathoschild** [comment]
Maybe something like this? This adds a helper which could eventually have methods to get mod info, compatibility, etc.
```cs
ISemanticVersion version = await helper.WebServices.FetchVersionAsync("nexus:541");
```

**Comment by spacechase0** [comment]
That would work great.

**Comment by Pathoschild** [comment]
Sub-mods are now officially supported as [content packs](https://stardewvalleywiki.com/Modding:Content_packs), which are version-checked the same way as normal SMAPI mods.
