### ISSUE TITLE
Manifest dependency `IsRequired` field not working

### ISSUE THREAD

**Issue by spacechase0** [Pathoschild/SMAPI#398]
I added this to Customize Exterior's manifest, and it would no longer load, since my development environment does not have Seasonal Immersion installed.

```json
  "Dependencies": [
    {
      "UniqueID": "Entoarox.SeasonalImmersion",
      "IsRequired": false,
    }
  ]
```

**Comment by Pathoschild** [comment]
@spacechase0 It seems to be working fine. Here's what I tried:

1. Installed SMAPI 2.1.1 and Customize Exterior 1.0.3.
2. Changed Customize Exterior's `manifest.json` to this:
   ```json
   {
     "Name": "Customize Exterior",
     "Author": "spacechase0",
     "Version": "1.0.3",
     "Description": "Change the exterior of your buildings.",
     "UniqueID": "spacechase0.CustomizeExterior",
     "PerSaveConfigs": false,
     "EntryDll": "CustomizeExterior.dll",
     "Dependencies": [
       {
         "UniqueID": "Entoarox.SeasonalImmersion",
         "IsRequired": false
       }
     ]
   }
   ```
3. Launched the game. Customize Exterior was loaded correctly:
   > ![](https://user-images.githubusercontent.com/230581/33243235-0cd9cbdc-d2b0-11e7-877f-1b3ed7d5f998.png)
4. Changed `IsRequired` to `true`.
5. Launched the game. Customize Exterior failed as expected:
   > ![](https://user-images.githubusercontent.com/230581/33243240-32c61620-d2b0-11e7-9116-acb8d3831833.png)

Can you try it again? If it's still not working, please zip the mod folder you have.

**Comment by Pathoschild** [comment]
Closed per discussion on Discord (working for @spacechase0 now).

**Comment by Pathoschild** [comment]
Reopened to look into it further, since it's happening for spacechase0 again.

**Comment by Pathoschild** [comment]
@spacechase0 I still can't reproduce this with SMAPI 2.3 and Customize Exterior 1.0.3, with its `manifest.json` changed to this ([see log](https://log.smapi.io/myXZaqXk)):
```json
{
  "Name": "Customize Exterior",
  "Author": "spacechase0",
  "Version": {
    "MajorVersion": 1,
    "MinorVersion": 0,
    "PatchVersion": 3,
    "Build": ""
  },
  "Description": "Change the exterior of your buildings.",
  "UniqueID": "spacechase0.CustomizeExterior",
  "PerSaveConfigs": false,
  "EntryDll": "CustomizeExterior.dll",
  "Dependencies": [
    {
      "UniqueID": "Entoarox.SeasonalImmersion",
      "IsRequired": false,
    }
  ]
}
```

If it still happens for you, please attach [your SMAPI log](https://log.smapi.io/) and a zip of your `Mods` folder.
