### ISSUE TITLE
A mod failed handling the SaveEvents.AfterLoad event

### ISSUE THREAD

**Issue by CipherArrow** [Pathoschild/SMAPI#407]
SMAPI log parser says it is "SMAPI" and not "GetDressed 3.5.2" mod. I posted it on their mod's bug section just in case but since the parser log says it is SMAPI then I decided to post it here since it has been going on since November 9th. I was hoping it wasn't SMAPI which is why I had waited so long.

Here is the SMAPI log parser link:
https://log.smapi.io/MHT4KHEQ

**Comment by Pathoschild** [comment]
Hi @otakuishi. Yep, that error is an issue with Get Dressed. (The error was caught and logged by SMAPI, which is why the log parser shows it under SMAPI.)
