### ISSUE TITLE
Create download page

### ISSUE THREAD

**Issue by Pathoschild** [Pathoschild/SMAPI#411]
GitHub redesigned its releases page to list files _before_ the release description, which means more players confused about which download they need. Create a user-friendly download page that links to the latest download automatically.

**Comment by Entoarox** [comment]
I've just had a look at github's API, if you want I could write up a bit of javascript that automatically finds the latest SMAPI release and packages the info into a user-friendly frame?

**Comment by Pathoschild** [comment]
@Entoarox Thanks for the offer! I'd prefer to keep the queries serverside though, since we'll need to pass GitHub authentication info to the API to avoid rate limits.

**Comment by Pathoschild** [comment]
First version implemented in `feature/download-page`, but needs design work to make it pretty:
> ![image](https://user-images.githubusercontent.com/230581/34334832-e1ba73ba-e917-11e7-967e-e363093fe8c1.png)

**Comment by Pathoschild** [comment]
Done in `develop` and pushed live. Here's the first released version for reference:
> ![](https://user-images.githubusercontent.com/230581/34341208-7159e4c2-e960-11e7-97a2-85124a3172ad.png)
