### ISSUE TITLE
Review controller support for input events

### ISSUE THREAD

**Issue by Pathoschild** [Pathoschild/SMAPI#416]
Review and fix controller support with the new `InputEvents`.

**Comment by Pathoschild** [comment]
Known issue:
* `e.IsActionButton` and `e.IsUseToolButton` don't work with controller buttons.

**Comment by catamari** [comment]
More info:
Controller buttons aren't added to `Game1.options.actionButton`. It seems that instead the controller button is checked explicitly or converted to keyboard input via `Utility.mapGamePadButtonToKey`.

**Comment by Pathoschild** [comment]
Fixed via #422 in the upcoming SMAPI 2.4.
