### ISSUE TITLE
Original pre-patch content files

### ISSUE THREAD

**Issue by Entoarox** [Pathoschild/SMAPI#417]
Sometimes there is a need to get the original files as they are in Content, rather then the patched versions supplied by SMAPI's content loader.

A way that lets mods access these files is thus very much welcome.

As to why such a thing could be useful, for starters in comparing a modded file against the vanilla one and resolving things from there (Injecting only differences between vanilla & modder yaml, tbin, etc. ratther then risk that a previous edit conflicts with another unintentionally). Another use is for if you are using a vanilla file in a way not intended by CA, and want to make sure edits made to that file dont conflict with your mods use of the file.

**Comment by Pathoschild** [comment]
I have no current plans to implement this, so I'm shelving this. I'd be open to considering a pull request to do it, though.
