### ISSUE TITLE
Add JSON converters to normalise inconsistent serialisation between platforms

### ISSUE THREAD

**Issue by Pathoschild** [Pathoschild/SMAPI#423]
Some types (like `Color` and `Point`) are serialised inconsistently between Linux/Mac and Windows. This can cause errors when reading a JSON file that was generated on a different platform. Add custom JSON converters to make sure they're serialised and deserialised consistently.

**Comment by spacechase0** [comment]
`Vector2`, `FloatRect`/`IntRect`

**Comment by Pathoschild** [comment]
@spacechase0 Where are `FloatRect` and `IntRect` defined?

**Comment by Pathoschild** [comment]
`Color` and `Point` format:
```json
// Windows
{
  "Color": "26, 51, 76, 102",
  "Point": "1, 2"
}

// Linux
{
  "Color": { "B": 76, "G": 51, "R": 25, "A": 102 },
  "Point": { "X": 1, "Y": 2 }
}
```

(`Vector2` format is the same.)

**Comment by Pathoschild** [comment]
Comparison of serialised format:

type      | on Windows                     | on Linux/Mac
--------- | ------------------------------ | ------------
Color     | `"26, 51, 76, 102"`            | `{ "B": 30, "G": 20, "R": 10, "A": 50 }`
Point     | `"1, 2"`                       | `{ "X": 1, "Y": 2 }`
Rectangle | `"{X:1 Y:2 Width:3 Height:4}"` | `{ "X": 1, "Y": 2, "Width": 3, "Height": 4 }`
Vector2   | `"1, 2"`                       | `"1, 2"`

**Comment by Pathoschild** [comment]
Done for `Color`, `Point`, and `Rectangle` in the upcoming SMAPI 2.4.
