### ISSUE TITLE
error loading spring_outdoorsTileSheet

### ISSUE THREAD

**Issue by tyrycool** [Pathoschild/SMAPI#426]
[SMAPI] An error occured in the base update loop: Microsoft.Xna.Framework.Content.ContentLoadException: Error loading "spring_outdoorsTileSheet". File not found. ---> System.IO.FileNotFoundException: Error loading "Content\spring_outdoorsTileSheet.xnb". File not found.

I entered the egg festival and I could not move my character or anything and a billion errors kept loading while on the screen due to this one problem, this file has been fine for me in the past but after updating smapi a few days ago I now have this error

**Comment by Pathoschild** [comment]
Your game's `Content\spring_outdoorsTileSheet.xnb` file seems to be missing; you can [reset your content files](https://stardewvalleywiki.com/Modding:Player_FAQs#Reset_your_content_files) to fix that. If you need any more help, feel free to post in the [SMAPI support thread](http://community.playstarbound.com/threads/108375). :)

**Comment by tyrycool** [comment]
the problem is that the file isn't missing yet it's telling me it is I even tried using 2 different mod files for this xnb and the error still occurs when entering the festival

**Comment by Pathoschild** [comment]
(Discussed via Discord; the file was missing from one folder.)
