### ISSUE TITLE
Smapi 2.3 causes occasional significant frame drops on farm.

### ISSUE THREAD

**Issue by JohnnyAppleseed12** [Pathoschild/SMAPI#427]
After a while of not playing SV I decided to update smapi and all of my mods. Afterwards I was getting drops of about 30 frames while on the farm. They would happen randomly, sometimes being set off by harvesting a plant, or opening the menu. I reinstalled the game and smapi without mods and was still getting the issue. Works fine without Smapi. The log doesn't show any errors.

**Comment by Pathoschild** [comment]
Hi @JohnnyAppleseed12. Please post a message in [the SMAPI support thread](https://community.playstarbound.com/threads/smapi-stardew-modding-api.108375), with a link to [your latest SMAPI log](https://log.smapi.io/) after a frame drop occurs. 🙂
