### ISSUE TITLE
StardewValley stop run

### ISSUE THREAD

**Issue by ghost** [Pathoschild/SMAPI#432]
[SMAPI] An error occured in the base update loop: System.ArgumentException: 值不在预期的范围内。
   在 StardewValley.Game1.updateMusic()
   在 StardewValley.Game1.Update(GameTime gameTime)
   在 StardewModdingAPI.Framework.SGame.Update(GameTime gameTime) 位置 C:\source\_Stardew\SMAPI\src\SMAPI\Framework\SGame.cs:行号 545

version: SMAPI-2.4

**Comment by Pathoschild** [comment]
Hi @xuehuashanshu. Please ask for help in the [Stardew Valley support forums](https://community.playstarbound.com/forums/stardew-support/), and link to your [uploaded SMAPI log](https://log.smapi.io/) in the message. :)
