### ISSUE TITLE
SMAPI Error

### ISSUE THREAD

**Issue by theneru** [Pathoschild/SMAPI#433]
![untitled](https://user-images.githubusercontent.com/36116916/35772418-61d88baa-0979-11e8-8675-63974ec1e128.png)

Error occurs when walking through my crop field.

**Comment by Pathoschild** [comment]
Hi @theneru. That's an issue with a mod or the game, not with SMAPI itself. Post a message in the [SMAPI support thread](https://community.playstarbound.com/threads/smapi-stardew-modding-api.108375/) and link to [your latest SMAPI log](https://log.smapi.io/), and we'll help you there. :)
