### ISSUE TITLE
API instance can't be non-public

### ISSUE THREAD

**Issue by spacechase0** [Pathoschild/SMAPI#435]
![API test](https://media.discordapp.net/attachments/156109690059751424/409761370691600395/unknown.png?width=857&height=449 "API test")

https://pastebin.com/A7ABajKj

**Comment by Pathoschild** [comment]
Fixed in `develop` for the upcoming SMAPI 2.5. The error happened because your API is marked `internal`, so SMAPI's proxy class couldn't access it. SMAPI will now rewrite all mod DLLs to inject an `[InternalsVisibleTo("StardewModdingAPI.Proxies")]` attribute.

**Comment by Pathoschild** [comment]
I reverted the previous fix since that would break debugging support.

**Comment by Pathoschild** [comment]
I played around with using `DynamicMethod` to bypass visibility checks in the IL-generated proxy class, but I'm shelving this for now. Instead I'll mark it a known issue and validate that the target type is `public` until we can address this.

**Comment by TehPers** [comment]
I wonder if it's possible to emit a proxy class for the API into the mod's assembly at runtime that's marked as public?

**Comment by Pathoschild** [comment]
This ticket is stale, I have no plans to add support for internal classes in the near future, and it's documented as a requirement for exposing an API. A pull request is welcome if someone wants to contribute an implementation though.
