### ISSUE TITLE
The sounds play for every player ingame

### ISSUE THREAD

**Issue by matthewperiut** [Pathoschild/SMAPI#440]
The mod overall is great, but the most irritating/noticeable bug is that the walking sound for all players is heard from all players.

**Comment by Pathoschild** [comment]
Hi @Slainlight. SMAPI is the mod loader and API. You can report bugs with the Makeshift Multiplayer mod on [its Nexus page](https://www.nexusmods.com/stardewvalley/mods/501). :)
