### ISSUE TITLE
Error when overwriting Event.festivalContent with a SMAPI content manager

### ISSUE THREAD

**Issue by spacechase0** [Pathoschild/SMAPI#441]
![image](https://media.discordapp.net/attachments/156109690059751424/413393548206145546/unknown.png)

Test mod: [AnimalFestival.zip](https://github.com/Pathoschild/SMAPI/files/1725156/AnimalFestival.zip)

Preloading the relevant asset (instead of loading it during IAssetLoader.Load) avoids the issue.

**Comment by Pathoschild** [comment]
Repro note: the custom event happens on Fall 5th, between 7am and 7pm, in the forest.

**Comment by Pathoschild** [comment]
Fixed in `develop` for the upcoming SMAPI 2.5.
