### ISSUE TITLE
Freeze when opening folder

### ISSUE THREAD

**Issue by afuro-dekkai** [Pathoschild/SMAPI#442]
Be sure to access the win folder
Freeze (image attached)

The same symptom appears even if you download again or change the folder to expand.
Turn off security software and freeze it.

stardew valley is also the latest version.

Please tell me the possible causes and solutions.

![default](https://user-images.githubusercontent.com/36536141/36306746-80072374-135c-11e8-99fa-0eae97cf761f.PNG)

**Comment by Pathoschild** [comment]
Hi @afuro-dekkai. That's an issue with your Windows install (not SMAPI), but you don't need to access that folder anyway. See the [install instructions](https://stardewvalleywiki.com/Modding:Installing_SMAPI_on_Windows#Install). :)
