### ISSUE TITLE
LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored

### ISSUE THREAD

**Issue by ghost** [Pathoschild/SMAPI#443]
ERROR: ld.so: object '/home/xxxxxx/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.

Os: Linux

**Comment by Pathoschild** [comment]
Hi @KarlFiabeschi. That's an issue with the Steam client, which you can probably ignore. Have you noticed any issues with SMAPI itself?

**Comment by ghost** [comment]
No issue, just the warning i reported ;)

**Comment by Pathoschild** [comment]
You can ignore it then, it shouldn't cause any issues. :)
