### ISSUE TITLE
Change in SMAPI 2.4 broke ALL's location patching

### ISSUE THREAD

**Issue by Entoarox** [Pathoschild/SMAPI#446]
ALL, due to SDV's limitations around existing locations has to do the patching at a incredibly exact point, namely after the world has been fully prepared, but before the savegame data is inserted into it.

The change in SDV 2.4 that disables UpdateTick during save loading seems to also be disabling ALL.

**Comment by Pathoschild** [comment]
I added `SpecialisedEvents.UnvalidatedUpdateTick` for use cases like that. It's the nuclear option of events: it will run on every update tick, including while the game is reading or writing a save or running async code. This is very much 'use at your peril' and will trigger a warning in the SMAPI console. See [docs on the wiki](https://stardewvalleywiki.com/Modding:SMAPI_APIs#Specialised_events) for details.
