### ISSUE TITLE
Textures dissappearing

### ISSUE THREAD

**Issue by Potato4002** [Pathoschild/SMAPI#447]
I haven't seen anybody complain about this so it might just be my computer or the way I'm doing something. What happens is that when I lauch SMAPI and play for a few minutes, all the textures and colors dissapear and I'm left with a black screen and a few brown squares where my HUD should be.
![sam house bug](https://user-images.githubusercontent.com/36648776/36444594-598ca2ae-1641-11e8-9c74-1a9981319c37.PNG)
This is a screenshot of me standing near Sam's house while the bug is active. Please respond ASAP, I really want to use this, but I haven't been able.

**Comment by Pathoschild** [comment]
Can you [upload your SMAPI log](https://log.smapi.io/) after it happens, and share the link here?

**Comment by Potato4002** [comment]
on it!

**Comment by Potato4002** [comment]
sorry for the delay
:(

**Comment by Potato4002** [comment]
just to clarify, the log is the black text screen where you input commands, right?

**Comment by Potato4002** [comment]
it says parsing failed when I try to do it.
[SMAPI-latest.txt](https://github.com/Pathoschild/SMAPI/files/1742321/SMAPI-latest.txt)
this is the log fileif that helps.
![gaaa](https://user-images.githubusercontent.com/36648776/36455317-33357c60-1665-11e8-9133-5091e9083d57.PNG)
also a screenshot of what it said

**Comment by Potato4002** [comment]
I hope you know how to fix it. Thanks in advance.

**Comment by Pathoschild** [comment]
Does it still happen if you [reset your content files](https://stardewvalleywiki.com/Modding:Player_FAQs#Reset_your_content_files)? What if you uninstall SMAPI?

**Comment by Potato4002** [comment]
I've uninstalled and reinstalled several times to no avail. And the instructions for steam to reset files say to verify integrity of game files, but if I'm correct, this will make steam verify the vanilla verison, am I right?

**Comment by Pathoschild** [comment]
It'll verify the game files, regardless of whether SMAPI is installed.

**Comment by Potato4002** [comment]
ok

**Comment by Potato4002** [comment]
So I verified the files and it still happened. Is there something else I can do?

**Comment by Pathoschild** [comment]
Does it still happen if you run `Stardew Valley.exe` directly?

**Comment by Potato4002** [comment]
morning. I went to bed yesterday. I´m at school so I´ll have to wait until later to check

**Comment by Potato4002** [comment]
doesn´t seem like it

**Comment by Pathoschild** [comment]
SMAPI itself doesn't change the graphics rendering, and none of the mods you installed through SMAPI would cause that. If it doesn't happen without SMAPI, my best guess is something on your computer is interfering with the game (e.g. faulty GPU drivers, antivirus, etc).

**Comment by Potato4002** [comment]
ok. I´ll see what i can do. Thanks anyway.
