### ISSUE TITLE
IDictionary value null check

### ISSUE THREAD

**Issue by overing** [Pathoschild/SMAPI#450]
https://github.com/Pathoschild/SMAPI/blob/c8162c2fb624f1c963615d79b557d7df5a23ff09/src/SMAPI/Framework/SContentManager.cs#L370

[Simple Crop Label] config file value "mouse_hover" is False
[SMAPI] Type 'help' for help, or 'help <cmd>' for a command's usage
[SMAPI] An error occured in the base update loop: System.Collections.Generic.KeyNotFoundException: 指定的索引鍵不在字典中。
   於 System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   於 StardewModdingAPI.Framework.SContentManager.<>c__DisplayClass33_0.<DisposeFor>b__1(String key, Type type) 於 C:\source\_Stardew\SMAPI\src\SMAPI\Framework\SContentManager.cs: 行 376
   於 StardewModdingAPI.Framework.SContentManager.<>c__DisplayClass32_1.<InvalidateCache>b__1(String key, Type type) 於 C:\source\_Stardew\SMAPI\src\SMAPI\Framework\SContentManager.cs: 行 331
   於 StardewModdingAPI.Framework.Content.ContentCache.Remove(Func`3 predicate, Boolean dispose) 於 C:\source\_Stardew\SMAPI\src\SMAPI\Framework\Content\ContentCache.cs: 行 141
   於 StardewModdingAPI.Framework.SContentManager.<>c__DisplayClass32_0.<InvalidateCache>b__0() 於 C:\source\_Stardew\SMAPI\src\SMAPI\Framework\SContentManager.cs: 行 328
   於 StardewModdingAPI.Framework.SContentManager.WithWriteLock[T](Func`1 action) 於 C:\source\_Stardew\SMAPI\src\SMAPI\Framework\SContentManager.cs: 行 796
   於 StardewModdingAPI.Framework.SContentManager.InvalidateCache(Func`3 predicate, Boolean dispose) 於 C:\source\_Stardew\SMAPI\src\SMAPI\Framework\SContentManager.cs: 行 323
   於 StardewModdingAPI.Framework.SContentManager.<>c__DisplayClass33_0.<DisposeFor>b__0() 於 C:\source\_Stardew\SMAPI\src\SMAPI\Framework\SContentManager.cs: 行 376
   於 StardewModdingAPI.Framework.SContentManager.WithWriteLock(Action action) 於 C:\source\_Stardew\SMAPI\src\SMAPI\Framework\SContentManager.cs: 行 780
   於 StardewModdingAPI.Framework.SContentManager.DisposeFor(ContentManagerShim shim) 於 C:\source\_Stardew\SMAPI\src\SMAPI\Framework\SContentManager.cs: 行 372
   於 StardewModdingAPI.Framework.ContentManagerShim.Dispose(Boolean disposing) 於 C:\source\_Stardew\SMAPI\src\SMAPI\Framework\ContentManagerShim.cs: 行 47
   於 StardewValley.Game1.CleanupReturningToTitle()
   於 StardewValley.Game1.Update(GameTime gameTime)
   於 StardewModdingAPI.Framework.SGame.Update(GameTime gameTime) 於 C:\source\_Stardew\SMAPI\src\SMAPI\Framework\SGame.cs: 行 545

**Comment by Pathoschild** [comment]
The content managers have been significantly revamped in SMAPI 2.6. Let me know if this still happens when that's released.
