### ISSUE TITLE
Stardew Issue

### ISSUE THREAD

**Issue by kaylirose16** [Pathoschild/SMAPI#464]
When I start a new game it goes to black after the bus scene and freezes there with birds chirping. I'm not sure if it just can't handle the mods I have installed or if its a bug in the system.

**Comment by Pathoschild** [comment]
Hi @kaylirose16. Can you [upload your SMAPI log](https://log.smapi.io/) after it happens, then add a message in [the support thread](https://community.playstarbound.com/threads/smapi-stardew-modding-api.108375) or [on Discord](https://stardewvalleywiki.com/Modding:Community) with a link to it? We'll help you troubleshoot which mod is causing it there. :)
