### ISSUE TITLE
Version error 2.5.4 in Stardew Valley

### ISSUE THREAD

**Issue by gogshow** [Pathoschild/SMAPI#465]
If you use INSTALL to update SMAPI 2.5.4 it will continue to display as version 2.5.3 when running the console.
It is advisable to do the replacement manually through the INTERNAL folder.

**Comment by Pathoschild** [comment]
The version changes correctly for me:
> ![](https://user-images.githubusercontent.com/230581/38178798-4e8c6cc4-35e8-11e8-87eb-098c64456dc8.png)

It sounds like the installer isn't working for you. Can you run it again, and post a screenshot of the full installer window when it shows the green text at the end?

**Comment by SpringDaGamer** [comment]
so, problem with the download link for the latest smapi, i cant download it at all, says failed - forbidden

**Comment by Pathoschild** [comment]
@SpringDaGamer Does it still happen now? If so, can you post a screenshot of that error?
