### ISSUE TITLE
Error with No Crows mod

### ISSUE THREAD

**Issue by Inny78** [Pathoschild/SMAPI#476]
As I'm on Windows 10 Fall Creator Update, I'm quite surprised to see this message on the console:
_[NoCrows] You've downloaded the Windows version of No Crows. If your game crashes at the end of the day, you need to download the right version for your computer instead!_
Looks like there is a bug with the way it handles the check.
- Steam version of Stardew Valley
- SMAPI 2.5.5
- [No Crows 1.1.0 on Nexus](https://www.nexusmods.com/stardewvalley/mods/1682/).

**Comment by Pathoschild** [comment]
Hi @Inny78. No Crows always logs that message, it doesn't actually check your platform. That has little to do with SMAPI, though. Feel free to post suggestions on that mod's Nexus page instead. :)
