### ISSUE TITLE
Game freezes on shipping screen

### ISSUE THREAD

**Issue by acravatta** [Pathoschild/SMAPI#482]
(Log:  https://log.smapi.io/8FSJsAY9 )

Un-modded game 'locks up' at end-of-day profit tally screen. Cursor dims and is unresponsive as soon as the tally screen appears and does not 'unlock', nor does the game proceed to save the game information. The shooting star animations in the background DO still play. The only course of action in this case is to close the game externally. Game data is not saved.

Additional note (unsure if related, just trying to cover all bases) - There is an event that happens when the player steps outside where Evelyn gives the player a gardening pot (new in 1.3 I believe). This happens in this particular case.

The game saves normally if the player goes to bed without selling anything (no profit tally screen).
Game files have been validated through Steam.

**Comment by Pathoschild** [comment]
Fixed in `develop` for the upcoming SMAPI 2.6-beta.3. Thanks for reporting it!
