### ISSUE TITLE
Warning CS8032 when compiling mod against SMAPI 2.6.3 beta.

### ISSUE THREAD

**Issue by catamari** [Pathoschild/SMAPI#483]
OS: Windows 10 Home

`1>CSC : warning CS8032: An instance of analyzer StardewModdingAPI.ModBuildConfig.Analyzer.NetFieldAnalyzer cannot be created from C:\...\GiftTasteHelper\packages\Pathoschild.Stardew.ModBuildConfig.2.1.0-beta-20180428\analyzers\dotnet\cs\StardewModdingAPI.ModBuildConfig.Analyzer.dll : Could not load file or assembly 'Microsoft.CodeAnalysis, Version=2.4.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified..
1>CSC : warning CS8032: An instance of analyzer StardewModdingAPI.ModBuildConfig.Analyzer.ObsoleteFieldAnalyzer cannot be created from C:\...\GiftTasteHelper\packages\Pathoschild.Stardew.ModBuildConfig.2.1.0-beta-20180428\analyzers\dotnet\cs\StardewModdingAPI.ModBuildConfig.Analyzer.dll : Could not load file or assembly 'Microsoft.CodeAnalysis, Version=2.4.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified..`

**Comment by Kevin-Mok** [comment]
Strange. I got this issue installing it on Mint but not on Ubuntu, even though Mint is based on Ubuntu? :thinking: 
```
Unhandled Exception:
System.IO.FileNotFoundException: Could not load file or assembly 'System.Management, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies.
File name: 'System.Management, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
  at StardewModdingApi.Installer.InteractiveInstaller.Run (System.String[] args) [0x00025] in <7324f88dc4524a57b82d853323e7f820>:0 
  at StardewModdingApi.Installer.Program.Main (System.String[] args) [0x00005] in <7324f88dc4524a57b82d853323e7f820>:0 
[ERROR] FATAL UNHANDLED EXCEPTION: System.IO.FileNotFoundException: Could not load file or assembly 'System.Management, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies.
File name: 'System.Management, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
  at StardewModdingApi.Installer.InteractiveInstaller.Run (System.String[] args) [0x00025] in <7324f88dc4524a57b82d853323e7f820>:0 
  at StardewModdingApi.Installer.Program.Main (System.String[] args) [0x00005] in <7324f88dc4524a57b82d853323e7f820>:0 
```

**Comment by Pathoschild** [comment]
@Kevin-Mok That's a different issue. Can you create a separate ticket for it, and describe how you're launching the installer and what terminal you use?

**Comment by Pathoschild** [comment]
@tstaples This seems to happen if you don't have Visual Studio 2017, since code analyzers are a pretty new feature.

**Comment by catamari** [comment]
I was compiling with VS2017 though. Perhaps I need to update though? What version are you running?

**Comment by Pathoschild** [comment]
@tstaples I have VS Community 2017 15.6.6. Do you have an older version?

**Comment by catamari** [comment]
Yeah I was using VS Community 2017 15.1. Updating fixed it.

**Comment by mralbobo** [comment]
Just throwing this out there, but it might be worth mentioning this in the migration guide.
(I added a quick mention to it)

**Comment by Pathoschild** [comment]
@mralbobo Thanks! I expanded your addition a bit.
