### ISSUE TITLE
Error when attempting to launch SMAPI 2.6-beta.3

### ISSUE THREAD

**Issue by Zachbrak** [Pathoschild/SMAPI#486]
After installing the new beta version of SMAPI with the 1.3 version of Stardew I get an exception thrown and it fails to launch. Here is the error log: https://log.smapi.io/m2Un1vbK

I am running windows 7 and had a fresh install of stardew and SMAPI.

**Comment by Pathoschild** [comment]
Hi @zburke911. See this [section in the player guide](https://stardewvalleywiki.com/Modding:Player_Guide/Troubleshooting#.22SEHException:_External_component_has_thrown_an_exception.22). :)
