### ISSUE TITLE
The game doesn't launch on Linux after installing SMAPI 2.6 Beta 3

### ISSUE THREAD

**Issue by anakcj** [Pathoschild/SMAPI#487]
I just installed SMAPI in Manjaro and Solus and have the exactly same issue in both. After installing SMAPI and try to launch Stardew Valley through Steam it says "running" for a few seconds and then just back to normal without launching anything nor showing a message.

Before the update I had a previous version of SMAPI on Solus that worked well (2.5.4), but not in Manjaro (I couldn't install it). I uninstalled it before try 1.3 beta and everything was okay in both OS, and also everything works again after uninstalling SMAPI again. I've also reinstalled SMAPI a few times and it's the same.

**Comment by Pathoschild** [comment]
@anakcj Can you [come ask on Discord](https://stardewvalleywiki.com/Modding:Community#Discord)? I'll need you to run some tests to figure out why that's happening for you.
