### ISSUE TITLE
Overhaul content caching

### ISSUE THREAD

**Issue by Pathoschild** [Pathoschild/SMAPI#488]
SMAPI caches content assets differently than the game, which causes some issues in SDV 1.3:
* festival issue (484);
* farmer visual bugs (e.g. [on the load screen](https://community.playstarbound.com/threads/smapi-stardew-modding-api.108375/page-118#post-3270887) and [farmer sprites](https://community.playstarbound.com/threads/smapi-stardew-modding-api.108375/page-118#post-3271131)).

**Comment by Pathoschild** [comment]
Some background: the issue is that SMAPI has a centralised content cache with what amounts to garbage collection counters to decide when an asset is no longer needed by any loaded content managers. SDV 1.3 makes content-manager-specific changes to the data it loads in some cases (like adding a field to the festival data), and expects that data not to be propagated to other content managers; but since there's a central cache, it does get propagated. The fix is to overhaul the content core to eliminate the central cache, though mods will have a higher performance impact when they load/edit assets.

**Comment by Entoarox** [comment]
Perhaps handle it differently - have a central cache that you then *copy* things from into per-manager cache's.

That way you get the performance benefit of a central cache, but fix the assumptions SDV makes about having multiple CM's

**Comment by Pathoschild** [comment]
That's a good idea. I'll need to write logic to clone assets, but fortunately the game only uses a few specific types so that should be easy enough.

**Comment by Pathoschild** [comment]
Done in `develop` for the upcoming SMAPI 2.6-beta.9. The cache is fully decentralised for now, but we can add a centralised clone cache if needed later.
