### ISSUE TITLE
2.6-beta.4 Update Missing?

### ISSUE THREAD

**Issue by mpql** [Pathoschild/SMAPI#490]
When I start SMAPI, I see:

```[SMAPI] You can update SMAPI to 2.6-beta.4: https://smapi.io```

However, the latest version on the site and in releases appears to be 2.6-beta.3. Further confusing, the link on smapi.io is:

> https://github.com/Pathoschild/SMAPI/releases/download/2.6-beta.4/SMAPI-2.6-beta.3-installer.zip

Notice the `2.6-beta.4` in the URL.

Apologies if this is not the quite correct place to report this since this isn't a _source code_ issue.

**Comment by blouwho** [comment]
I have the same message, and have been hunting for beta 4 also

**Comment by Pathoschild** [comment]
Beta 4 was released for a few minutes, but I removed it due to issues found in the release. Unfortunately SMAPI still sees an update due to the Git tag. I'll deploy SMAPI 2.6 beta 5 soon. Sorry about that!

**Comment by mpql** [comment]
Ah, no worries! And don't apologize, thanks for everything you do; SMAPI is great! :D

**Comment by Pathoschild** [comment]
SMAPI 2.6-beta.5 is now available!
