### ISSUE TITLE
Crash with last SMAPI since 1.3 last update

### ISSUE THREAD

**Issue by koalaoo** [Pathoschild/SMAPI#492]
Hello, since last beta update, we have a systematic bug with SMAPI.
- We cannot save anymore and go to the next day. Crash happens as soon as we get asleep. :/ Before that last update we could play perfeclty. 

error is : 

07:53:59 | ERROR | SMAPI | An error occured in the overridden update loop: System.ArgumentException: The asset key or local path contains invalid characters.    à StardewValley.Game1.Update(GameTime gameTime) dans C:\Users\gitlab-runner\gitlab-runner\builds\5c0f9387\0\chucklefish\stardewvalley\Farmer\Farmer\Game1.cs:ligne 1831    à StardewModdingAPI.Framework.SGame.Update(GameTime gameTime) dans C:\source\_Stardew\SMAPI\src\SMAPI\Framework\SGame.cs:ligne 242
-- | -- | -- | --

[SMAPI-crash.txt](https://github.com/Pathoschild/SMAPI/files/1976388/SMAPI-crash.txt)

Does anyone know how to fix this , please? Thanks everyone for this great mod :) I use it since my first plays!

have a good game anyone that can still luckily play ;)

**Comment by Pathoschild** [comment]
@koalaoo Can you attach a zip of your `Mods` folder and [your save folder](https://stardewvalleywiki.com/Saves)?

**Comment by koalaoo** [comment]
[Mods.zip](https://github.com/Pathoschild/SMAPI/files/1976390/Mods.zip)


[Saves.zip](https://github.com/Pathoschild/SMAPI/files/1976391/Saves.zip)

[startup_preferences.zip](https://github.com/Pathoschild/SMAPI/files/1976392/startup_preferences.zip)


Hey :) Thanks for your fastest answer. Here are the files in zip! Let met know if they are the good ones ^^ Waiting for your next answer. Thx thx thx

**Comment by Pathoschild** [comment]
Thanks! I'll take a look this weekend. (Sorry for the delay; things are a bit busy with the Stardew Valley beta!)

**Comment by koalaoo** [comment]
hehe I understand :) thanks a lot ! Have a good week end!! I'll wait ^^ I put a star for SMAPI

**Comment by koalaoo** [comment]
One more thing I used to have Lookupanything Mod while playing the 10days of game. Now it seems to be broken since last 1.3 update. it might help to understand...may be ^^

**Comment by Pathoschild** [comment]
@koalaoo Your save works fine for me, and none of those mods should cause any issues. Do you have an unofficial language patch?

**Comment by koalaoo** [comment]
Hello,
Thank you very much for having a look at it! No I don't have a language
pack, I'm playing in English :/

That's kinda strange. On an other post, two other guys wrote they had the
same issue since last 1.3 update, few days ago. That like me they could
play and now not anymore with their friends.

May be its with I dunno firewall or programs or something else? I use to
have lookup anything and might be for one day but playing solo pelicantts.

Thanks anyway for looking at my problem, this is so nice of you.

Have a lovely weekend.

**Comment by koalaoo** [comment]
I'm gonna try on another pc to look if it's not my config which blocks the
save.

Big thx..... Really big thx

**Comment by Pathoschild** [comment]
@koalaoo Can you [come ask on Discord](https://stardewvalleywiki.com/Modding:Community#Discord)? I can create a custom build of SMAPI to test what's happening; if it's a SMAPI issue, I can fix it in the next beta update.

**Comment by koalaoo** [comment]
Hi Jesse,
I did update my nvidia drivers and uninstall and reinstall xna. I also
updated lookupanything and npcmap locations. And now it seems to save fine.
I will do some other test to check is everyithing's still fine.

Should I strill put the error log on discord since it's working now?



<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Garanti
sans virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

2018-05-06 18:15 GMT+02:00 Jesse Plamondon-Willard <notifications@github.com

**Comment by Pathoschild** [comment]
No need. Glad you got it working! :)

**Comment by koalaoo** [comment]
Thx Jesse!! great work, great support! continue your nice work , it's very
appreciated by the Community! long life to SMAPI :D

2018-05-08 5:52 GMT+02:00 Jesse Plamondon-Willard <notifications@github.com>
:
