### ISSUE TITLE
Exception when returning to the title screen in certain locales

### ISSUE THREAD

**Issue by catamari** [Pathoschild/SMAPI#493]
With SMAPI 2.5.5/SDV 1.2.33 I get https://log.smapi.io/cxe4AZmJ if I do the following:
1. Change the locale to Japanese
2. Restart the game
3. Load a save
4. Exit to the title.
Only seems to happen in Japanese, Portuguese and Spanish.
I tried multiple saves too so it's unrelated to that.

**Comment by Pathoschild** [comment]
@tstaples Thanks for reporting it! That should already be fixed in SMAPI 2.6 beta.
