### ISSUE TITLE
Improve installer readability on Mac

### ISSUE THREAD

**Issue by Pathoschild** [Pathoschild/SMAPI#495]
Continuing from #327, also fix the installer's text color on Mac:
> ![](https://user-images.githubusercontent.com/230581/39670113-9c4de49e-50cb-11e8-9243-15b380599236.png)

**Comment by Saklad5** [comment]
I don’t think this is a problem with SMAPI. It was fine for me.

Couldn’t you just use the foreground color specified by the terminal?

**Comment by Pathoschild** [comment]
@Saklad5 SMAPI can change color scheme to match the background color, but that value isn't provided on Mac. I'll try checking the default foreground color; if that's specified, I can switch color scheme based on that.

**Comment by Saklad5** [comment]
You could just forgo the colors entirely, as well. Most CLI programs don’t color-code. If you do want to use colors, make sure it is using the ANSI colors that have been set, since that can be changed by the user. If you want it to be blue, use whatever has been configured to be “blue”.

**Comment by Pathoschild** [comment]
The installer is meant for users who often aren't comfortable with CLI tools, so I think the color coding is useful. SMAPI uses .NET Framework's standard console colors, which are determined by the implementation for that OS.

**Comment by Pathoschild** [comment]
Fixed in `develop` for the upcoming SMAPI 2.6-beta.9.

**Comment by Saklad5** [comment]
So the blame lies with Mono’s implementation. In that case, any changes should come from them, not here. Carry on.
