### ISSUE TITLE
Steam Controller interface could easily be fixed with a silent command line option

### ISSUE THREAD

**Issue by formicsapien** [Pathoschild/SMAPI#496]
Steam Controller support (and general controller input mapping) doesn't work with SMAPI simply because steam thinks the command prompt box that pops up is the game, and when Stardew Valley launches it's a different application and will not recognize the inputs.  If we could get a command line option that disables the prompt from showing this problem would be fixed.

**Comment by Pathoschild** [comment]
Merged into #222.

**Comment by formicsapien** [comment]
The "Input mapper" program and the fact that other controllers "work" does not help fix this issue.

I did find another workaround, and I think you should make it visible to people trying to use features with the Steam Input overlay.  You do NOT add SMAPI as an external program, but instead add it as a launch option to the original game.  You have to launch essentially what the entire shortcut for SMAPI would be. For example this is what I use and it works perfect:

`C:\Program Files (x86)\Steam\steamapps\common\Stardew Valley\StardewModdingAPI.exe" %command%`

**Comment by Pathoschild** [comment]
@formicsapien #222 is a ticket to address this issue; InputMapper is just a workaround mentioned in that ticket. We can discuss here if you want, and I'll summarise the result there.

With regards to your change, that's what the [SMAPI install guide](https://stardewvalleywiki.com/Modding:Installing_SMAPI_on_Windows) says to do in the first place. I didn't know you were adding Steam as an external program. Next time someone reports controller problems, I'll make sure to ask whether they set the launch options correctly. Here's hoping that's the solution for other affected users too!
