### ISSUE TITLE
SMAPI broken the game.. 

### ISSUE THREAD

**Issue by netcan** [Pathoschild/SMAPI#497]
there is a log: https://log.smapi.io/BcvW7AGk

**Comment by Pathoschild** [comment]
Hi @netcan. That error is happening in .NET Framework (not SMAPI), and usually means something is wrong with your computer's memory. I suggest [running memtest](http://www.tomshardware.com/faq/id-1906201/test-memory-memtest.html) to check for hardware issues.

**Comment by netcan** [comment]
I have solved it by reinstalling XNA framework: https://www.microsoft.com/en-us/download/details.aspx?id=20914, I found that it has different size from game's.
