### ISSUE TITLE
Unable to install beta on Windows 10?

### ISSUE THREAD

**Issue by southerngoth** [Pathoschild/SMAPI#498]
I keep trying to update smapi to the beta version but I keep getting this error. I've tried downloading and deleting it multiple times to see if it was a one time issue but apparently it keeps doing it. Help?
(I've also tried typing in the file path but that won't work either)

![image](https://user-images.githubusercontent.com/39065199/39718319-ed38edca-5203-11e8-8409-d18b4bbb9e64.png)

**Comment by Pathoschild** [comment]
Can you post a screenshot of what happens when you enter the path?

**Comment by LinkHyruleI** [comment]
Go on the stardew valley app go on properties, see the directory, do a ctrl+C ctrl+V and it should work!

**Comment by southerngoth** [comment]
So I followed LinkHyrulel's suggestion's and it worked but now I'm unable to even open Stardew? This is a re-install after I got rid of everything on my system thanks to a lovely windows crash a few months back. I double click the application .exe and even tried right click open but still get nothing. Help?

**Comment by Pathoschild** [comment]
@southerngoth Come [ask on Discord](https://stardewvalleywiki.com/Modding:Community#Discord) and we'll help you get it working. The GitHub issues are only for SMAPI development tasks, so you'll get a lot more help there. :)
