### ISSUE TITLE
Smapi not opening Mods!

### ISSUE THREAD

**Issue by LinkHyruleI** [Pathoschild/SMAPI#499]
everytime that i open smapi 2.6 the mods are not loaded, the smapi close an the game start without mods. Please what do i have to do?

**Comment by Pathoschild** [comment]
Can you [upload your SMAPI log](https://log.smapi.io/) (see instructions on that page) and post the link here?

**Comment by LinkHyruleI** [comment]
here https://log.smapi.io/D3NrWVvv this is the error, if you be able to tell me what to do i will be very happy
when i try to play the game it dont work, i click in load and the intro start again.

**Comment by Pathoschild** [comment]
Can you come [ask on Discord](https://stardewvalleywiki.com/Modding:Community)? We'll need to investigate further, and we only use the GitHub issues to track development tasks. :)
