### ISSUE TITLE
Player skins visually bugging

### ISSUE THREAD

**Issue by SeooY** [Pathoschild/SMAPI#501]
When playing co-op with a friend using SMAPI 2.6-beta.8, whenever she joined (I'm the host) and entered the same room with me our skins visually bugged out, with different results for each of us.

This is what I see:
![image](https://user-images.githubusercontent.com/39110993/39794724-7183c6c8-5311-11e8-85c1-398955fee4cb.png)

And this is what she sees:
![image](https://user-images.githubusercontent.com/39110993/39794754-9315c052-5311-11e8-9ada-9823771950d7.png)

Her skin usually is the one in the first image, and mine usually is the one in the second, only that for each of us the other's skin is overriding ours. We only had SMAPI installed with ConsoleCommands. This is the log I got:
https://log.smapi.io/36Pji5rS

**Comment by Pathoschild** [comment]
This should be fixed via #488.
