### ISSUE TITLE
Support for external tools (StardewPatcher)

### ISSUE THREAD

**Issue by Entoarox** [Pathoschild/SMAPI#502]
Support for mods to depend on external tools like Stardew Patcher.

Stardew Patcher identifies itself by adding a new attribute into the patched assembly:
https://cdn.discordapp.com/attachments/156109690059751424/443859597791592450/unknown.png

**Comment by Pathoschild** [comment]
I have no plans to add this in the foreseeable future. Harmony is bundled with SMAPI now, Stardew Patcher was never released (and I'm not a fan of the executable patching approach), and there are no other external tools that would use this.

**Comment by Entoarox** [comment]
One mistake, Stardew Patcher *was* released: https://www.nexusmods.com/stardewvalley/mods/2268

I have just not seen a point in working further on it as no mods ended up taking advantage of the functionality it provided, seeming to prefer using the much less safe Harmony method instead.
