### ISSUE TITLE
smapi says im runnig stardew valley 1.2.33 

### ISSUE THREAD

**Issue by tyler06080608** [Pathoschild/SMAPI#503]
smapi says I'm running stardew valley 1.2.33 and to update it but I just installed stardew valley and it is up to date

[03:13:38 ERROR SMAPI] Oops! You're running Stardew Valley 1.2.33, but the oldest supported version is 1.3.9. Please update your game before using SMAPI.

I am running smapi 2.6 beta 8

**Comment by Pathoschild** [comment]
@tyler06080608 Make sure you install [SMAPI 2.5.5](https://smapi.io/) instead. You should only use SMAPI 2.6 beta if you've opted in to the Stardew Valley 1.3 beta.
