### ISSUE TITLE
Asset key or local path contains invalid characters

### ISSUE THREAD

**Issue by d0x7** [Pathoschild/SMAPI#505]
Hello,

I guess since the latest SMAPI update (SDV 1.3.10, SMAPI 2.6-beta.8) I'm having really annoying crashes.

At some point a error appears in the console and when that happens I cannot save the game. When I'm going to sleep the game crashes.

SMAPI Log: https://log.smapi.io/QCqSPzqc
Crash Log: https://log.smapi.io/gfZ5ka7n

If you need the save game I can upload it for you. 

Thanks

**Comment by Pathoschild** [comment]
@d0x7 Does it still happen if you [reset your game files](https://stardewvalleywiki.com/Modding:Player_Guide/Troubleshooting#Reset_your_content_files)? If so, can you attach [your save files](https://stardewvalleywiki.com/Saves)?

**Comment by d0x7** [comment]
@Pathoschild I've just verified the integrity of the game files via steam, no files were broken or missing.

As this wouldn't fix the issue I uninstalled stardew valley and installed it again.
The issue is still happing.

Save Game: * removed *
Screenshot: ![stardew](https://user-images.githubusercontent.com/17951467/39919481-1151affe-5514-11e8-89d9-d2848c79ca90.PNG)
Crash Log: https://log.smapi.io/y9WzSgtH
Crash Log of 2nd Player: https://log.smapi.io/MExMT7Rd

The NoSuitableGraphicsDeviceException isn't related to SMAPI (or maybe it is, but at least not related to this bug report).

I'm not very aware of C# nor the Stardew Modding API, but could the issue be about the fact that I named my horse 'Lotta ♡'? Maybe \u2661 is causing an issue?

To reproduce just load the savegame, maybe install CJB Cheats Menu (I guess it also happens without it) and play some SDV, like collect the animal stuff and so on. After some time the error will occur.

**Comment by Pathoschild** [comment]
Fixed in the upcoming SMAPI 2.6-beta.12. Thanks for reporting it!

**Comment by d0x7** [comment]
Yeah, sure but I have a question. As said earlier I don't know about the SDV Modding API, so the question is maybe dumb, but what's the use of throwing another exception? Does this exception get catched and handled correctly, but the other won't or what? Thanks anyways.

**Comment by Pathoschild** [comment]
You mean why does 69850cb1143110877ad0eea206a6537fe42c9063 fix it? The error happens when the game loads dialogue from a file named `Characters\Dialogue\Lotta <.xnb` (`<` turns into a heart). The game detects if a `ContentLoadException` is thrown, and if so assumes there's no dialogue for this character. However SMAPI was throwing a different exception type, which the game didn't handle. So throwing the exception that the game expects ensures that it treats an invalid file name the same way as a missing file.
