### ISSUE TITLE
RE: SMAPI 2.6 beta-8 for Mac?

### ISSUE THREAD

**Issue by LustyFarmer** [Pathoschild/SMAPI#506]
Hey I downloaded your SMAPI 2.6 beta-8 because some of the mods I had for my stardew valley updated, and needed that specific SMAPI- but my terminal said the SMAPI you got there (NOT the developers one, the normal SMAPI 2.6 beta-8) was for WINDOWS, not MAC. When's the Mac one coming out?

**Comment by Pathoschild** [comment]
Hi @LustyFarmer. Make sure you run the `install on Mac.command` file the error mentions instead.

**Comment by LustyFarmer** [comment]
I'm not a techno geek so i open the terminal and type- like a tutorial video on youtube shows-

mono (then drag and drop the install.exe from the downloaded SMAPI 2.6 beta-8) and hit enter but that's where the error shows up saying it is for windows

so where do i put Mac.command in that then? after the mono but before the install.exe? Cause i really am not good with computers so i don't get this tbh

**Comment by Pathoschild** [comment]
Just double-click `install on Mac.command`. If it asks, choose to execute or run it. :)

**Comment by LustyFarmer** [comment]
if i knew where to find Mac.command I wouldn't be having this problem... do i type it into the terminal and then click it? I said i don't know anything about computers so i obviously don't know how to do this.

**Comment by LustyFarmer** [comment]
so open terminal. type in 'install on Mac.command' and hit enter and that's it?

**Comment by Pathoschild** [comment]
The `install on Mac.command` file should be in the same folder as the `install.exe`:
![](https://user-images.githubusercontent.com/230581/39936009-0e2b1d56-5519-11e8-865b-5682b0e03345.png)

**Comment by LustyFarmer** [comment]
oh. like i said i m not good with computers XD

thx

**Comment by LustyFarmer** [comment]
sorry for any inconvenience.

so, just to check. i just click that then right?

**Comment by Pathoschild** [comment]
Yep, I think you can just double-click that file. (I'm not very familiar with Mac though.)

**Comment by LustyFarmer** [comment]
thx it works now :D
