### ISSUE TITLE
Crash on launch.

### ISSUE THREAD

**Issue by Naoeaoe** [Pathoschild/SMAPI#508]
It seems to occur with both a pirated GOG and the Steam version, sorry if it's an already reported issue! :<
![smapi](https://user-images.githubusercontent.com/29278305/39968213-563be23c-56d2-11e8-8b31-b3f6ba0886a4.PNG)

**Comment by Pathoschild** [comment]
See [_"SEHException: External component has thrown an exception"_](https://stardewvalleywiki.com/Modding:Player_Guide/Troubleshooting#.22SEHException:_External_component_has_thrown_an_exception.22) in the troubleshooting guide for help with that.
