### ISSUE TITLE
No Sound

### ISSUE THREAD

**Issue by ghost** [Pathoschild/SMAPI#509]
I have no sound while using SMAPI, but I do when using normal game. I'm using SMAPI 2.6-beta.12,
and Stardew Valley 1.3.10 beta. 

SMAPI-latest.txt log:  
[SMAPI-latest.txt](https://github.com/Pathoschild/SMAPI/files/1998570/SMAPI-latest.txt)

**Comment by Pathoschild** [comment]
Hi @jellyjelly81. The GitHub issues are only for SMAPI development tasks, and few users will see your question here.

To get help with SMAPI problems, I suggest one of these:
* post in the [SMAPI support thread](https://community.playstarbound.com/threads/108375);
* or [ask on Discord](https://stardewvalleywiki.com/Modding:Community#Discord).
