### ISSUE TITLE
Which .exe to use for Mac?

### ISSUE THREAD

**Issue by LustyFarmer** [Pathoschild/SMAPI#510]
so my SMAPI said it could update to 2.6-beta12 and i found that, and downloaded it

followed the commands shown in an easy tutorial video I reference everytime SMAPI updates, to remember how to update/reinstall- figured this out with the beta update that i had to choose the MAC exe not the windows one- I put the Mac exe command in like I have with previous versions that worked.

did not work. tried with the linux, same result. anyone know why the SMAPI update ain't working? Cause now i can not use mods on any of the farms I try hosting in multiplayer and when i start a new game/host a new farm in multiplayer, then quite to the main menu of the game then try and go back to it the farm is gone.

even if i delete all my other farms. and my terminal keeps saying 'SMAPI can update' but it won't LET me update

**Comment by Pathoschild** [comment]
Just double-click on `install on Mac.command` to install SMAPI.

Which video guide are you using? I suggest using [the install guide](https://smapi.io/install) linked from the download page; videos are often outdated. :)

**Comment by LustyFarmer** [comment]
using this video link which has proven useful and easy to understand in the past- https://www.youtube.com/watch?v=NjKJjDaGUiU&t=276s

but thx for reminding me, i got memory issues and keep forgetting there's different commands for it for Mac smapi

**Comment by Pathoschild** [comment]
Thanks! I added a comment on the video, hopefully the author will update it.
