### ISSUE TITLE
Suppress multiplayer debug output

### ISSUE THREAD

**Issue by Pathoschild** [Pathoschild/SMAPI#511]
The game writes a large number of debug messages like this:
```
DebugOutput: Ping: 1.59673ms
```

Suppress those messages unless SMAPI is in verbose mode.

**Comment by danvolchek** [comment]
One debug message that SMAPI may also want to filter out is of the form
```
DebugOutput: playerPos: {X:433 Y:622}, mousePos: 292, 379
```
This gets written to the console every update tick that the player's mouse moves when they're aiming with a slingshot.

**Comment by Pathoschild** [comment]
Both done in `develop` for the next SMAPI 2.6 beta.
