### ISSUE TITLE
Assembly Loader fails to rewrite mods that use Netcode.NetInt

### ISSUE THREAD

**Issue by bcmpinc** [Pathoschild/SMAPI#514]
A mod that references the NetInt class when compiled on Linux fails to load on Windows.

When testing with Wine (I don't have windows) I got this exception:
```Error: Mono.Cecil.AssemblyResolutionException: Failed to resolve assembly: 'StardewValley, Version=1.3.6703.20048, Culture=neutral, PublicKeyToken=null' ```
For the full log, see: https://log.smapi.io/0dLFVNq3 . Make sure to enable TRACE & DEBUG.

##Steps to reproduce:
Compile the following Mod on Linux:
```c#
using System;
using System.Reflection.Emit;
using StardewModdingAPI;

public class ModEntry : Mod
{
    public override void Entry(IModHelper helper) {
        Netcode.NetInt test = new Netcode.NetInt(42);
        test.Value += 2;
    }
}
```
And load it with SMAPI on windows.

**Comment by Pathoschild** [comment]
Fixed in `develop` for the upcoming SMAPI 2.6-beta.14. Thanks for reporting it!
