### ISSUE TITLE
Mods not working

### ISSUE THREAD

**Issue by Avinimuss** [Pathoschild/SMAPI#516]
i had a few mods installed that don't work and on the compatibility pagg it's shown that the mods should work   (Ui Info Suite, EXP Bars, automate, lookup anything)

pls help i love these mods

**Comment by reveriadive** [comment]
Wait. Stuff takes time, though this patch should be simple enough. The author may be sleeping at the moment, or busy with life.

**Comment by Pathoschild** [comment]
Stardew Valley 1.3.11 broke SMAPI. I'll deploy an update soon (you can watch #521 for updates), and many mods will need a separate update.
