### ISSUE TITLE
Multiplayer: when host closes game, farmhand game becomes unresponsive.

### ISSUE THREAD

**Issue by hawkfalcon** [Pathoschild/SMAPI#525]
This is consistently reproducible. When the host closes the game (only by hitting x), the other connected games crash and require force quitting. I think this might be due to attempting to save? 
`[16:06:38 TRACE game] setGameMode( 'titleScreenGameMode (0)' )
[16:06:38 TRACE game] CleanupReturningToTitle()
[16:06:38 DEBUG Cooking Skill] beforeSave
`
Minimal output before crash ^

**Comment by Pathoschild** [comment]
@hawkfalcon I can't reproduce this. Does it happen if you temporarily remove all mods?

**Comment by danvolchek** [comment]
I've confirmed this to be caused by Skip Intro - without any mods the other player's game returns to the title menu fine, and with Skip Intro as the only mod they crash.
