### ISSUE TITLE
EventArgsInput.SuppressButton does not suppress mouse clicks when at the TitleMenu

### ISSUE THREAD

**Issue by danvolchek** [Pathoschild/SMAPI#527]
When the game is showing the title menu, mouse clicks are not suppressed by `EventArgsInput.SuppressButton()`.

Here's a sample mod that exhibits this behavior:
[ButtonSupressor.zip](https://github.com/Pathoschild/SMAPI/files/2021297/ButtonSupressor.zip)

The source code is:
```cs
public class ModEntry : Mod
{
    public override void Entry(IModHelper helper)
    {
        InputEvents.ButtonPressed += this.InputEvents_ButtonPressed;
    }

    private void InputEvents_ButtonPressed(object sender, EventArgsInput e)
    {
        e.SuppressButton();
    }
}
```
The expected result is that you cannot click the on screen buttons to load/start a new game/etc, but you can. This is running SDV 1.3.11 and SMAPI 2.6-beta.14.

**Comment by Pathoschild** [comment]
Fixed in `develop` for the next SMAPI 2.6 beta.
