### ISSUE TITLE
Failing loading assets when game language is not English

### ISSUE THREAD

**Issue by RenanCostaNascimento** [Pathoschild/SMAPI#529]
As shown in this [error](https://drive.google.com/file/d/1zpN2KC3XnvxxAlBi-qx_0fi1-y4PX133/view), Smapi fails to load assets from a few mods. I managed to replicate this error with [Elle](https://www.nexusmods.com/stardewvalley/mods/1993?tab=description) and [Hudson](https://www.nexusmods.com/stardewvalley/mods/2110?tab=description) mods. Everything works as expected when the game language is set to English, but other languages cause the above error to occur.

I saw that a similar issue was corrected [a few days ago](https://github.com/Pathoschild/SMAPI/commit/86a477d310c63edf7e9cc0547ef26e544ade1817#diff-bda8c231fd1c79abc469a3912bcae3dc), maybe it has something to do with that.

Thanks for all your hard work!

**Comment by Pathoschild** [comment]
The content core is getting refactored in #524, which should fix this. (If it doesn't, feel free to reopen this ticket after that's released.)

**Comment by Pathoschild** [comment]
I'll reopen this and double-check that it's fixed for the next release.

**Comment by Pathoschild** [comment]
Fixed via #524.
