### ISSUE TITLE
Invisible Objects

### ISSUE THREAD

**Issue by Setara253** [Pathoschild/SMAPI#530]
One of the main issues I encountered was some things, like garden pot, automatic shearer/milker, and some furniture are invisible. When hovering over the block in my inventory, I can see the item description, but the actual sprite is missing.

**Comment by Pathoschild** [comment]
Hi @Setara253. It sounds like you installed an outdated XNB mod which replaced `Content\Maps\springobjects.xnb` with an older version. You can [reset your content files](https://stardewvalleywiki.com/Modding:Player_Guide/Troubleshooting#Reset_your_content_files) to fix that. I suggest only using SMAPI mods and [Content Patcher packs](https://stardewvalleywiki.com/Modding:SMAPI_compatibility#XNB_mods) to avoid issues like that.

(The GitHub issues here are only used for SMAPI development tasks. If you still need help, feel free to [ask on Discord](https://stardewvalleywiki.com/Modding:Community#Discord) or post in the [SMAPI support thread](https://community.playstarbound.com/threads/108375).)
