### ISSUE TITLE
Crash when placing lightning rods

### ISSUE THREAD

**Issue by chvolkmann** [Pathoschild/SMAPI#531]
It looks like lightning rods cause the game to crash when they are ready to be picked up.

I was playing on a multiplayer session with Stardew Valley v1.3.12 and SMAPI-2.6-beta.14 on a Windows 10 machine, with me being the host.
During the first days of summer, it was raining and I set up a lightning rod. As soon as it became charged, I went to bed -- then the game crashed without any further notice. Here's a crash report: https://pastebin.com/RYiqecWH
Note that the folders `C:\Users\gitlab-runner\` and `C:\source\` referenced in the log don't actually exist.

Removing SMAPI for that day fixed the issue. I sadly can't reproduce the problem anymore as I've already moved on in the save.

I'm also not sure if this is an error in SMAPI or the single mod I have installed ([UI Info Suite](https://www.nexusmods.com/stardewvalley/mods/1150/) v1.7.5, obsolete by now).

**Comment by Pathoschild** [comment]
Hi @Freemanium. The error happened in the game code, so my initial impression is that it's a vanilla bug. Unfortunately I can't look into it further if you can't reproduce it. :)
