### ISSUE TITLE
Create mod handler toolkit

### ISSUE THREAD

**Issue by Pathoschild** [Pathoschild/SMAPI#532]
Create a C# library to encapsulate reusable mod-handling logic, which is currently buried in SMAPI and my custom scripts. This will be useful for mod managers and custom tools, and help simplify SMAPI's core logic.

For example:
* scanning a folder for mods;
* parsing manifests;
* performing update checks;
* resolving dependencies;
* reading the internal mod DB;
* parsing the wiki compatibility list;
* etc.

**Comment by Sakorona** [comment]
As an aside, this breaks mods that used to poll the IManifest to verify versions, which is useful for making sure a minimum version of the API is installed. While, sure, we can just reference the external DLL, there might be something to be said for making the internal API calls return a struct containing the version of the mod as well?

**Comment by Pathoschild** [comment]
@JohnsonNicholas There's no need to reference any DLLs yourself, updating to the latest mod build config package should add it automatically. If that doesn't work, try restarting Visual Studio (so it picks up the reference change) or reinstalling the package (to fix a broken package install).

**Comment by Pathoschild** [comment]
This is essentially done. The `SMAPI.Toolkit.dll` encapsulates many of the generic mod operations and is already used in some external scripts.
