### ISSUE TITLE
Crash randomly with SMAPI

### ISSUE THREAD

**Issue by taigacon** [Pathoschild/SMAPI#533]
Using the latest game version on Steam and the latest SMAPI version.
It crashes per half an hour perhaps, and it seems not to crash when running game without SMAPI.

[03:43:47 ERROR SMAPI] The game failed unexpectedly: System.AccessViolationException: 尝试读取或写入受保护的内存。这通常指示其他内存已损坏。
   在 Microsoft.Xna.Framework.Audio.UnsafeNativeMethods.Engine.SetVolume(UInt32 hEngine, UInt16 category, Single volume)
   在 Microsoft.Xna.Framework.Audio.AudioCategory.SetVolume(Single volume)
   在 StardewValley.Game1.updateMusic() 位置 C:\Users\gitlab-runner\gitlab-runner\builds\5c0f9387\0\chucklefish\stardewvalley\Farmer\Farmer\Game1.cs:行号 4468
   在 StardewValley.Game1.Update(GameTime gameTime) 位置 C:\Users\gitlab-runner\gitlab-runner\builds\5c0f9387\0\chucklefish\stardewvalley\Farmer\Farmer\Game1.cs:行号 2015
   在 StardewModdingAPI.Framework.SGame.Update(GameTime gameTime) 位置 C:\source\_Stardew\SMAPI\src\SMAPI\Framework\SGame.cs:行号 635
   在 Microsoft.Xna.Framework.Game.Tick()
   在 Microsoft.Xna.Framework.Game.HostIdle(Object sender, EventArgs e)
   在 Microsoft.Xna.Framework.GameHost.OnIdle()
   在 Microsoft.Xna.Framework.WindowsGameHost.RunOneFrame()
   在 Microsoft.Xna.Framework.WindowsGameHost.ApplicationIdle(Object sender, EventArgs e)
   在 System.Windows.Forms.Application.ThreadContext.System.Windows.Forms.UnsafeNativeMethods.IMsoComponent.FDoIdle(Int32 grfidlef)
   在 System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   在 System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   在 System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   在 System.Windows.Forms.Application.Run(Form mainForm)
   在 Microsoft.Xna.Framework.WindowsGameHost.Run()
   在 Microsoft.Xna.Framework.Game.RunGame(Boolean useBlockingRun)
   在 Microsoft.Xna.Framework.Game.Run()
   在 StardewModdingAPI.Program.RunInteractively() 位置 C:\source\_Stardew\SMAPI\src\SMAPI\Program.cs:行号 285

**Comment by Pathoschild** [comment]
Hi @taigacon. Seems I missed this ticket somehow, sorry for the slow response!

That error indicates a problem with your computer, like faulty audio drivers or memory issues. This is failing in code that SMAPI doesn't change in any way. I suggest running some tests (e.g. memtest) to see if there's an underlying issue.

If you still need help, feel free to [ask on Discord](https://stardewvalleywiki.com/Modding:Community#Discord) or post in the [SMAPI support thread](https://community.playstarbound.com/threads/108375). The GitHub issues are only used for SMAPI development tasks. :)
