### ISSUE TITLE
SaveEvents.AfterReturnToTitle is not triggered on a disconnection from Multiplayer

### ISSUE THREAD

**Issue by Dawilly** [Pathoschild/SMAPI#545]
Any functions stored under SaveEvents.AfterReturnToTitle will not be called, as the event itself is never triggered when a farmhand disconnects from the host, which in turn sends them back to the Title Screen. This can cause issues for mods that depend on knowing if the user has returned to the title screen in order to properly (re)set values.

**Comment by Pathoschild** [comment]
Fixed in `develop` for the upcoming SMAPI 2.6 beta 19.
