### ISSUE TITLE
Mods that overwrite files in /Content with Vortex

### ISSUE THREAD

**Issue by xenopuff** [Pathoschild/SMAPI#548]
Hi hi! might be a stupid question, but when installing Stardew Mods with Vortex, it's not updating/replacing anything that needs to be put in /Content instead of /Mods (eg like farmer_base.xnb etc.). Am I missing something obvious, or is it not able to make these changes?

**Comment by Pathoschild** [comment]
@xenopuff That's normal, Vortex doesn't support XNB mods. They're much harder to install correctly, and they're [deprecated in general](https://stardewvalleywiki.com/Modding:Using_XNB_mods). Vortex will work fine with Content Patcher packs though, which are main alternative to XNB mods.
