### ISSUE TITLE
DLLs are being written in memory for ISemanticVersion & IManifest

### ISSUE THREAD

**Issue by Juice805** [Pathoschild/SMAPI#556]
This is causing breakpoints not to be triggered.

https://log.smapi.io/1GzZBZWV

**Comment by Juice805** [comment]
<img width="1440" alt="screen shot 2018-06-30 at 10 33 08 am" src="https://user-images.githubusercontent.com/8647159/42127622-0055bba0-7c51-11e8-8e40-01ded584cf41.png">
Unsure if they are related but Unit Tests also fail

**Comment by Pathoschild** [comment]
The original issue is fixed in `develop` for the upcoming SMAPI 2.6 beta 19. The screenshot seems unrelated, but let me know on Discord if it still happens with today's NuGet package update.
