### ISSUE TITLE
Frozen Quest Marnie’s Request (Cave Carrot)

### ISSUE THREAD

**Issue by Toys0125** [Pathoschild/SMAPI#566]
**Describe the bug**
Walking into the house and when she goes to talk give this constant error, similar to what happened before but differently. Giving out the Incorrect string format. This is on a multiplayer map, idk if that affects it.

**To Reproduce**
Exact steps which reproduce the bug, if possible. For example:
Just walking in with the cave Carrot

**Log file**
Upload your SMAPI log to https://log.smapi.io and post a link here.
https://log.smapi.io/ie6PjS67
**Screenshots**
https://i.imgur.com/Rs9AP8o.jpg

**Comment by Pathoschild** [comment]
@Toys0125 Does it still happen after [resetting your game files](https://stardewvalleywiki.com/Modding:Player_Guide/Troubleshooting#Reset_your_content_files)? If so, what if you temporarily remove all mods (but still run it through SMAPI)?

**Comment by Toys0125** [comment]
So after testing using the steam version, it seems to be a issue with the content data not the modding api, i have to fix my install manually, since not using steam to run it.

**Comment by Pathoschild** [comment]
Thanks for the update!
