### ISSUE TITLE
"The Game failed unexpectedly"

### ISSUE THREAD

**Issue by Lioncandies** [Pathoschild/SMAPI#567]
I've tried googling fixes to this bug and didn't find anything of use.

I go onto my files, into the stardew valley folder, then click StardewModdingAPI. There isn't an '.exe' after it though. When I click on it I'm brought to a black screen with all writing which you can see in the screenshot below. It doesn't crash, the error stays there until I press any button. I have no idea what any of the writing means, let alone how to solve it. I'm not sure if this is a common bug or not.

![smapi bug 2](https://user-images.githubusercontent.com/41532039/43042736-636e67c0-8db6-11e8-9743-21df108583ce.JPG)

I did see on a video where someone displayed the bug, in the comment sections a user suggested this:

"I had the same problem.
The solution that will work for me: 1) Start "Stardew Valley.exe" then turn it off. 2) Start "StardewModdingAPI.exe".

The game will work again.
I hope it will help you, good luck﻿"

So I followed their solution, went onto the windows start tab, and searched "Stardew valley.exe" I waited a bit, nothing loaded, So then I searched "StardewModdingAPI.exe" there was quite a few different options. The first and biggest at the top which was labeled "StardewModdingAPI.exe" with no other information. Below it was 4 others with all the same label but with "- In windows" on the first 2 and "- In Mono" after the last 2.

Clicking on the first "In windows" resulted in this message:
"Oops! SMAPI can't find the game. It looks like your running SMAPI from the download package, but you need to run the installed version instead. See the read.me txt file for more details."

![smapi error 3](https://user-images.githubusercontent.com/41532039/43042734-51232a38-8db6-11e8-944e-d9cc26d13229.JPG)

Clicking on the second "In windows" Came with another weird bug I was considering writing about as well.
It shows a message in all grey text, with lots of code, it only stays for 5 seconds then crashes, therefor I do not know much information about this bug. Here is an image of it:
![smapi bug](https://user-images.githubusercontent.com/41532039/43042597-24592f30-8db5-11e8-9b22-865add0a4576.JPG)

Clicking on the Mono stardewModdingAPI.exe tabs displays the exact same messages.

I also happened to run into the problem of stardewmoddingAPI saying that I'm on Stardew version 

1.2.33, even though I'm on 1.3 beta, I can even see it on steam, as in my library stardew valley has a [beta] tag after it.

I've been trying to bypass this bug for 3 days now, I can't find any information about it, and I'm rather upset about it. I'll also note I am fairly new to modding and don't know many specific terms. Thank you for reading, hope to find a solution soon.

~ From a Stardew valley lover

**Comment by Pathoschild** [comment]
Hi there!

Sorry for the slow response; the GitHub issues are only for development tasks, so we don't check here often. If you come ask in [#modding on the Stardew Valley Discord](https://stardewvalleywiki.com/Modding:Community) (feel free to link to this page for context), we'll help you get it working. :)
