### ISSUE TITLE
RE: SMAPI Update not working in terminal install

### ISSUE THREAD

**Issue by LustyFarmer** [Pathoschild/SMAPI#572]
So I downloaded the SMAPI 2.6 installer zip *not the developers one as I m not a developer* and followed instructions that I've used with every SMAPI update by opening my Terminal, typing 'mono', putting a space then dragging the Install on linux.sh into the terminal and hitting enter, did not work.

Tried to do the same with the install on Mac.command, did not work. got this same message in my terminal with both those attempts at updating SMAPI the regular way-

Cannot open assembly '/Users/*myname*/Desktop/SMAPI 2.6 installer/install on Linux.sh': File does not contain a valid CIL image.

note to keep my privacy i replaced my actual name that was there with *myname* it obviously did not show it as *myname* in the terminal

This is the SMAPI crash log in case that was needed as well- https://log.smapi.io/48qr5XiQ

**Comment by Pathoschild** [comment]
You don't need to install through the terminal like that anymore, just run `install on Mac.command` instead  (double-click the file and choose 'run' or 'execute'). See the [install guide](https://stardewvalleywiki.com/Modding:Player_Guide/Getting_Started#Install_SMAPI) for more info.
