### ISSUE TITLE
new 2.7 SMAPI have a trojaner SONAR.Heuristic.170

### ISSUE THREAD

**Issue by Dolbai** [Pathoschild/SMAPI#581]
its like the name said my antivir shows me the Sonar heuristic trojaner in the 2.7 update

**Comment by Pathoschild** [comment]
Hi @Dolbai. The name is scary, but the _heuristic_ in the name means the antivirus didn't find an actual trojan but is still suspicious. See [_SMAPI files disappear or your antivirus complains_](https://stardewvalleywiki.com/Modding:Player_Guide/Troubleshooting#SMAPI_files_disappear_or_your_antivirus_complains) in the troubleshooting guide for more info.
