### ISSUE TITLE
Update for Stardew Valley 1.3.29

### ISSUE THREAD

**Issue by Pathoschild** [Pathoschild/SMAPI#585]
Stardew Valley 1.3.29 (currently in beta) has major changes which affects SMAPI. Add support in SMAPI 2.8.

## To do
* [x] Update `SGame.Draw`.
* [x] Update watchers for `NetCollection` changes.
* [x] Filter new `Console.WriteLine` debug output.
* [x] Make beta blurb on smapi.io configurable.
* [x] Release SMAPI 2.8 beta.

**Comment by Pathoschild** [comment]
Done in `develop` for the upcoming SMAPI 2.8.

**Comment by boocatbutterbee** [comment]
Sorry to trouble you, but I have a problem I can't find a solution for.  I have managed to update my SMAPI to 2.8 beta.4, but the little window that came up says I must update my game to 1.3.29 - except I can't find the link to go do that! (I am 64 years old and it's starting to drive me crazy.) I thought that Stardew Valley updated automatically in Steam. I'm still stuck with 1.3.28 and the game won't run. Any advice you might lend me would be greatly appreciated. Thank you for your time.

Sincerely yours,

Catherine Conrad
[email snipped]

**Comment by Pathoschild** [comment]
@boocatbutterbee Installing SMAPI 2.7 should fix that. (SMAPI 2.8-beta is only for the opt-in Stardew Valley 1.3.29-beta.)

**Comment by boocatbutterbee** [comment]
Well, I forgot to mention that I am in the beta opt-in.  (Sorry.)

I had originally tried to update to the SMAPI 2.7, but it never seemed to
take, never seemed to be anywhere. Then I thought it was something about
the beta set-up.

Thanks for your help. Sorry to trouble you, Mr. Plamondon-Willard.


Sincerely,

Catherine Conrad

**Comment by Pathoschild** [comment]
@boocatbutterbee All players were kicked out of the beta branch when it went live, so you have Stardew Valley 1.3.28 by default even if you previously opted in. You'd need to opt in again to get the new beta, but there's no need unless you want to help test it.

If SMAPI 2.7 isn't working for you, come ask in [#modding on the Stardew Valley Discord](https://stardewvalleywiki.com/Modding:Community#Discord) and we'll help you get it working. :)

**Comment by spaghettisos** [comment]
Ugh can I please have help??? I first downloaded SMAPI version 2.7 and inserted my mod files into my Stardew Valley game file, but then I got an error when I tried to load the game saying that I needed SMAPI version 2.8beta-4 to run these mods. So then I installed the other version, but when I tried to run my game again it said that I needed Stardew Valley version 1.3.29 which is unavailable to me because Steam says that no updates are available. I'm so confused???

**Comment by Pathoschild** [comment]
@spaghettisos There are two versions of the game: Stardew Valley 1.3.28 (which you have), and Stardew Valley 1.3.29 (opt-in beta). You need to install SMAPI 2.7, _and_ install the version of each mod for Stardew Valley 1.3.28.

**Comment by Pathoschild** [comment]
**GitHub tickets are for development tasks only.** If you need help using mods, come [ask on Discord](https://stardewvalleywiki.com/Modding:Community#Discord) or post in the [SMAPI support thread](https://community.playstarbound.com/threads/108375). :)
