### ISSUE TITLE
Clarify how to change color scheme during manual install

### ISSUE THREAD

**Issue by mys721tx** [Pathoschild/SMAPI#587]
**Describe the bug**
On mac OS 10.14, SMAPI 2.7 console output color is fixed to black instead of the foreground color. This makes the output hard to read on terminal with dark background. 

**To Reproduce**
1. Set Terminal.app profile to Basic, Homebrew, or Pro.
2. Launch SMAPI via the shell script `StardewModdingAPI`.

**Log file**
[Log file](https://log.smapi.io/UAT4P2Hf)

**Screenshots**
<img width="682" alt="image" src="https://user-images.githubusercontent.com/561975/44621965-bd977c00-a87d-11e8-9d73-5e6d48a4eb89.png">

**Comment by Pathoschild** [comment]
@mys721tx When you run the installer on Linux or Mac, you should be given a choice of color schemes:
> ![color theme selector](https://user-images.githubusercontent.com/230581/44623082-eaef2480-a893-11e8-9bfc-1e6ac0dba0f4.png)

Does that not appear for you?

**Comment by mys721tx** [comment]
Sorry I did not notice that. I was manually installing SMAPI the entire time since I don't have Mono installed. Is it possible to add this option in the documentation?

**Comment by Pathoschild** [comment]
Sure, added in fb3b7aefa79ed9edeee85cf64004e928d203de81.

**Comment by mys721tx** [comment]
Thanks! fixed in fb3b7ae.
