### ISSUE TITLE
umm what?

### ISSUE THREAD

**Issue by calamittyjane** [Pathoschild/SMAPI#589]
![what](https://user-images.githubusercontent.com/42811982/44799246-7103b780-ab81-11e8-9ba6-9c84414d626a.png)

I updated with the new file, but when i try and play  this is what i get.. im confused

Upload your SMAPI log to https://log.smapi.io and post a link here.

**Screenshots**

**Comment by Pathoschild** [comment]
I assume you figured it out, but installing SMAPI 2.7 should fix that. SMAPI 2.8 beta is only for the Stardew Valley 1.3.29 beta. :)
