### ISSUE TITLE
Cant run StardewModdingAPI.bin.x86_64

### ISSUE THREAD

**Issue by ghost** [Pathoschild/SMAPI#599]
When I run SMAPI it opens a terminal, which closes again.

**Describe the bug**
A clear and concise description of what the bug is. Provide any other details you think might be relevant here.

**To Reproduce**
Exact steps which reproduce the bug, if possible. For example:
1. Follow the manual installation steps from the README.txt
2. enter the game folder with the terminal
3. execute the StardewValleyModdingAPI script and in my case it shortly opened a new terminal which executed the file and it closed again

**Comment by Pathoschild** [comment]
Hi there! GitHub issues are only used for development tasks. For user support, you can ask in one of these places:

* [#modding on the Stardew Valley Discord](https://stardewvalleywiki.com/Modding:Community#Discord);
* [support forum thread](https://community.playstarbound.com/threads/smapi-stardew-modding-api.108375/);
* [Nexus page](https://www.nexusmods.com/stardewvalley/mods/2400).

There are a lot more users who can help there. :)
