### ISSUE TITLE
Skill Prestige Mod have an unofficial update that works right now

### ISSUE THREAD

**Issue by AilinaDiasqua** [Pathoschild/SMAPI#607]
The address is this 

https://community.playstarbound.com/threads/updating-mods-for-stardew-valley-1-3.142524/page-43#post-3318586

I don't know how to update SMAPI mod list so I just post it here

**Comment by Pathoschild** [comment]
@AilinaDiasqua Thanks! That unofficial update broke in the latest version of SpaceCore, unfortunately.

For future reference, here's how to edit the compatibility list:

1. Go to [mods.smapi.io](https://mods.smapi.io/).
2. Click "edit this list" at the top.
3. Click "edit" at the top of the wiki page that opens. (You'll need to create an account first if you don't have one.)
