### ISSUE TITLE
Conditions on maps break warps

### ISSUE THREAD

**Issue by Nanogamer7** [Pathoschild/SMAPI#608]
I'm pretty sure this is a SMAPI bug, if I'm mistaking, pls excuse me

**Describe the bug**
When trying to load a map conditionally the warps provided with map properties wont work ingame

**To Reproduce**
1. Have SMAPI 2.9-alpha
2. Add conditions to a map in content.json
3. Go to corresponding map ingame
4. Try to leave the map again via touch warps
5. Error occurs.

I'm pretty sure this is a SMAPI bug rather than my mod, because:

What I did                                                                                                            |   working/broken
---------------------------------------------------------------------------   |   :------:
Loaded same map file with another content pack (non conditionally)              |   working
Loaded older, know to be working map with new content pack conditionally   |   broken
Loaded map with same cp, but removed conditions                                          |   working
Added conditions to a completly different content pack                                   |   broken

**Log file**
https://log.smapi.io/jFUaKxsr

**Comment by Pathoschild** [comment]
Does this affect all warps, or only the new ones added conditionally? Can you provide a sample content pack and mention which warp is affected?

**Comment by Nanogamer7** [comment]
[This](https://github.com/Pathoschild/SMAPI/files/2658136/Tunnel.System.for.SMAPI.2.9.zip) is the 2.9 version of my tunnel system mod, the bug appeared for me in **all** warp on the **greenhouse** map. In my testing not changed warps didn't wok either as long as the map is loaded conditionally

**Comment by Pathoschild** [comment]
Fixed in `develop` for the upcoming SMAPI 2.9. Thanks for reporting it!
