### ISSUE TITLE
Add combat events

### ISSUE THREAD

**Issue by Pathoschild** [Pathoschild/SMAPI#612]
Consider adding events raised when the player receives damage from an NPC, or hits/kills an NPC.

Split from #310.

**Comment by Krutonium** [comment]
Any chance this could be done?

**Comment by Pathoschild** [comment]
Hi! This one is a low priority since you can usually use [change monitoring](https://stardewvalleywiki.com/Modding:Modder_Guide/APIs/Events#Change_monitoring) or events like [`NpcListChanged`](https://stardewvalleywiki.com/Modding:Modder_Guide/APIs/Events#World.NpcListChanged) instead, and combat events may impact performance depending on how they're implemented. I wouldn't be opposed if someone wanted to submit a pull request with combat events that don't unduly impact performance though.

**Comment by Pathoschild** [comment]
Future SMAPI updates may have new combat events, but I don't have any plans to implement this ticket specifically. I'll close this ticket since GitHub issues aren't really the place to track long-term suggestions/ideas.
