### ISSUE TITLE
Custom map tilesheets not loaded correctly in some cases with SDV 1.3.35

### ISSUE THREAD

**Issue by Dawilly** [Pathoschild/SMAPI#616]
**Bug Description**
With Tilesheets being reworked in the lastest beta build (1.3.35), SMAPI is no longer able to distinguish tilesheets that have previously been loaded in memory, canon or custom via Content Patcher, for custom maps.

**To Reproduce**
Load MTN2 with any MTN2 content pack map. Creating a new map or loading a previous save map involving a custom farm triggers the bug (SMAPI's lack of awareness(?) that said tilesheets have been loaded or can be loaded ala Content folder, or Content Patcher).

**Log file**
https://log.smapi.io/HaQrryy0

**Screenshots**
![smapierror](https://user-images.githubusercontent.com/26033748/51725543-6530fa00-2028-11e9-9c87-9225bd71c308.png)

**Comment by Pathoschild** [comment]
This might be specific to MTN2. I tried White Water Farm, a Content Patcher pack which replaces the farm map using both vanilla and custom tilesheets, and it worked fine:
> ![farm waterfall](https://user-images.githubusercontent.com/230581/51763754-46227e80-20a1-11e9-8bb9-7eb81782572d.png)

I'll ping you on Discord to discuss further.
