### ISSUE TITLE
Asset propagation for NPCDispositions doesn't affect starting location

### ISSUE THREAD

**Issue by Pathoschild** [Pathoschild/SMAPI#620]
When propagating changes to `Data\NPCDispositions` asset, the new home location doesn't affect existing NPCs.

**Comment by MissCoriel** [comment]
[[CP] Sample.zip](https://github.com/Pathoschild/SMAPI/files/2896472/CP.Sample.zip)
Talk to Haley, go to sleep.  The next day she will change to her new Disposition as she will now be called HaleyX her starting location should be BusStop 22 5.

**Comment by Pathoschild** [comment]
Also reported by Trent#4455 on Discord (see [another sample content pack](https://github.com/Pathoschild/SMAPI/files/3564686/CP.Marnie.Spawn.zip)).

**Comment by Pathoschild** [comment]
Possibly related to or caused by #620.

**Comment by Pathoschild** [comment]
Possibly related to or caused by #653.

**Comment by Pathoschild** [comment]
Done via [requested changes to Stardew Valley 1.4](https://stardewvalleywiki.com/User:Pathoschild/Modding_wishlist#Done_in_Stardew_Valley_1.4) and changes in SMAPI 3.0. The NPC's default location will change immediately, and they'll warp to that location on the next day update.
