### ISSUE TITLE
Cannot find libgdiplus when brew is used to install mono on Mac

### ISSUE THREAD

**Issue by h4xnoodle** [Pathoschild/SMAPI#621]
I'm a new user to SMAPI, and attempting to install and use my first content patch mods.

I already had mono installed via brew, and so I was hoping it would work without needing to install the package. Unfortunately, after attempting all the efforts in https://github.com/Pathoschild/SMAPI/issues/414 and elsewhere, it seems like mono with brew doesn't really cut it.

**Describe the bug**
Installing SMAPI & attempting to use a mod results in assembly/libs not found if `mono` is installed with `brew` on Mojave. Installing the framework package from openmono.com and reinstalling SMAPI resolves all issues.

**To Reproduce**
Exact steps which reproduce the bug, if possible. For example:
1. `brew install mono`
1. `sh "install on Mac.command"`
1. `unzip/mv <mods>` that use `libgdiplus`
1. Launch game
```
Mod crashed on entry and might not work correctly. Technical details: StardewModdingAPI.Framework.Exceptions.SContentLoadException: Failed loading content asset 'Buildings/house.png': couldn't find libgdiplus, which is needed to load mod images. Make sure Mono is installed and you're running the game through the normal launcher.
--
...
```
I attempted removing files and symlinking myself as per https://github.com/Pathoschild/SMAPI/issues/414 and more random forum posts. The only thing that worked for me was installing the package instead of from brew.

**Workaround**
1. `brew uninstall mono`
1. Download mono framework install pkg from site linked in here https://stardewvalleywiki.com/Modding:Player_Guide/Getting_Started
1. Reload terminal session, `sh "install on Mac.command"` and install SMAPI again
1. Launch game from Steam

Mods work fine.

**Log file**
N/A

I see the other issues are closed about this: https://github.com/Pathoschild/SMAPI/issues/344, https://github.com/Pathoschild/SMAPI/issues/277, https://github.com/Pathoschild/SMAPI/issues/414 so I'm mostly drawing attention to the work around for anyone who gets just as stuck and don't want to go down the rabbit hole others did when there is a simple work-around.

**Comment by Pathoschild** [comment]
Thanks! I'll close this since no SMAPI changes are needed, but it'll appear in search results if others have the same issue.

**Comment by h4xnoodle** [comment]
Thanks @Pathoschild

**Comment by YesAlcazar** [comment]
Thank you @h4xnoodle, this workaround saved me today. Only issue was to find the Mono framework on the wiki page, so I downloaded directly from [https://www.mono-project.com/download/stable/](url)
