### ISSUE TITLE
Linux xubuntu trusty install error

### ISSUE THREAD

**Issue by quartox** [Pathoschild/SMAPI#622]
**Describe the bug**
A clear and concise description of what the bug is. Provide any other details you think might be relevant here.

While running install script for 2.10 and 2.11:

```
$ ./install\ on\ Linux.sh 
Extracting install files...

Unhandled Exception:
System.NotImplementedException: The requested feature is not implemented.
  at StardewModdingApi.Installer.Program.Main (System.String[] args) [0x00000] in <filename unknown>:0 
[ERROR] FATAL UNHANDLED EXCEPTION: System.NotImplementedException: The requested feature is not implemented.
  at StardewModdingApi.Installer.Program.Main (System.String[] args) [0x00000] in <filename unknown>:0 
```

Already installed `mono-complete` and tried restarted.

**Comment by Pathoschild** [comment]
It's failing in `Main` after the `Extracting install files...` log, so one of these lines is failing:
```c#
ZipFile.ExtractToDirectory(zipFile.FullName, bundleDir.FullName);

// set up assembly resolution
AppDomain.CurrentDomain.AssemblyResolve += Program.CurrentDomain_AssemblyResolve;

// launch installer
var installer = new InteractiveInstaller(bundleDir.FullName);
installer.Run(args);
```

Can you enter `mono --version` in the terminal and post the output here?

**Comment by quartox** [comment]
```
$ mono --version
Mono JIT compiler version 3.2.8 (Debian 3.2.8+dfsg-4ubuntu1.1)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       altstack
	Notifications: epoll
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	LLVM:          supported, not enabled.
	GC:            sgen
```

**Comment by Pathoschild** [comment]
Try updating to a newer version of Mono. You have a version from 2014, and it seems to be missing some core Mono features that SMAPI uses.

**Comment by quartox** [comment]
Thanks for the help. For future reference for anyone else seeing this, it was an issue with updating the mono package index. It claimed the latest version was installed because the package index hadn't been updated.
