### ISSUE TITLE
Newest version of the game won't load SMAPI

### ISSUE THREAD

**Issue by N3rdGirl64** [Pathoschild/SMAPI#623]
**Describe the bug**
With the newest version of Stardew valley, SMAPI doesn't work and the game will not load

**Screenshots**
![screen shot 2019-03-01 at 11 17 36 am](https://user-images.githubusercontent.com/24899388/53660832-b0d05800-3c13-11e9-8ffc-6ab644223011.png)

**Comment by Pathoschild** [comment]
You can install [SMAPI 2.11](https://smapi.io/) to fix that. (Just run the new installer, and it'll update automatically.)
