### ISSUE TITLE
No longer able to join multiplayer server.

### ISSUE THREAD

**Issue by vinylphilharmonica** [Pathoschild/SMAPI#624]
My friend was hosting this multiplayer server just for us two, and we played for 3.5 seasons or so. Then, when he invited me, I joined, and while I was joining the server, he thought I wasn't in yet, so he disconnected the server while I was joining. After that, I couldn't join anymore with the same or different farmer.
It just gets stuck in the loading screen. "Loading..."

https://log.smapi.io/1wbXC7x6

I don't understand what the error is telling me and how to fix it.

**Comment by Pathoschild** [comment]
@vinylphilharmonica 
* Does it work if all players exit the game entirely, then relaunch and reconnect?
* What if all players temporarily remove their mods (so only SMAPI itself is running)?

If it still happens after doing those, please post both your and the host's SMAPI logs.

**Comment by vinylphilharmonica** [comment]
We temporarily removed all our mods and put in each mod and found that the mod called Entoarox Framework was not enabling him to invite me. He said that once he started up with the mod, he tried to invite me and it was stuck on "Connecting..." for him. We put all of the mods back in and I could get back in, so we know it's Entoarox Framework. The thing is that he got this mod because it's a requirement for Extended Minecart mod and the XNB Loader mod. I could get in while he was running the XNB Loader by itself, so we know that mod isn't the problem.
I'm not sure if you can see what the problem was based on the error log, but maybe you can tell other people the reason if they have the same problem.

Just in case:
Entoarox Framework: https://www.nexusmods.com/stardewvalley/mods/2269
Extended Minecart: https://www.nexusmods.com/stardewvalley/mods/2271
XNB Loader: https://www.nexusmods.com/stardewvalley/mods/2275

So currently as of now, I no longer have the issue.

**Comment by Pathoschild** [comment]
I suggest reporting that in the [Entoarox Framework support thread](https://community.playstarbound.com/threads/smapi-entoarox-framework.125025/) so the author can look into it.

(Note that XNB Loader is deprecated, so the author might not update it for upcoming game versions. I suggest [replacing your XNB mods with Content Patcher packs](https://stardewvalleywiki.com/Modding:Using_XNB_mods#Alternatives_using_Content_Patcher) before that happens.)
