### ISSUE TITLE
suggestion/bug 

### ISSUE THREAD

**Issue by Nielsplays** [Pathoschild/SMAPI#625]
Found something that isnt particulary a bug but could be changed.

The console advices an update for a version of a mod that only works in the beta version of smapi however I do not have the smapi beta installed. Please fix to [optional update] if smapi detects that the beta is not installed.
![stardew smapi bug or feature](https://user-images.githubusercontent.com/48332239/53983157-e3e48100-4116-11e9-96ef-15d87e1d4e69.png)

Thanks in advance,

**Comment by Pathoschild** [comment]
That mod's file description is outdated. Stardew Valley 1.3.36 and SMAPI 2.11 are no longer beta, so it should work fine for you.
