### ISSUE TITLE
SMAPI For Android

### ISSUE THREAD

**Issue by ghost** [Pathoschild/SMAPI#628]
I know this impossible. but can you make SMAPI for Android?

Because Stardew Valley android has been released

**Comment by Pathoschild** [comment]
SMAPI won't work on Android/iOS/consoles for the foreseeable future, unless someone familiar with those platforms wants to work on porting SMAPI. (Get in touch with me if so!)

**Comment by Pathoschild** [comment]
See #632 for more info.
