### ISSUE TITLE
when i use the smapi，i can't play with other people using the lan

### ISSUE THREAD

**Issue by il1707** [Pathoschild/SMAPI#645]
i play the game with steam.

when i use the smapi，i can't play with other people using the lan while can play a single game or play with others through steam internet.

in a same environment,without the smapi,run the orginal game,everything works well.

**Comment by Pathoschild** [comment]
@il1707 SMAPI doesn't change how the game connects over the network. If connecting via LAN only works without it, you may have a firewall blocking SMAPI. Try adding an exception to any security suite or firewall you have installed.

If that doesn't fix it, see [_Ask for help_ in the troubleshooting guide](https://stardewvalleywiki.com/Modding:Player_Guide/Troubleshooting#Ask_for_help) for the best places to ask. (GitHub issues are only used for tracking development tasks, so most modders who could help won't see questions here.)
