### ISSUE TITLE
Co-op Console Error

### ISSUE THREAD

**Issue by M-AlNoaimi** [Pathoschild/SMAPI#646]
**Description**
Upon accepting an invite to a Co-op game via Steam, or entering an invite code. It tries to connect then later on either fails with "Connection Failed" or gives out a "No More Slots Left" response. Following that is console errors. 
Strangely, I've encountered this error even when the connection is successful, but that was a few days ago and from memory, it seemed *shorter* than this console error code. 

**Reproducing the bug**
1. Load Stardew Valley.
2. Enter an Invite code or accept a Steam Invite to Co-op.
3. Either it fails or succeeds, both of which give out a console error. 
4. That's it.

**Log file**
https://log.smapi.io/tEr17n08

**Comment by Pathoschild** [comment]
The error is from the game itself, SMAPI is just logging it for you.

Does it still happen if you have the same mods installed for all players? If so, what if you temporarily remove all mods (for all players)?

**Comment by M-AlNoaimi** [comment]
Hmm, seems to be from the mods. 

I tried playing without mods on both ends and on one end and it didn't log any errors. 
Playing with mods gave that error again, strange issue.

So to sum up, 

> Does it still happen if you have the same mods installed for all players? If so, what if you temporarily remove all mods (for all players)?

Apparently so, for both.

**Comment by Pathoschild** [comment]
The log doesn't have enough info to know which mods are causing it, so you'll need some trial and error. Try removing Intravenous Coffee, Json Assets, More Rings, PyTK, SpaceCore, Stardew Hack, and Wear More Rings first (for all players); if that fixes it, re-add them one at a time until it breaks again, then report it to the author of the last mod you added.

If that doesn't fix it, see [_Ask for help_ in the troubleshooting guide](https://stardewvalleywiki.com/Modding:Player_Guide/Troubleshooting#Ask_for_help) for the best places to ask. (GitHub issues are only used for tracking development tasks, so most modders who could help won't see questions here.)
