### ISSUE TITLE
Console Item Spawning

### ISSUE THREAD

**Issue by M-AlNoaimi** [Pathoschild/SMAPI#649]
**Description of the bug**
Went on a little break from 13-22 June and when I got back suddenly, `list_items` - `player_add` - `player_setstamina` doesn't work. Well, aren't there anymore. I haven't exactly uninstalled any mods excluding ConsoleCommands which according to https://mods.smapi.io is already built into SMAPI. 

**Steps to reproduce**
Exact steps which reproduce the bug, if possible. For example:
1. Load Save
2. Go into the console and type any of the `player_$` commands and/or `list_items`.
3. Observe the no command found output.
4. That's about it.

**Log file**
https://log.smapi.io/bkw0ZeQG

**Comment by Pathoschild** [comment]
Hi @DiscoverSquishy. Those commands are added by the Console Commands mod, which is added automatically when you install SMAPI. You can reinstall SMAPI to restore the commands, then type `help` to see a list of commands grouped by the mod which added them.
