### ISSUE TITLE
[Linux] Have no one of termanal in the modified "StardewValley".

### ISSUE THREAD

**Issue by MofuMoca** [Pathoschild/SMAPI#656]
I use Archlinux and using cinnamon for DM.
And I use `sakura` that instead of other terminal in  `StardewValley` file.
This lead to SMAPI not work, in terminal I run `./StardewValley` in the game folder only return `command` and process exit.
Then I install `xterm` for test ,it works.
I think maybe you need to write down that some terminal need to be install.
Thanks.

**Comment by Pathoschild** [comment]
If you don't have a preferred terminal installed, SMAPI automatically uses your default terminal instead. It sounds like you didn't have any of the preferred terminals installed, _and_ your default terminal wasn't compatible. I updated the [install guide](https://stardewvalleywiki.com/Modding:Installing_SMAPI_on_Linux) and [troubleshooting guide](https://stardewvalleywiki.com/Modding:Player_Guide/Troubleshooting#Nothing_happens_when_you_launch_the_game) to address that case, thanks for pointing that out!
