### ISSUE TITLE
How to add UI Info Suite

### ISSUE THREAD

**Issue by asadabasmalik** [Pathoschild/SMAPI#660]
**Describe the bug**
A clear and concise description of what the bug is. Provide any other details you think might be relevant here.

**To Reproduce**
Exact steps which reproduce the bug, if possible. For example:
1. Load save '...'.
2. Walk to '....'.
3. Click '....'.
4. Error occurs.

**Log file**
Upload your SMAPI log to https://log.smapi.io and post a link here.

**Screenshots**

**Comment by Pathoschild** [comment]
Hi! See the [player guide](https://stardewvalleywiki.com/Modding:Player_Guide) for help installing mods, or you can ask for help on the [UI Info Suite](https://www.nexusmods.com/stardewvalley/mods/1150) page or [SMAPI discussion thread](https://community.playstarbound.com/threads/smapi-stardew-modding-api.108375).
