### ISSUE TITLE
Improve reflection error handling for TargetParameterCountException

### ISSUE THREAD

**Issue by InkDragon** [Pathoschild/SMAPI#673]
https://smapi.io/log/g0U5Z4Eq

00:13:59 | ERROR | SMAPI | Critical thread exception: System.Reflection.TargetParameterCountException: Parameter count mismatch.    at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)    at StardewModdingAPI.Framework.Reflection.ReflectedMethod.Invoke[TValue](Object[] arguments) in C:\source\_Stardew\SMAPI\src\SMAPI\Framework\Reflection\ReflectedMethod.cs:line 66
-- | -- | -- | --

breaks all in game functions, unable to move or access menus

**Comment by Pathoschild** [comment]
That's a mod bug (per our later Discord discussion), but SMAPI should be handling it better.

**Comment by Pathoschild** [comment]
Improved the error-handling in `develop` for the upcoming SMAPI 3.0.2.
