### ISSUE TITLE
Broken set-the-game-path section link in mod-package.md

### ISSUE THREAD

**Issue by tambry** [Pathoschild/SMAPI#677]
The text "set the game path" in [mod-package.md](https://github.com/Pathoschild/SMAPI/blob/730d9783959cc35945841ab721c930fad8ff9ca0/docs/technical/mod-package.md#detect-game-path) links to the section `set-the-game-path` in the same file, which doesn't exist.

**Comment by Pathoschild** [comment]
Thanks! I fixed that link and made sure the other section links work. (See [the latest version](https://smapi.io/package/detect-game-path).)
