### ISSUE TITLE
Asset propagation for TerrainFeatures/Flooring_winter

### ISSUE THREAD

**Issue by MouseyPounds** [Pathoschild/SMAPI#679]
**Describe the bug**
Content patches of TerrainFeatures/Flooring_winter will not apply if the patch contains the {{Season}} token. Per discussion on Discord, this may be a problem with SMAPI's asset propagation for that file.

**To Reproduce**
Attached is a zip containing a small Content Pack and save game which illustrates this issue. 
1. Install the included mod (CP must be installed as well) and load the included save. The mod contains a config.json and the "Tokens" config should be set to "true".
2. Walk outside the farmhouse. The small area of wood floor just in front of the door is supposed to be a dark red, but will instead be the normal wood color.
3. Running `patch summary` will show that the patch is not applied. (Example log: https://smapi.io/log/4qCtA0Ka )
Now change the config.json for the mod so that "Tokens" is set to "false" and rerun the same test. This time the patch will apply and the wood floor will be properly colored. (Example log: https://smapi.io/log/2B3gcCM9 )

[Flooring_winter asset propagation.zip](https://github.com/Pathoschild/SMAPI/files/3978514/Flooring_winter.asset.propagation.zip)

**Comment by Pathoschild** [comment]
Added in `develop` for the next SMAPI update. Thanks for reporting it!
