### ISSUE TITLE
Game is crashing

### ISSUE THREAD

**Issue by NoehMi** [Pathoschild/SMAPI#680]
https://smapi.io/log/7595256141494a9fbbb05375e01801d6
I wanted to go to my farm but I only got a black screen and after some time it crashed

**Comment by Pathoschild** [comment]
Can you [come ask on Discord](https://smapi.io/community) so we can run some tests?

(I'll close this ticket since GitHub issues are only used for tracking development tasks; most modders who could help won't see questions here.)
