### ISSUE TITLE
Problem with calling an API using an interface as a return value or parameter

### ISSUE THREAD

**Issue by Xebeth** [Pathoschild/SMAPI#687]
**Describe the bug**
While trying to implement the API integration with [ModTabSettings](https://github.com/GilarF/SVM) I ran into a problem with the proxy class generated to bind the API interface to the method in the ModTabSettings mod. The method used in the API uses [an interface](https://github.com/GilarF/SVM/blob/develop/ModSettingsTab/Api.cs) as a return value (**_ISettingsTabApi_**) so it might be partly on @GilarF's side too. I have tried returning the _**ISettingsTabApi**_ object as an **_out_** parameter but that results into a different error: `The ModUsingAPI.IModAPI interface defines method GetThing which doesn't exist in the API.` (probably a separate issue).

**To Reproduce**
I created a [repository](https://github.com/Xebeth/StardewValley-SampleAPI) to illustrate the problem. It contains a mod providing an API and a mod using the API. This results in an exception (see the [full log](https://raw.githubusercontent.com/Xebeth/StardewValley-SampleAPI/master/SMAPI-latest.txt)):
`Failed loading type:
'StardewModdingAPI.Proxies.From<Blackclaw.ModUsingAPI_ModUsingAPI.IModAPI>_To<Blackclaw.ModWithAPI_ModWithAPI.ModAPI>': System.TypeLoadException: Method 'GetThing' in type 'StardewModdingAPI.Proxies.From<Blackclaw.ModUsingAPI_ModUsingAPI.IModAPI>_To<Blackclaw.ModWithAPI_ModWithAPI.ModAPI>' from assembly 'StardewModdingAPI.Proxies, Version=3.0.1.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.`

**Log file**
[Log file](https://raw.githubusercontent.com/Xebeth/StardewValley-SampleAPI/master/SMAPI-latest.txt)

**Comment by Xebeth** [comment]
If the **_IThing_** interface is replaced with a _**bool**_ everything works [as expected](https://stardewvalleywiki.com/Modding:Modder_Guide/APIs/Integrations).

**Comment by Xebeth** [comment]
In my original mod, referencing the **_ModSettingsTab.dll_** assembly doesn't seem to improve anything.

**Comment by Pathoschild** [comment]
That's a known limitation when mapping the API to a custom interface; only the main API interface is proxied by SMAPI. I expanded the [known limitations](https://stardewvalleywiki.com/Modding:Modder_Guide/APIs/Integrations#Known_limitations) in the docs to clarify that. (Pull requests are welcome if someone wants to rework the API proxying!)

The solution in this case is to reference `ModSettingsTab.dll`, remove your custom interface, and use the one provided by the mod directly.

**Comment by Xebeth** [comment]
I tried referencing the ModTabSettings.dll and it didn't help, though. If I understand the issue correctly, @GilarF should expose his [API](https://github.com/GilarF/SVM/blob/develop/ModSettingsTab/Api.cs) through an interface which I would need to use, right?

**Comment by Pathoschild** [comment]
The mod has this example on its mod page:
```cs
ITabApi api = helper.ModRegistry.GetApi<ISettingsTabApi>("GilarF.ModSettingsTab").GetMod("YourModUniqueId");
```
The example seems wrong though; [its API](https://github.com/GilarF/SVM/blob/develop/ModSettingsTab/Api.cs) doesn't implement `ISettingsTabApi`, and [`ISettingsTabApi`](https://github.com/GilarF/SVM/blob/develop/ModSettingsTab/Framework/Interfaces/ISettingsTabApi.cs) doesn't have a `GetMod` method.

I suggest opening an issue in the author's repo to clarify.
