### ISSUE TITLE
Allow persistent overrides to SMAPI config

### ISSUE THREAD

**Issue by kins-dev** [Pathoschild/SMAPI#693]
The default config.json has:
```json
            "DarkBackground": {
                "Trace": "DarkGray",
                "Debug": "DarkGray",
                "Info": "White",
                "Warn": "Yellow",
                "Error": "Red",
                "Alert": "Magenta",
                "Success": "DarkGreen"
            },
```
Which looks like this on Ubuntu 18.04:
![image](https://user-images.githubusercontent.com/48720687/73127369-fb696a00-3f73-11ea-8714-18d64c2a8dd0.png)

It should probably be changed to:
```json
            "DarkBackground": {
                "Trace": "Gray",
                "Debug": "Gray",
                "Info": "White",
                "Warn": "Yellow",
                "Error": "Red",
                "Alert": "Magenta",
                "Success": "Green"
            },
```

Which looks like this:
![image](https://user-images.githubusercontent.com/48720687/73127412-af6af500-3f74-11ea-9e36-c232e20da175.png)

**Comment by Pathoschild** [comment]
It's hard to support all platforms with the default colors. The dark background on Windows is black, instead of the mid-range purple Ubuntu opted for. The proposed color scheme also makes `Trace`/`Debug`/`Info` almost indistinguishable, which defeats one of the main purposes (deemphasizing less important messages).

To make matters worse, we can't just have per-OS color schemes since it also depends on which particular terminal you have and its settings.

**Comment by kins-dev** [comment]
I understand what you're saying. If I change those defaults I expect to mess color settings in SMAPI as well as anything else using the terminal, because I did something special.

So maybe I can come at this a different way.  That config file is replaced each time I install SMAPI right?  Would it be reasonable to have a file in my local user space that would define the colors?  That way the installer would just know and I don't need to mess with the settings every time I upgrade.

**Comment by Pathoschild** [comment]
Thanks for the suggestion! The upcoming SMAPI 3.2 will now let you override settings in a separate `smapi-internal/config.user.json` file.

**Comment by kins-dev** [comment]
Thank you!  This will make my life better!
