### ISSUE TITLE
Nixos libgdiplus.so missing

### ISSUE THREAD

**Issue by rowpsmo1859** [Pathoschild/SMAPI#696]
Hi,

A bit stumped atm on fixing this. There are errors in the console about the missing dll libgdipius.so. I'm running Nixos 19.09

I have the library installed as a separate package (mono complete isn't an option in the repo). Not sure why it's not picking it up.

Thoughts?

EDIT:

[Here's the package ](https://github.com/NixOS/nixpkgs/blob/6d881472ef7c6a592eda36c2783130dc03c678b9/pkgs/development/libraries/libgdiplus/default.nix)

**Comment by sts3johnson** [comment]
Any luck in fixing it? If not can you post the error logs?

**Comment by Pathoschild** [comment]
The SMAPI launcher symlinks libgdiplus into the game folder automatically on MacOS:
```sh
# fix "DllNotFoundException: libgdiplus.dylib" errors when loading images in SMAPI
if [ -f libgdiplus.dylib ]; then
    rm libgdiplus.dylib
fi
if [ -f /Library/Frameworks/Mono.framework/Versions/Current/lib/libgdiplus.dylib ]; then
    ln -s /Library/Frameworks/Mono.framework/Versions/Current/lib/libgdiplus.dylib libgdiplus.dylib
fi
```

That's normally not needed for Linux though. Does it work if you edit the `StardewValley` file in your game folder after installing SMAPI, and add that in the Linux (non-`Darwin`) section with the correct paths?

**Comment by rowpsmo1859** [comment]
> The SMAPI launcher symlinks libgdiplus into the game folder automatically on MacOS:
> 
> ```shell
> # fix "DllNotFoundException: libgdiplus.dylib" errors when loading images in SMAPI
> if [ -f libgdiplus.dylib ]; then
>     rm libgdiplus.dylib
> fi
> if [ -f /Library/Frameworks/Mono.framework/Versions/Current/lib/libgdiplus.dylib ]; then
>     ln -s /Library/Frameworks/Mono.framework/Versions/Current/lib/libgdiplus.dylib libgdiplus.dylib
> fi
> ```
> 
> That's normally not needed for Linux though. Does it work if you edit the `StardewValley` file in your game folder after installing SMAPI, and add that in the Linux (non-`Darwin`) section with the correct paths?

That worked! Thank you :3

I used `nix eval nixos.libgdiplus.outPath` to find the path

These paths are dynamic with each generation of nixos.

EDIT

If the above command doesn't work try
`nix eval nixpkgs.libgdiplus.outPath`

**Comment by Pathoschild** [comment]
This might be too niche to support directly, but hopefully the thread will be useful to any other NixOS players who search for it!
