### ISSUE TITLE
Games crashes every time I go to sleep

### ISSUE THREAD

**Issue by FluffieKiss** [Pathoschild/SMAPI#698]
Games crashes every time I go to sleep. I updated all the mods I use, as suggested in my log but it keeps crashing. Here is the log: https://smapi.io/log/2c1b242f98de48108c37fbd2c8de1679
Thank you for you help!

**Comment by Pathoschild** [comment]
Hi! See [Modding:Help](https://stardewvalleywiki.com/Modding:Help) for the best places to get help. 

GitHub issues here are only used to track development on the core (non-Android) SMAPI, so fewer modders watch for issues here.
