### ISSUE TITLE
SDV Crashing Upon Deleting Command

### ISSUE THREAD

**Issue by M-AlNoaimi** [Pathoschild/SMAPI#700]
**Describe the bug**
Ignoring the clear PyTK issues pre-issue happening; this happened to me twice as of now and only when I delete command that I could have possibly mis-spelt.

**To Reproduce**
Exact steps which reproduce the bug, if possible. For example:
1. Start SDV
2. Type in a command like `player_add sdosjdo`
3. Start backspacing it
4. Observe the automatic killing of SDV

**Log file**
https://smapi.io/log/e81ea54b15f14140b6a4b065b24ea126

**Comment by Pathoschild** [comment]
That seems like an issue with the .NET terminal driver (or the terminal itself). Unfortunately I don't think SMAPI can do anything about it.
