### ISSUE TITLE
Stuck with willy at Ice festival

### ISSUE THREAD

**Issue by KurtySuit** [Pathoschild/SMAPI#704]
Hi, after speaking to willy at the Ice festival i'm stuck and can't do anything
https://i.imgur.com/le2iNzE.png

Error log
https://pastebin.com/mTsrrf7D

**Comment by purrplingcat** [comment]
Hi, It's better to upload log to smapi.io, I uploaded it https://smapi.io/log/d64672c79f784ec4a529b4d5af5dc99b

I think your problem is not a SMAPI problem, it's caused by bad dialogue in another mod or in french dialogue in original game. If you run SMAPI without mods, you still got this error?

**Comment by Pathoschild** [comment]
Hi! See [Modding:Help](https://stardewvalleywiki.com/Modding:Help) for the best places to get help. GitHub issues here are only used to track SMAPI development, so fewer modders watch for issues here.
