### ISSUE TITLE
Input suppression broken in 3.4

### ISSUE THREAD

**Issue by ghost** [Pathoschild/SMAPI#705]
Suppressing mouse buttons seems to be broken in 3.4.0. It worked fine in 3.3.2, but I can't get it to work now.

**Comment by Pathoschild** [comment]
Input handling was rewritten in SMAPI 3.4. Looks like this affects any suppression, not just for the mouse button.

**Comment by ghost** [comment]
Controller suppression seemed to work properly still. I didn't test keyboard.

**Comment by Pathoschild** [comment]
Yep, it affected any mouse input. Fixed in `develop` for the upcoming SMAPI 3.4.1. Thanks for reporting it!
