### ISSUE TITLE
Migrate to Harmony 2.0

### ISSUE THREAD

**Issue by Pathoschild** [Pathoschild/SMAPI#711]
Migrate to Harmony 2.0, which was [released](https://github.com/pardeike/Harmony/releases/tag/v2.0.0) a few months ago and has improvements useful to SMAPI and modders (e.g. finalizers).

## To do
* [x] Document [mod migration process](https://stardewvalleywiki.com/Modding:Migrate_to_Harmony_2.0).
* [x] Migrate SMAPI code to Harmony 2.0.
* [x] Add rewriters so most Harmony 1._x_ mods still work.
* [x] **BLOCKER:** [Error loading Data\Movies if any Harmony 2.0 patch is applied to GameLocation.performAction](https://github.com/Pathoschild/SMAPI/issues/722).
* [x] Test all Harmony mods, [track compatibility](https://stardewvalleywiki.com/Modding:Migrate_to_Harmony_2.0#Mod_compatibility), and improve rewriters as needed.

**Comment by KenMacD** [comment]
It looks like this will be required before there's a chance this will work on aarch64/arm64. The older version of the library [uses x86 bytes directly](https://github.com/pardeike/Harmony/blob/422b16fcd8d86351118aa602fd13b4e171b719e6/Harmony/ILCopying/Memory.cs#L83-L85).

The newest version uses https://github.com/MonoMod/MonoMod.Common, which [at least seems to have aarch64 support](https://github.com/MonoMod/MonoMod.Common/blob/master/RuntimeDetour/Platforms/Native/DetourNativeARMPlatform.cs)

**Comment by Pathoschild** [comment]
It's mainly blocked by #722. I'm not planning any big changes like this with Stardew Valley 1.5 releasing soon, but once the dust settles on that I'll take another look to see if the issue still happens with the latest Harmony version.

**Comment by Pathoschild** [comment]
Done in `develop` for the upcoming SMAPI 3.12.0.
