### ISSUE TITLE
Out of memory exception

### ISSUE THREAD

**Issue by Rmdhn1** [Pathoschild/SMAPI#713]
Out of memory exception
that's it, haven't played the game in a while, updated it, updated all the mods, failed to initialize system blah blah blah

**Log file**
it didn't generate a log lol since the game didn't start

**Screenshots**

**Comment by Pathoschild** [comment]
Can you post a screenshot of the error?

**Comment by Rmdhn1** [comment]
Sorry for late reply but here it is
![Capture](https://user-images.githubusercontent.com/54092365/81666731-9e36ed00-946c-11ea-82a2-a8431f9593e6.PNG)

**Comment by Rmdhn1** [comment]
SMAPI failed to initialize: System.TypeInitializationException: The type initializer for 'StardewModdingAPI.Constants' threw an exception. ---> System.TypeInitializationException: The type initializer for 'StardewValley.Game1' threw an exception. ---> System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at StardewValley.Game1..cctor()
   --- End of inner exception stack trace ---
   at StardewModdingAPI.Constants..cctor() in C:\source\_Stardew\SMAPI\src\SMAPI\Constants.cs:line 98
   --- End of inner exception stack trace ---
   at StardewModdingAPI.Constants.get_GameVersion() in C:\source\_Stardew\SMAPI\src\SMAPI\Constants.cs:line 98
   at StardewModdingAPI.Program.AssertGameVersion() in C:\source\_Stardew\SMAPI\src\SMAPI\Program.cs:line 95
   at StardewModdingAPI.Program.Main(String[] args) in C:\source\_Stardew\SMAPI\src\SMAPI\Program.cs:line 41
Game has ended. Press any key to exit.

**Comment by Pathoschild** [comment]
It's failing very early in the loading process, before any mods are loaded. What happens if you double-click `Stardew Valley.exe` in your game folder directly?

**Comment by Rmdhn1** [comment]
didn't do anything? ok it' probably broken

**Comment by Rmdhn1** [comment]
i validated the files and steam says it completes it, but it still won't start SDV and still the same error

**Comment by Pathoschild** [comment]
Yep, so it's not an issue with SMAPI. Can you come ask in [#game-support on the Stardew Valley Discord](https://smapi.io/community#Discord)?
