### ISSUE TITLE
Entoarox Framework 

### ISSUE THREAD

**Issue by BunnyX53** [Pathoschild/SMAPI#720]
Looking to get this working on android

**Comment by Pathoschild** [comment]
Hi! I suggest asking the author of [Entoarox Framework](https://www.nexusmods.com/stardewvalley/mods/2269) or the [SMAPI Android port](https://github.com/ZaneYork/SMAPI-Android-Installer), or asking in the [#using-mods channel on Discord](https://stardewvalleywiki.com/Modding:Help#Using_mods).
