### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by jjc54** [Pathoschild/SMAPI#726]
**Describe the bug**
Randomly keeps crashing when attempting to play during the first 10 minutes.

**To Reproduce**
Exact steps which reproduce the bug, if possible. For example:
1. Load save
2. Try and play for about 10 minutes

**Log file**
https://smapi.io/log/36e8fae2df6643938c235a5ffc90cb7d

**Screenshots**
N/A

**Comment by Pathoschild** [comment]
Hi! That's probably an issue with one of your mods. GitHub issues here are only used for development tasks; [come ask on Discord](https://stardewvalleywiki.com/Modding:Help) and we'll help you get it working!
