### ISSUE TITLE
Have SMAPI ignore marked tilesheets when loading a map

### ISSUE THREAD

**Issue by Platonymous** [Pathoschild/SMAPI#732]
**Have SMAPI ignore marked tilesheets from a modfolder/contentpack when loading the map**

Allow map modders to keep certain (vanilla) files next to their map content and still have those loaded from game content.
First proposal was to mark them was some kind of tilesheet property like `@IgnoreLocalFile`, another to have the file start with a dot, e.g. `.fall_town.png`.

**Comment by Pathoschild** [comment]
Done in the upcoming SMAPI 3.10 using the [dot-ignore convention](https://stardewvalleywiki.com/Modding:Maps#Local_copy_of_a_vanilla_tilesheet). Thanks for the suggestion!
