### ISSUE TITLE
ARM64/AArch64 Support

### ISSUE THREAD

**Issue by KenMacD** [Pathoschild/SMAPI#738]
SMAPI uses an older, 1.x version of [Harmony](https://www.github.com/pardeike/Harmony). Support for ARM64 was added in version 2. While #711 exists to track that progress it would be nice for the existing code to be usable on systems like Chromebooks.

With that in mind this issue was opened to track changes required to add support:

- [ ] Upgrade Harmony to support ARM64 (Pathoschild/Harmony#1)
- [ ] Import new Harmony build
- [ ] Include the [RuntimeInformation](https://www.nuget.org/packages/System.Runtime.InteropServices.RuntimeInformation/) in the package for net45.

**Comment by Pathoschild** [comment]
Thanks for the suggestion!

I keep SMAPI's fork of Harmony as close to the upstream version as possible, so unfortunately a change like this would be out of scope for the fork. Normally I'd suggest submitting it to the upstream Harmony repo and SMAPI would pull the update, but this shouldn't be an issue in Harmony 2.0, and taking another look at Harmony 2.0 is one of my priorities after the Stardew Valley 1.5 release.

If you upload the compiled build somewhere, we could temporarily add something to the FAQs about adding the `0Harmony.dll` and RuntimeInformation package to `smapi-internal` on ARM64 systems though.
