### ISSUE TITLE
Autodetect path of Stardew Valley directory in a flatpaked steam client

### ISSUE THREAD

**Issue by saltedcoffii** [Pathoschild/SMAPI#739]
The Linux SMAPI install script does not autodetect a Stardew Valley install if the Steam Client is flatpaked. The path is `$HOME/.var/app/com.valvesoftware.Steam/data/Steam/steamapps/common/Stardew\ Valley`. Please fix this!

**Comment by Pathoschild** [comment]
Done in `develop` for the upcoming SMAPI 3.8.2.
