### ISSUE TITLE
Windows removing executable as a threat

### ISSUE THREAD

**Issue by cheshire137** [Pathoschild/SMAPI#740]
**Describe the bug**

I downloaded 3.8.0 from smapi.io today to play with the updated Stardew Valley 1.5. However, every time I tried to launch it from Steam, Steam gave an error about a missing executable. I noticed when I manually installed SMAPI and just watched my SDV install folder, the SMAPI executable disappeared after a few seconds. I checked Windows security and found this:

![smapi-threat-2020-12-21](https://user-images.githubusercontent.com/82317/102812149-2e86ca00-438c-11eb-8fe6-eaacbc45d1f6.png)

I don't know if this is just Windows 10 being overzealous, but I haven't had this problem with SMAPI before, through multiple versions. Maybe something is wrong with the executable?

**To Reproduce**

Do a direct download from smapi.io of SMAPI 3.8.0. Install on Windows 10. Wait and the executable disappears. Check Action Center in Windows to see if Windows determined it a threat.

**Log file**

There's no ErrorLogs directory in my `%appdata%\StardewValley` after updating Stardew Valley to 1.5, so I can't find SMAPI's log file.

**Comment by cheshire137** [comment]
Trying to download [from Nexus Mods](https://www.nexusmods.com/stardewvalley/mods/2400?tab=files&file_id=33253) instead of directly, Edge won't even let me download it:

![smapi-nexus-download-virus-2020-12-21](https://user-images.githubusercontent.com/82317/102813032-bd481680-438d-11eb-817c-e04d4afd9124.png)

**Comment by Pathoschild** [comment]
Hi! That's normal when the update is still new. See [_SMAPI files disappear or antivirus complains_](https://stardewvalleywiki.com/Modding:Player_Guide/Troubleshooting#SMAPI_files_disappear_or_antivirus_complains) in the troubleshooting guide for more info about why that happens, how to check if it's safe, and how to install it when that happens.

**Comment by cheshire137** [comment]
Thank you!
