### ISSUE TITLE
SMAPI.io log parser incorrectly parsing some mods.

### ISSUE THREAD

**Issue by kurumushi** [Pathoschild/SMAPI#743]
Mods using a colon (:) in the title seem to throw off the log parser. I have installled a mod with the description in the log:

More Food: A Collection of Recipes for JsonAssets 1.9.11 by Project Populate Json Assets | for  | A port of Mizu's recipe sprites for JsonAssets

In the log parser, it comes up as mod named "more" and version "food" in the suggested fixes section (mod is currently out of date)

Offending log parse:

https://smapi.io/log/202fb536c8cf4b5a9cfc5252039ea876

**Comment by Pathoschild** [comment]
Fixed in `develop` and deployed. Thanks for reporting it!
