### ISSUE TITLE
Game freeze in local co-op with four players

### ISSUE THREAD

**Issue by DiscipleOfEris** [Pathoschild/SMAPI#747]
**Describe the bug**
When playing the new local (split screen) co-op for 1.5, the game always freezes when the fourth player joins or attempts to join. This does not happen in vanilla, but it happens in SMAPI with zero mods installed, both when loading a game or creating a new game. I launch the game via Steam.

**To Reproduce**
1. Connect four controllers.
2. Launch game.
3. Create a new farm with three cabins.
4. Enable local co-op.
5. Join with second character. (Error messages occur in SMAPI console, but game works)
6. Join with third character. (Error messages occur in SMAPI console, but game works)
7. Attempt to join with fourth character.
8. Game freezes. (SMAPI console repeats the same message forever. I must manually close.)

**Log file**
https://smapi.io/log/ab5d8c764a2e4bea98ed2b06b076d96f

**Screenshots**
N/A

I haven't tested if mods work in local co-op despite the error (playing with only two or three players). I haven't tested four players in a combination of network and local co-op (eg. two players join via split screen, one player joins via Steam).

**Comment by Pathoschild** [comment]
Also [reported here on Reddit](https://www.reddit.com/r/SMAPI/comments/khmgyg/stardew_valley_15_released/ght79vh/), with [a similar log](https://smapi.io/log/3f8bd505d7074cd29eb6afa86da6e518). This seems to be an issue with the peer context/connection tracking, since both logs shows endless unexpected reconnections.

**Comment by Pathoschild** [comment]
Fixed in `develop` for the upcoming SMAPI 3.8.2.
