### ISSUE TITLE
Smapi Error, please help

### ISSUE THREAD

**Issue by kauleu** [Pathoschild/SMAPI#748]
My game was working normally, so after updating Smapi SV it stopped working :(. I discovered that the error was Stardew Valley (1.4.5.148), so I put the previous version and finally opened, but this time, errors were found and I didn't understand why. Here the smapi log: https://smapi.io/log/4a01168009d241848c9f5d55f2e4d093

**Comment by Pathoschild** [comment]
Hi! SMAPI for Android is an unofficial port by another developer, and the game has a lot of customizations on Android. Android modders don't watch issues here, so come ask in [#using-mods on the Stardew Valley Discord](https://smapi.io/community#Discord) instead and we'll help there!
