### ISSUE TITLE
Game.Initialize() caught exception initializing XACT: System.InvalidOperationException: This resource could not be created

### ISSUE THREAD

**Issue by MeianXGame** [Pathoschild/SMAPI#750]
Hello , i'm sorry but my english is very bad. 

I have a problem with Smapi when I start, it shows me these errors. I uninstall , reinstall the game , remove the mods , but do nothing about it , on my other pc, it works without error. I cleaned up the game files but I still have the same problem.

Do you have an idea? Thank you for your help.

Smapi log : https://smapi.io/log/8815830ac8414da49c6256cb540565f6

**Comment by Pathoschild** [comment]
Hi! GitHub issues are only used to track development tasks, so most people who could help don't watch here. See [Modding:Help](https://stardewvalleywiki.com/Modding:Help) on the wiki for the best places to ask instead.
