### ISSUE TITLE
Infinite loading screen

### ISSUE THREAD

**Issue by LongNameNTC** [Pathoschild/SMAPI#752]
I was playing Stardew Valley with some mods, including Stardew Valley Expanded, but when I enter a new area added by the map (new locations, houses, stores, etc), I get stuck in a loading screen that never load. Here is the full log:

https://smapi.io/log/563531eb3d374a55a20bc8740e72c410

I don't know how to use GitHub, sorry if I posted this in the wrong place. Thank you. =)

**Comment by Pathoschild** [comment]
Hi! You're missing important parts of the log, but the visible part shows that TMXL Map Toolkit is incompatible and has an update available. If updating your mods to the latest versions doesn't fix it, see [Modding:Help](https://stardewvalleywiki.com/Modding:Help) on the wiki for the best places to ask!
