### ISSUE TITLE
Website issue: Wiki URL is changing

### ISSUE THREAD

**Issue by User670** [Pathoschild/SMAPI#753]
The Stardew Valley Wiki's URL has changed from https://stardewvalleywiki.com/ to https://stardewcommunitywiki.com/ . smapi.io has at least one wiki link(s) that point to the old URL, please update the links before the old URL becomes unusable.

**Comment by Pathoschild** [comment]
Hi! My understanding is that `stardewcommunitywiki.com` is temporary and the wiki will be back at `stardewvalleywiki.com` once it's transferred to ConcernedApe, so no change is needed here. The local SMAPI client always redirects through `smapi.io` though, so we can update quickly if the final URL changes.
