### ISSUE TITLE
SMAPI 3.8.3 says that the oldest required SDV version is 1.5.2

### ISSUE THREAD

**Issue by whitebear60** [Pathoschild/SMAPI#755]
SMAPI 3.8.3 says that the oldest required SDV version is 1.5.2 but the https://smapi.io/ site says that the oldest required SDV version is 1.5.1
**To Reproduce**
1. Install Stardew Valley 1.5.1 (I've used GOG version)
2. Install SMAPI 3.8.3
3. Try ti run the game
4. See error:
![Screen Shot 2021-01-14 at 08 45 37](https://user-images.githubusercontent.com/42472132/104554954-b12a3e80-5645-11eb-97f2-cc701e8c0444.png)

**Comment by Pathoschild** [comment]
Thanks! I updated the site to show the correct version.
