### ISSUE TITLE
Console disappeared after game loaded

### ISSUE THREAD

**Issue by tulx17** [Pathoschild/SMAPI#756]
**Describe the bug**
I'm having 2 SDV version. The old one is SDV 1.5.2 use SMAPI 3.8.3 working just fine. But the SDV 1.5.3 use SMAPI 3.8.4 have this problem. The console disappeared after game loaded.

**Log file**
https://smapi.io/log/37868efdced24deba14354181dab8a4d

**Screenshots**
![image](https://user-images.githubusercontent.com/50549524/105429586-48197b00-5c84-11eb-9093-167a0f3463ca.png)

![image](https://user-images.githubusercontent.com/50549524/105429599-4f408900-5c84-11eb-8a00-cc41c50f1b93.png)

**Comment by Pathoschild** [comment]
@tunbk1002 What if you delete the `steam_api.dll` and `Steamworks.NET.dll` files, then [reset your game files](https://stardewcommunitywiki.com/Modding:Player_Guide/Troubleshooting#Reset_your_content_files) to download fresh versions?

**Comment by tulx17** [comment]
Well that's really worked. I still don't understand why? In the SDV 1.5.2 that error affect nothing.

**Comment by Pathoschild** [comment]
It seems like something changed in the Steam API, and the files in the game folder weren't fully updated. I'll let anyone else with the same issue know about that fix. Thanks for testing!
