### ISSUE TITLE
File Not Found Error After Installing SMAPI

### ISSUE THREAD

**Issue by a7x492** [Pathoschild/SMAPI#760]
**Describe the bug**

Everything worked fine before. I tried to install Stardew Valley mods for the first time, and then this happened. By the way, I am on Mac running the latest SV version from steam.

**To Reproduce**

1. Install SV normally on Mac
2. Install Mono (stable version)
3. Install SMAPI

* Note I did nothing out of the ordinary above. Everything is exactly the steps provided in the instructions on the wiki for how to add mods.

4. Try to run SV again from Steam, and get error. Crash on startup.

Log File: https://smapi.io/log/ea8b8a14d17b48c5ae7eebd07d6d286b

**Comment by Pathoschild** [comment]
Can you post a screenshot of the directory mentioned in the error?

**Comment by a7x492** [comment]
<img width="485" alt="Screen Shot 2021-02-01 at 3 47 13 PM" src="https://user-images.githubusercontent.com/78004039/106516231-c22bda00-64a4-11eb-81f9-94143e57c8e0.png">
<img width="479" alt="Screen Shot 2021-02-01 at 3 47 25 PM" src="https://user-images.githubusercontent.com/78004039/106516256-c952e800-64a4-11eb-828a-082817be8e1d.png">

**Comment by Pathoschild** [comment]
Can you post a screenshot of `~/Library/Application Support/Steam/steamapps/common/Stardew Valley/Contents/Resources/Content` (and the `XACT` subfolder if any)?

**Comment by a7x492** [comment]
```bash
❯ pwd
/Users/matt/Library/Application Support/Steam/steamapps/common/Stardew Valley/Contents/Resources/Content
❯ ls
Animals         Fonts           Strings
Buildings       LooseSprites    TerrainFeatures
Characters      Maps            TileSheets
Data            Minigames       VolcanoLayouts
Effects         Portraits       XACT
❯ ls XACT
FarmerSounds.xgs   Wave Bank(1.4).xwb
Sound Bank.xsb     Wave Bank.xwb
~/Library/Application Support/Steam/steamapps/common/Stardew Valley/Contents/Resources/Content 3.8.3 (miniconda3) ❯
```

**Comment by Pathoschild** [comment]
It seems like the game is trying to use Windows logic to find the content path for some reason. Can you come ask in [#using-mods on the Stardew Valley Discord](https://smapi.io/community#Discord) so we can run some tests? (Feel free to ping me there.)

**Comment by a7x492** [comment]
Hmm I wonder if that has to do with Mono? The https://stardewcommunitywiki.com/Modding:Installing_SMAPI_on_Mac page has installing Mono as the first step though. I posted in there but the channel seems busy so it might get buried

**Comment by Pathoschild** [comment]
I'll close this ticket since it's not a specific SMAPI issue yet, but feel free to ping me in that channel so we can run some tests. (The channel can be busy, so I probably won't see it if you post without pinging me.)
