### ISSUE TITLE
i cant seem to find the stardewmoddingAPI.exe file.

### ISSUE THREAD

**Issue by SiggzXO** [Pathoschild/SMAPI#761]
i just downloaded smapi but for some reason it doesnt show the file anywhere, i have the steam stardew and im not too sure how i can run my modded game thx for the help in advance.

**Comment by Pathoschild** [comment]
Hi! GitHub issues are only used to track development tasks, so most people who could help don't watch here. See [Modding:Help](https://stardewvalleywiki.com/Modding:Help) on the wiki for the best places to ask instead.
