### ISSUE TITLE
3.9.3 Installer Error "System.IO.DirectoryNotFoundException"

### ISSUE THREAD

**Issue by horizon98** [Pathoschild/SMAPI#764]
**Describe the bug**
A clear and concise description of what the bug is. Provide any other details you think might be relevant here.

SMAPI 3.9.3 will not create `Stardew Valley\Mods` folder automatically. After I deleting the Mods folder and run `install on Windows.bat` , an error occurred: 

> System.IO.DirectoryNotFoundException: Can't find the path "C:\Program Files (x86)\Steam\steamapps\common\Stardew Valley\Mods"

When I switched to SMAPI 3.9.2, everything is ok.

Environment: Windows 10 20H2, Steam, Stardew Valley 1.5.4, SMAPI 3.9.3.

**To Reproduce**
Exact steps which reproduce the bug, if possible. For example:
1. Load save '...'.
2. Walk to '....'.
3. Click '....'.
4. Error occurs.

**Log file**
Upload your SMAPI log to https://smapi.io/log and post a link here.

**Screenshots**
![image](https://user-images.githubusercontent.com/48114360/110273400-77ebca80-8007-11eb-9848-0b1dfa64820b.png)

**Comment by Pathoschild** [comment]
Fixed in the upcoming SMAPI 3.9.4. Thanks for reporting it!
