### ISSUE TITLE
Community Center Bundles was mixed up in Non-English language

### ISSUE THREAD

**Issue by horizon98** [Pathoschild/SMAPI#765]
**Describe the bug**
A clear and concise description of what the bug is. Provide any other details you think might be relevant here.

**To Reproduce**
Exact steps which reproduce the bug, if possible. For example:
1. Set the game language to Chinese.
2. Quit the game and then launch it again.
3. Create a new save with SMAPI 3.9.2 or 3.9.3.
4. **Exiting to the title** before unlocking the bundles on **Spring 5th**.
5. Load the save (Including other saves which haven't unlocked the Community Center Bundles).
6. Complete "Meet the Wizard" quest on Spring 6th.
7. The Spring Foraging Bundle was unlocked automatically, and other bundles needs incorrect amounts of items. For example, the Winter Foraging Bundle needs 6 items instead of 4 items. The name of other bundles are "2 收集包" (means 2 bundles), "3 收集包", "4 收集包", "5 收集包", "6 收集包".
8. SMAPI console outputs that "Found broken community center bundles and fixed them automatically."

Then I exit to the title and change the language to English, and re-complete "Meet the Wizard" quest again. The  Spring Foraging Bundle was still unlocked automatically, but the name of other bundles are right.

[Several players in China have met the problems, too.](https://tieba.baidu.com/p/7243423378) Maybe they need to fix the error in their saves.

Environment: Windows 10 20H2, Steam, Stardew Valley 1.5.4, SMAPI 3.9.2/3.9.3, Mods: 
>[SMAPI] Loaded 6 mods:
>[SMAPI]    CJB Cheats Menu 1.27.0 by CJBok and Pathoschild | Simple in-game cheats menu!
>[SMAPI]    CJB Item Spawner 2.0.2 by CJBok and Pathoschild | Simple in-game item spawner!
>[SMAPI]    CJB Show Item Sell Price 1.9.10 by CJBok and Pathoschild | Show item sell price in your inventory!
>[SMAPI]    Console Commands 3.9.3 by SMAPI | Adds SMAPI console commands that let you manipulate the game.
>[SMAPI]    Error Handler 3.9.3 by SMAPI | Handles some common vanilla errors to log more useful info or avoid breaking the game.
>[SMAPI]    Save Backup 3.9.3 by SMAPI | Automatically backs up all your saves once per day into its folder.

**Log file**
Upload your SMAPI log to https://smapi.io/log and post a link here.
https://smapi.io/log/a3ea9272a9eb4afaac5f3e520761ac4e

**Screenshots**
![image_1](https://user-images.githubusercontent.com/48114360/110279831-b936a700-8014-11eb-99b9-ab226aa22a71.png)
![image_2](https://user-images.githubusercontent.com/48114360/110279849-c0f64b80-8014-11eb-9177-8cb37a66814d.png)
![image_3](https://user-images.githubusercontent.com/48114360/110281188-2f3c0d80-8017-11eb-9011-6eb924b58245.png)

Thanks for all you have done! 😀

**Comment by Pathoschild** [comment]
@horizon98 Does this version fix the problem if you start a new save? (This won't retroactively fix affected saves yet.)

* [SMAPI 3.9.5-alpha.20210314 installer (Windows only).zip](https://github.com/Pathoschild/SMAPI/files/6137106/SMAPI.3.9.5-alpha.20210314.installer.Windows.only.zip)

**Comment by horizon98** [comment]
@Pathoschild Fixed! Thanks for your work. But there's a little side effect in 3.9.5 alpha: When I exit to the title in non-English language, there's a lag where can't move mouse for about 2 seconds. Anyway, the bundle bug has been fixed. Thanks.

**Comment by Pathoschild** [comment]
@horizon98 Can you try with this build? It has two main changes:

* You should have less lag when returning to the title screen.
* If a save has corrupted bundles, you can enter the `regenerate_bundles confirm` console command to reset them.

[SMAPI 3.9.5-alpha.20210316 installer (Windows only).zip](https://github.com/Pathoschild/SMAPI/files/6152761/SMAPI.3.9.5-alpha.20210316.installer.Windows.only.zip)

**Comment by horizon98** [comment]
@Pathoschild Thanks for your work! There's no lag when returning to the title screen. And the command truly took effect under normal conditions. But there's another bug when I tried to exit to the title and then enter this command. ＞︿＜

1. Load the save and exit to the title.
2. Re-load the save and enter the command.
3. Right click the bundle (Golden Scroll) in the Community Center and nothing happened.
4. SMAPI Console output many errors. Despite how I moved, the screen wouldn't change. Even if I have used CJB cheater menue to wrap, nothing happened.
5. The only thing I can do is exit to the title/desktop.

Here's the log:  https://smapi.io/log/5a55bef2ad2c4124a41f36c78d8da315

**Comment by Pathoschild** [comment]
@horizon98 Fixed! Can you try with this build?

* [SMAPI 3.9.5-alpha.20210320 installer (Windows only).zip](https://github.com/Pathoschild/SMAPI/files/6176859/SMAPI.3.9.5-alpha.20210320.installer.Windows.only.zip)

**Comment by horizon98** [comment]
@Pathoschild Everything works well now! And the command didn't result in any error in my test. Thanks for your work.

**Comment by Pathoschild** [comment]
Thanks for testing! This will be in the upcoming SMAPI 3.9.5.

**Comment by Denky-san** [comment]
hello, im with the same problem, and i have the version 3.10.1 is it rly fixed?

**Comment by Pathoschild** [comment]
Can you come ask in [#using-mods on the Stardew Valley Discord](https://smapi.io/community#Discord) so we can ask questions, run some tests, etc? (GitHub issues are only used for specific development tasks with repro steps, etc.)
