### ISSUE TITLE
world_clear doesn't clear large resource clumps from IslandWest

### ISSUE THREAD

**Issue by hpeinar** [Pathoschild/SMAPI#770]
**Describe the bug**
Running `world_clear current everything` or `world_clear IslandWest everything` doesn't remove the large resource clumps like large stones etc.

**To Reproduce**
Running SMAPI version 3.9.5, Stardew Valley 1.5.4 on PC
1. Created a new game
2. `debug warp IslandWest`
3. `world_clear current everything`
4. Large resources are not removed as expected. Same command works as expected in farm map.

**Screenshots**
![img of reproducable steps](https://user-images.githubusercontent.com/490959/112369953-7b5ca280-8ce5-11eb-9fad-8cc0c09e55f3.png)

**Comment by Pathoschild** [comment]
Fixed in `develop` for the upcoming SMAPI 3.9.6. Thanks for reporting it!
