### ISSUE TITLE
Can't load DLL

### ISSUE THREAD

**Issue by zarcheur** [Pathoschild/SMAPI#771]
Hi, how to resolve this?
![Screenshot_20210331-174816](https://user-images.githubusercontent.com/81684461/113129288-4ef8d700-924d-11eb-9cf7-bd2ed2a1d126.jpg)

I also checked the mod file, It has DLL on it
![Screenshot_20210331-181755_ES File Explorer](https://user-images.githubusercontent.com/81684461/113129413-7059c300-924d-11eb-8ff8-c915206d4bcb.jpg)

**Comment by Pathoschild** [comment]
Hi! GitHub issues are only used to track development tasks, so most people who could help don't watch here. See [Modding:Help](https://stardewvalleywiki.com/Modding:Help) on the wiki for the best places to ask, but in this case I suggest asking on the Producer Framework Mod page.
