### ISSUE TITLE
Text wrong color when running install_on_linux.sh

### ISSUE THREAD

**Issue by miome** [Pathoschild/SMAPI#772]
When running SMAPI 3.9.5 install on Linux.sh, and selecting light text on dark background, the following portion of the output is printed in black text:

```Game path: /home/miome/.steam/steam/steamapps/common/Stardew Valley
Color scheme: light text on dark background
----------------------------------------------------------------------------

Removing SMAPI launcher...
Removing previous SMAPI files...
Adding SMAPI files...
Safely replacing game launcher...
Adding bundled mods...
   adding Save Backup...
   adding Error Handler...
   adding Console Commands...

```
My OS is Ubuntu 18.04 LTS and my terminal is Gnome Terminal

**Comment by Pathoschild** [comment]
Hi! Do you mean this dark gray text color?
> ![image](https://user-images.githubusercontent.com/230581/116823809-ac39be00-ab54-11eb-9be3-54218b07f5cb.png)

That's deliberate if so. That's `DEBUG`-level text, which should appear faded or 'grayed out' compared to the normal white `INFO` text.

If you're seeing fully black text so it's not readable, can you ping me on Discord so we can run some tests?
