### ISSUE TITLE
Stops looking in nested mod folders if there is a ".ico" and ".ini" file in it (FolderIco incompatibilities)

### ISSUE THREAD

**Issue by zwei7** [Pathoschild/SMAPI#773]
I colour my 400+ Mod folders in my Stardew Valley/Mods folder to keep them organized with FolderICO.

FolderIco embeds 2 files that cause SMAPI to not look deeper into a complicated nested Stardew Valley Mod folder.
1. Example Coloured Folder image.ico
2. desktop.ini

If SMAPI could ignore these 2 file types and continue looking deeper into the Mod's folder that would be great.

Nested folder are found in mods like Stardew Valley Expanded, Boarding House, Stardew Aquarium, or any map mod. Usually map mods include a seperate folder for [CP], [TMXL], [FTM], [JA], [PFM], [TMX] and etc.

Usually SMAPI will say it could not find the manifest.json file of my complicated map mods if I colour my map mod folder since it does not look deeper to find said manifest.json file.

As a sidenote, FolderIco does not rely on one centralized DLL library file with 100's of icons. It includes the ini and ico file in EACH and EVERY folder so when you move a folder to another PC it will always work since it is decentralized. Other PCs do not need to have FolderIco installed.

**Comment by Pathoschild** [comment]
Sure! The upcoming SMAPI 3.10 will ignore `*.ico` files too (it already ignores `desktop.ini`).

**Comment by zwei7** [comment]
Thanks Pathoschild!
Now I can have colourful folders again!
