### ISSUE TITLE
SMAPI no longer loading savefile or writing a new one

### ISSUE THREAD

**Issue by Iarinu** [Pathoschild/SMAPI#774]
**Describe the bug**
Every time I try to load an existing savefile, after a short while the game kicks me back to the main-menu. After that the option for loading said savefile disappears from the load menu.
Trying to start a brand new game, everything works fine, until the first autosave after the cutscenes. While trying to save the new file, the game just hangs indefinitely.  A look at the filesystems shows, that the folder for the savegame had been created but the file itself stayed at 0 Bytes size.
Even with SMAPI set to log verbose, the only error in the log is:

> [SMAPI] An error occurred in the overridden update loop: System.NullReferenceException: Object reference not set to an instance of an object
>   at (wrapper dynamic-method) StardewValley.SaveGame+<getLoadEnumerator>d__94:StardewValley.SaveGame+<getLoadEnumerator>d__94.MoveNext_Patch0 (object)
>   at StardewModdingAPI.Framework.SCore.OnPlayerInstanceUpdating (StardewModdingAPI.Framework.SGame instance, Microsoft.Xna.Framework.GameTime gameTime, System.Action runUpdate) <0x42525940 + 0x0075f> in <filename unknown>:0 

which sadly doesn't help me locating the cause for this.

Also I'm aware that there are error for the mods "Furry Farmer" and "Event Repeater". I've already tried it without both, with the exact same result.

**To Reproduce**
Exact steps which reproduce the bug, if possible. For example:
1. Start game
2. At main menu click "Load"
3. Try to load any existing savegame
4. Error occurs.

**Log file**
https://smapi.io/log/39b544dfc9894bdfa4c9d264a0862bd1

**Screenshots**
N/A

**Comment by Pathoschild** [comment]
That seems to be an issue with Entoarox Framework 2.5.4. I suggest reinstalling Entoarox Framework 2.5.3 until the author can look into it.
