### ISSUE TITLE
Illegal characters in save name

### ISSUE THREAD

**Issue by Gaphodil** [Pathoschild/SMAPI#791]
Adding [invalid path characters](https://docs.microsoft.com/en-us/dotnet/api/system.io.path.getinvalidpathchars) to the name of the farm when making a save causes a `System.ArgumentException: Illegal characters in path.`

This issue is not present in the vanilla version of the game (with illegal characters in both farmer name and farm name). This also creates the save regardless, which is able to be loaded and saved without issue.

**To Reproduce**
Tested on SMAPI 3.11.0 with an emptied mod folder, as well as with SaveBackup.

1. Start a new game.
2. Use any characters in the set of invalid path characters in the name of the farm.
3. Click 'OK'.
4. Game hardlocks while fading in after 'Your progress has been saved.'

[**Log file**](https://smapi.io/log/03f89f9a9e6b4d2aa7438bfbe5181113)

**Comment by Pathoschild** [comment]
Fixed in `develop` for the upcoming SMAPI 3.12.0. Thanks for reporting it!
