### ISSUE TITLE
Community Center Bundles in multiplayer had incorrect amount of items and broken names on Non-English language

### ISSUE THREAD

**Issue by AppleNorris** [Pathoschild/SMAPI#795]
**Describe the bug**
Bundle-breaking bug that appears to be happening on Non-English languages.
In my case happened in multiplayer.
Bundle names are breaking and appearing as "Узелок 1" (Bundle 1), "Узелок 2" (Bundle 2), "Узелок 3" (Bundle 3), and so on.
Bundle table is breaking and shows incorrect amount of items that are needed for the bundles.
There is a possibility that this bug happens to be the same as [#765](https://github.com/Pathoschild/SMAPI/issues/765), but this time it happens in multiplayer.

[SV Forum Thread](http://forums.stardewvalley.net/threads/bug-several-bugs-on-community-center-bundles.6386/post-48567) - it seems that Portuguese players have the same issue in multiplayer.
[SV Forum Thread](https://forums.stardewvalley.net/threads/bug-too-many-slots-in-the-community-center.7225/) - it's the same bug as in April.

**To Reproduce**
1. Start both client and server on Russian.
2. Create a new save in multiplayer.
3. Play for some time (in my case this bug happened three times - on Summer 28, Fall 11, Fall 15) while getting bundles done.
4. It will break, just give it time.

Command "regenerate_bundles" does reset all bundles, but they broke in a few days anyway.

Environment server: Windows 10 21H1, Steam, Stardew Valley 1.5.4, SMAPI 3.12.0.
Environment client: Windows 7 (all latest updates), Steam, Stardew Valley 1.5.4, SMAPI 3.12.0.
Both server and client are using similar modlists that are shown in the log below.

**Log file**
Updated:
https://smapi.io/log/c8cf67946d3142dbbea0ae1819447440 - my log.
https://smapi.io/log/48fc4dbc71df4f458b0c4e6c8e431a48 - friend's log.

**Screenshots**
![svb1](https://user-images.githubusercontent.com/24507135/127791337-7bcb1ab0-161f-4a83-9446-ad26c81ee76a.jpg)
![svb7](https://user-images.githubusercontent.com/24507135/127791339-f0abb93e-7291-4dba-af1c-0b7d50ac53a3.jpg)
![svb6](https://user-images.githubusercontent.com/24507135/127791340-7090a8df-0b59-4384-850e-7047510e2950.jpg)
![svb5](https://user-images.githubusercontent.com/24507135/127791342-ffbc895f-4019-43f5-8afb-44322f9af503.jpg)
![svb4](https://user-images.githubusercontent.com/24507135/127791343-bf9c04cc-3ff4-4e88-bdbf-5d6b11ea2475.jpg)
![svb3](https://user-images.githubusercontent.com/24507135/127791344-31254a64-1a3c-4d50-8dd1-9198da7f23d3.jpg)
![svb2](https://user-images.githubusercontent.com/24507135/127791346-c61f2df8-4f5c-4243-942d-018213a93a0a.jpg)

All other bundles are finished and I can't see them, but I presume that they do have the same issue.

**Comment by AppleNorris** [comment]
Tested it a bit - doesn't seem like this is something that has to do with cutscenes (that are tied to the ones with junimos) or bundles themselves (tried to fill bundles one by one - hadn't experienced any bugs).
I think it has something to do with the Witch cutscene? At least it's the only cutscene that happened before the first case - or maybe it has something to do with the black egg (though we had a bit more than 3 eggs... still it might be a good lead) - or it doesn't matter at all.

Added:
Tried savefile from 'halfqheart'. It seems that we have a few things in common - Skull Key, Dwarvish Translation Guide, cat, mushroom cave, chicken coop, lvl2 house.

**Comment by Kostyansa** [comment]
Same problem, same language, but SMAPI is version 3.11.0
And i think with  AppleNorris we have only UI Info Suite 2.0.0 in common from mod list.
Broken bundles:
![image](https://user-images.githubusercontent.com/18513731/129449618-ce7ee163-3c8c-4394-8daf-c4a2c5d2541b.png)
![image](https://user-images.githubusercontent.com/18513731/129449631-06c8e4e8-f4ee-453c-b347-543741f262e5.png)
Log:
https://smapi.io/log/ec16cab77a7748d892cdddf3218ae7c8
Save file with broken bundles:
[Star_287512165.zip](https://github.com/Pathoschild/SMAPI/files/6986616/Star_287512165.zip)

**Comment by AppleNorris** [comment]
I have found that this bug always duplicates last "/ {NUMBER}" before "</ string>" and that it can possibly lead to savefile bloating - had to manually clean about 300kb of the duplicate numbers after one in-game year, even after finishing all bundles.

**Comment by Pathoschild** [comment]
SMAPI 3.12.6 no longer updates in-game bundles to reflect mod changes to the bundle data, so the bundle corruption should no longer happen. See #805 for a related issue that still happens in 3.12.6+.
