### ISSUE TITLE
Remove log / broken char

### ISSUE THREAD

**Issue by LeGmask** [Pathoschild/SMAPI#798]
**Describe the bug**
In the new version there a bunch of log, such as set windows size etc, is there a way to remove them ? Also there a few broken char at startup `����`.

**Comment by Pathoschild** [comment]
Can you post a screenshot of what you see?

**Comment by LeGmask** [comment]
Yeah ofc: 
![image](https://user-images.githubusercontent.com/53308142/129453141-64d97fec-ed27-4f00-91ab-89829cdfa412.png)

![image](https://user-images.githubusercontent.com/53308142/129453137-84159593-62f5-4264-8c8b-605366aa37d3.png)

**Comment by Pathoschild** [comment]
Do you remember which specific version you had before it started happening?

**Comment by LeGmask** [comment]
Yeah all is working with SMAPI 3.11, with this version I've no issue.
![image](https://user-images.githubusercontent.com/53308142/129679632-89be25df-9867-4d9c-9273-7a7044fd2264.png)

**Comment by Pathoschild** [comment]
That should be fixed in the upcoming SMAPI 3.12.3. Let me know if you still have any issues when you get the update. Thanks for reporting it!

**Comment by LeGmask** [comment]
Okay thanks for the fix !

**Comment by LeGmask** [comment]
I've just tested work perfectly :+1: thanks !
