### ISSUE TITLE
Translations through a temporary content pack are not correctly updated when SMAPI loads translations

### ISSUE THREAD

**Issue by spacechase0** [Pathoschild/SMAPI#802]
**Describe the bug**
I used `Helper.ContentPacks.CreateTemporary` to create a content pack for a mod, but the translations in the `i18n` folder do not appear to be loading.

**To Reproduce**
Exact steps which reproduce the bug, if possible. For example:
1. Create content pack with `Helper.ContentPacks.CreateTemporary` (in `GameLaunched` in my case).
2. Fetch a translation from it.
3. Be sad when it says no translation found.

**Comment by Pathoschild** [comment]
Fixed in SMAPI 3.12.6. Thanks for reporting it!
