### ISSUE TITLE
Virus detected on SMAPI 3.12.5

### ISSUE THREAD

**Issue by dmatton** [Pathoschild/SMAPI#804]
Hello,

Impossible to install this new release, because my antivirus (BitDefender) detected a virus (**Gen:Variant.Bulz.648117**) in the file **StardewModdingAPI-x64.exe**...

It's the first time that happen.

Regards,

**Comment by Pathoschild** [comment]
Hi! See _[SMAPI files disappear or antivirus complains](https://stardewvalleywiki.com/Modding:Player_Guide/Troubleshooting#SMAPI_files_disappear_or_antivirus_complains)_ in the troubleshooting FAQs for more info about why that happens, how to confirm it's safe, and how to install SMAPI when that happens.
