### ISSUE TITLE
The version of my game is 1.5.4, but SMAPI find 1.5.5 or later and set error

### ISSUE THREAD

**Issue by tianchen-first** [Pathoschild/SMAPI#810]
**Describe the bug**
A clear and concise description of what the bug is. Provide any other details you think might be relevant here.

**To Reproduce**
Exact steps which reproduce the bug, if possible. For example:
1. Load save '...'.
2. Walk to '....'.
3. Click '....'.
4. Error occurs.

**Log file**
Upload your SMAPI log to https://smapi.io/log and post a link here.

**Screenshots**

**Comment by tianchen-first** [comment]
log:
Oops! The detected game install path seems to be Stardew Valley 1.5.5 or later, but this version of SMAPI is only compatible up to Stardew Valley 1.5.4. Please check for a newer version of SMAPI: https://smapi.io.

**Comment by Pathoschild** [comment]
Hi! GitHub issues are only used to track specific development tasks, so many of the users who could help troubleshoot errors don't watch here. See [Modding:Help](https://stardewvalleywiki.com/Modding:Help) on the wiki for the best places to ask for help.
