### ISSUE TITLE
Lagging with and without mods [1.5.5 BETA]

### ISSUE THREAD

**Issue by Bellabeau6** [Pathoschild/SMAPI#811]
**Describe the bug**
I was playing lag-free with a bunch of mods for a while but soon I started noticing drops in frame rate and attempts to fix the lag (optimising, removing mods, etc.) made the problem worse and the lag got more and more obvious the more I attempted to fix it. so I moved (not deleted) all of my mods out of my mods folder leaving just a pure vanilla game, loaded it and made a test save and the lag was still there. the lag was most severe when I left the house, took out my scythe and used it, it causes a major drop in frame rate on the first swing, both before and after removing the mods in the same severity. after that, I get stutters and lag spikes. 

I'm not sure if this can be reproduced but here's what happened.
- loaded the smapi beta with a load of mods
- played lag-free for a few sessions (totalling around 40 hours)
- lag starts in the form of small spikes and gradually worsens to more noticeable spikes in lag. the game isn't slow or unplayable or extremely laggy but the lag spikes were a nuisance 
- all attempts to optimise my computer and the game (i even resorted to overclocking(via MSI afterburner)) gave barely any or no improvement or made the lag spikes worse.
- I moved everything out of the mod folder and launched it as a test and low and behold the lag was still there. 

eventually, I deleted smapi and went back to 1.5.4 which crashed when I tried to make a fresh save. so I decided to give 1.5.5 another shot with smapi and my lag was magically gone. I don't know if it was a bug. I don't know if it's corruption. I was just told to put in a report because it may be a bug

I, unfortunately, lost the log and didn't get screenshots so you're just going to have to go off of what I've written here.

(sorry if there are typos)

**Comment by Pathoschild** [comment]
Hi! There might have been an issue with the game files or save data, since resetting the beta version fixed it. I can't look into it further without the log details though. If it happens again, come ask in [#using-mods on the Stardew Valley Discord](https://smapi.io/community#Discord) and we can run some tests to track down the cause (feel free to ping me with `@Pathoschild#0001` there).
