### ISSUE TITLE
SMAPI Installer Bug: dotnet --info does not return the 64 bit .NET SDKs and Runtimes

### ISSUE THREAD

**Issue by itsanonmelody** [Pathoschild/SMAPI#814]
**Describe the bug**
The dotnet program used in the batch file for installing on Windows sometimes is the 32 bit version of the program. This means that the program only detects 32 bit .NET SDKs and Runtimes.

**To Reproduce**
1. The path to the 64 bit version of the dotnet program comes after the 32 bit version in the Path system environment variable.
2. Run SMAPI installer.
3. Error occurs.

**Screenshots**
When the 64 bit version of dotnet comes after the 32 bit version.
![image](https://user-images.githubusercontent.com/37172966/144247289-e6f4cab2-0e21-49ec-9481-8f7b941f3304.png)

When the 64 bit version of dotnet comes before the 32 bit version.
![image](https://user-images.githubusercontent.com/37172966/144247009-1046d81c-027b-4fc4-86c6-7f902c70868d.png)

The .NET Desktop Runtimes installed on my computer.
![image](https://user-images.githubusercontent.com/37172966/144248468-2c35b382-8f08-436d-bd4d-ed43046d7ca9.png)

Edit: Added the output of dotnet --info for both cases.

**Comment by Pathoschild** [comment]
Fixed in SMAPI 3.13.2, which no longer needs any version of .NET to be installed. Thanks for reporting it!
