### ISSUE TITLE
SMAPI cannot open a terminal when using flatpak steam

### ISSUE THREAD

**Issue by vermarine** [Pathoschild/SMAPI#819]
**Describe the bug**
The [flatpak version of steam](https://flathub.org/apps/details/com.valvesoftware.Steam) has no access to the binaries of the host so unix-launcher.sh fails to detect and launch a terminal and proceeds to run headless, leaving the user with no way to access the SMAPI console.

A dirty workaround could be to use flatpak-spawn --host within unix-launcher.sh to open itself (unix-launcher.sh) on the host and then within the launcher running on the host proceed with the shell detection and finally return to the flatpak sandbox (ex. with `gnome-terminal -- flatpak enter com.valvesoftware.Steam sh -c "cd \"$HOME/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/common/Stardew Valley\" && ./StardewModdingAPI STEAM_RUNTIME=..."`)

**To Reproduce**
1. Install the flatpak version of Steam (Linux)
2. Install Stardew Valley on the flatpak version of Steam
3. Install SMAPI
4. Launch Stardew Valley: the SMAPI console is never shown

**Comment by Pathoschild** [comment]
Hi! I don't use the Flatpak version of Steam, but pull requests are welcome if you want to contribute a fix for it.

**Comment by Pathoschild** [comment]
The [install guide on Linux](https://stardewvalleywiki.com/Modding:Installing_SMAPI_on_Linux) covers Flatpak too now, so I'll close this. Thanks for reporting it!
