### ISSUE TITLE
White screen at launch and not responding when using smapi

### ISSUE THREAD

**Issue by MindOfMelyse** [Pathoschild/SMAPI#821]
**Describe the bug**
When I launch the game using Smapi, I get a white screen. Even after restarting and making sure everything was up to date it still yields a white screen and not responding. This occurred after I got in game and clicked "Exit to desktop" which i've done in the past but this broke it for some reason. 

**To Reproduce**
Exact steps which reproduce the bug, if possible. For example:
1. Launch Game
2. Smapi loads fine, no error message shown
3. Game goes whitescreen and does not respond

**Log file**
https://smapi.io/log/947179a9b2e34cb4acd7af44f6d9e5d6

**Screenshots**
https://1drv.ms/u/s!Ag0r_N_IuFQjrkpTZZioV6CqfRzt?e=RlmLCO

**Comment by Pathoschild** [comment]
Hi! That's probably an issue with one of your mods, not SMAPI itself. GitHub issues are only used to track specific SMAPI development tasks, so many of the users who could help troubleshoot don't watch here. See [Modding:Help](https://stardewvalleywiki.com/Modding:Help) on the wiki for the best places to ask for help.
