### ISSUE TITLE
Delete key does not work on MacOS in console

### ISSUE THREAD

**Issue by elizabethcd** [Pathoschild/SMAPI#822]
**Describe the bug**
The delete key on MacOS does not change the text shown in the console, although the actual effect of the delete key (removing the previous typed character) does happen. This makes it extremely difficult to type in console commands, since any typo will remain onscreen.

**To Reproduce**
Exact steps which reproduce the bug, if possible. For example:
1. Install SMAPI on MacOS
2. Launch SMAPI
3. Type a console command but make a mistake, then hit the delete key.

**Log file**
I don't think a log file would be helpful, but I can generate one if needed.

**Screenshots**
Please note the slight (1 character) difference between screenshots—I typed "patch s", then "delete", then some nonsense because I remembered patch summary would spit out too many words.
<img width="565" alt="Screen Shot 2021-12-25 at 9 07 22 PM" src="https://user-images.githubusercontent.com/55162529/147399447-401da872-2577-44ac-b3a0-5b1f7a8ccbe9.png">
<img width="568" alt="Screen Shot 2021-12-25 at 9 07 31 PM" src="https://user-images.githubusercontent.com/55162529/147399449-b2178ea2-ee70-4cf7-b441-d727d1880e9b.png">

**Comment by Pathoschild** [comment]
Fixed in the upcoming SMAPI 3.13.3. Thanks for reporting it!
