### ISSUE TITLE
Add Ukrainian language

### ISSUE THREAD

**Issue by DanielleTlumach** [Pathoschild/SMAPI#823]
Hi there)
Could you please add my translations in Ukrainian for all these mods (Automate, ChestsAnywhere, CJB Cheats Menu, CJBItemSpawner, CJBShowItemSellPrice, DataLayers, DebugMode, LookupAnything, NoclipMode, NPCMapLocations, SmallBeachFarm and TractorMod) and SMAPI itself?)
Thanks in advance)

P.S : Yes, there is already a Ukrainian Mod for Stardew Valley 1.5.5+, which adds a new custom language to the game (obviously it's Ukrainian). Ukrainian mod for SDV :  https://www.nexusmods.com/stardewvalley/mods/8427
[SMAPI - Ukrainian.zip](https://github.com/Pathoschild/SMAPI/files/7797985/SMAPI.-.Ukrainian.zip)
[Automate - Ukrainian.zip](https://github.com/Pathoschild/SMAPI/files/7797986/Automate.-.Ukrainian.zip)
[ChestsAnywhere - Ukrainian.zip](https://github.com/Pathoschild/SMAPI/files/7797987/ChestsAnywhere.-.Ukrainian.zip)
[CJBCheatsMenu - Ukrainian.zip](https://github.com/Pathoschild/SMAPI/files/7797988/CJBCheatsMenu.-.Ukrainian.zip)
[CJBItemSpawner - Ukrainian.zip](https://github.com/Pathoschild/SMAPI/files/7797989/CJBItemSpawner.-.Ukrainian.zip)
[CJBShowItemSellPrice - Ukrainian.zip](https://github.com/Pathoschild/SMAPI/files/7797990/CJBShowItemSellPrice.-.Ukrainian.zip)
[DataLayers - Ukrainian.zip](https://github.com/Pathoschild/SMAPI/files/7797991/DataLayers.-.Ukrainian.zip)
[DebugMode - Ukrainian.zip](https://github.com/Pathoschild/SMAPI/files/7797992/DebugMode.-.Ukrainian.zip)
[LookupAnything - Ukrainian.zip](https://github.com/Pathoschild/SMAPI/files/7797993/LookupAnything.-.Ukrainian.zip)
[NoclipMode - Ukrainian.zip](https://github.com/Pathoschild/SMAPI/files/7797994/NoclipMode.-.Ukrainian.zip)
[NPCMapLocations - Ukrainian.zip](https://github.com/Pathoschild/SMAPI/files/7797995/NPCMapLocations.-.Ukrainian.zip)
[SmallBeachFarm - Ukrainian.zip](https://github.com/Pathoschild/SMAPI/files/7797996/SmallBeachFarm.-.Ukrainian.zip)
[TractorMod - Ukrainian.zip](https://github.com/Pathoschild/SMAPI/files/7797997/TractorMod.-.Ukrainian.zip)

**Comment by DanielleTlumach** [comment]
Hi.
I just wanted to say that translated into Ukrainian three more of your mods (HorseFluteAnywhere, SkipIntro and FastAnimations).
Please add them too in the new versions of these mods 🙂
[FastAnimations - Ukrainian.zip](https://github.com/Pathoschild/SMAPI/files/7799618/FastAnimations.-.Ukrainian.zip)
[HorseFluteAnywhere - Ukrainian.zip](https://github.com/Pathoschild/SMAPI/files/7799619/HorseFluteAnywhere.-.Ukrainian.zip)
[SkipIntro - Ukrainian.zip](https://github.com/Pathoschild/SMAPI/files/7799621/SkipIntro.-.Ukrainian.zip)

**Comment by Pathoschild** [comment]
Thanks for the help! Added in the upcoming...

* SMAPI 3.13.3;
* Automate 1.25.2;
* Chests Anywhere 1.21.2;
* CJB Cheats Menu 1.29.4;
* CJB Item Spawner 2.1.6;
* CJB Show Item Sell Price 1.9.14;
* Data Layers 1.15.3;
* Debug Mode 1.13.2;
* Fast Animations 1.9.11;
* Horse Flute Anywhere 1.1.13;
* Lookup Anything 1.36.2;
* Noclip Mode 1.2.11;
* NPC Map Locations 2.7.3;
* Skip Intro 1.9.7;
* Small Beach Farm 2.0.3;
* and Tractor Mod 4.14.10.
