### ISSUE TITLE
Selling Bamboo Rod at Willy's Shop make game become unresponsive

### ISSUE THREAD

**Issue by zwei7** [Pathoschild/SMAPI#824]
**Describe the bug**
On PC, when I try to sell the bamboo rod at Willy's Fish Shop, the entire game screen fades to white with 50% opacity and becomes unresponsive according to taskmanager. SMAPI logs reports no error and no problematic mod is identified at the time of the error. I recreated this 2x to make sure it wasn't a one time thing.

**To Reproduce**
Exact steps which reproduce the bug, if possible. For example:
1. Load single player save file
2. Walk to 'Willy's shop' at the beach
3. Use "time speed" mod to increase time speed so Willy will open his shop faster (I have also done this without time speed)
4. Talk to Willy at the counter to open shopping interface
5. Right click "bamboo rod" in inventory to sell it
6. Game becomes unresponsive and goes ghost white 50% opacity

**Log file**
https://smapi.io/log/0b6c999629c246a0b1c421bf5906e5db

**Notes**
3 Mods are intentionally out-of-date since their newest versions are broken.

**Comment by spacechase0** [comment]
Are you using Better Shop Menu in grid mode?

**Comment by zwei7** [comment]
Nope, it is in list mode, can only see 4 items in 4 rows.
Didn’t know there was a grid mode option.

**Comment by Pathoschild** [comment]
That's most likely an issue with one of your mods, not SMAPI itself. GitHub issues are only used to track specific SMAPI development tasks, so many of the users who could help troubleshoot errors don't watch here. See [Modding:Help](https://stardewvalleywiki.com/Modding:Help) on the wiki for the best places to ask for help.
