### ISSUE TITLE
[SMAPI: 3.13.2] [SDV:1.5.6] blank spots in smapi console 

### ISSUE THREAD

**Issue by ghost** [Pathoschild/SMAPI#825]
**Describe the bug**
SMAPI creates a lot of blank spots in the console. i think the trace lines are being shown as invisible. i selected some parts of it to show there are no invisible or black text there and also copy-pasted it into a text editor. i set the theme to DarkBackground in the smapi internal config.json but it still has issues. someone else on discord has this issue so I'm posting it here as a bug.

**To Reproduce**
1. Install smapi 3.13.2 and stardew valley 1.5.6
2. install some mods (it's better to install content patcher mods like world recolor).
3. load the game. there should be blank spots in the console. if you don't see any, load a save and walk outside if you have a world recolor mod to let content patcher edit the game files.
4. there should be a lot of blank spots in the console window.

**Log file**
Not needed for my case

**Screenshots**
attached 2 screenshots
![blank_spots2](https://user-images.githubusercontent.com/69715417/148644622-b6d92604-e6d6-4b58-b19b-726b46efe2a3.png)
ignore the maroon background of the above image
![blank_spots](https://user-images.githubusercontent.com/69715417/148644624-e718128c-4666-4c6a-8392-78dd03b1c366.png)

**Comment by ghost** [comment]
here is a link to the picture the other discord user sent:
"ah yeah, seems to be the case for me as well now. white is only space and text parts show as black"
https://cdn.discordapp.com/attachments/678284714829807636/929351294748098580/console.png

**Comment by Pathoschild** [comment]
Fixed in the upcoming SMAPI 3.13.3. Thanks for reporting it!
