### ISSUE TITLE
A way to hide the launcher terminal? For Steam Deck

### ISSUE THREAD

**Issue by LiamDawe** [Pathoschild/SMAPI#831]
Hi, trying to do a video on this for the Steam Deck but i've come up against an issue.

When you go to load with SMAPI installed, the terminal that comes up to tell you it's loading mods entirely covers the game and the Deck UI doesn't have an alt-tab like thing to swap to the actual Stardew Valley screen. Is there a way to have this SMAPI screen hidden somehow?

**Comment by Pathoschild** [comment]
Yep, you can do it like this on Linux (and I assume it's the same on Steam Deck):

1. [Open your game folder](https://stardewvalleywiki.com/Modding:Player_Guide/Getting_Started#Find_your_game_folder).
2. Open the `StardewValley` file (the one with no file extension) in a text editor.
3. Change `SKIP_TERMINAL=false` near the top to `SKIP_TERMINAL=true`.

You'll need to do that again each time you update SMAPI though, since it'll replace the launcher.

**Comment by LiamDawe** [comment]
Ah, perfect!

Did I miss this in the setup guide, I didn't spot a section on it.

**Comment by Pathoschild** [comment]
Nope, it was only meant as a last resort for [a gamepad support issue](https://stardewvalleywiki.com/Modding:Player_Guide/Troubleshooting#SMAPI_doesn.27t_recognize_controller_.28Steam_only.29). We'll probably need a section for instructions specific to the Steam Deck in the [Linux install guide](https://stardewvalleywiki.com/Modding:Installing_SMAPI_on_Linux) now though.

**Comment by LiamDawe** [comment]
Well, thanks to your help, I could whip up a video guide :D https://youtu.be/CrrWtqdbvC4

**Comment by Pathoschild** [comment]
Thanks for the guide! I added the initial Steam Deck info to the [Linux install guide](https://stardewvalleywiki.com/Modding:Installing_SMAPI_on_Linux), and added a link to your video.

**Comment by LiamDawe** [comment]
Oh wow, thank you! <3

**Comment by ghost** [comment]
This should probably be separated from the Linux guide as many users won't know what Linux is.

Is it also not possible to have a check to auto hide the terminal similar to how it checks for different terms?

**Comment by Pathoschild** [comment]
They still need to run the Linux installer, but we could maybe have something like this in the install guide?
> ![](https://user-images.githubusercontent.com/230581/158004424-156ae0bc-ff93-4836-a471-b04bcf03c69a.png)

I don't have a Steam Deck myself, but pull requests are welcome if you want to add Steam Deck detection to the launcher!

**Comment by ghost** [comment]
I'm terrible at scripting but I'll give it a go.

**Comment by ghost** [comment]
So, I currently have an ugly solution.

`if [ "$HOSTNAME" == "steamos" ]; then`
`    SKIP_TERMINAL=true`
`fi`

Obviously this will break if someone decides to change the systems hostname. Trying to figure out a way to check `/etc/os-release` as that will never change as long as the user is running steamos3 itself.

![1426489 2850000001_image](https://user-images.githubusercontent.com/4485158/158916615-dd2fd0db-45bd-4215-acbe-76b3052d173c.png)

**Comment by Pathoschild** [comment]
What does `$(uname)` return? We're already using that to check for macOS, so it might work for SteamOS too.

**Comment by Philip-Scott** [comment]
`uname` just returns Linux, although `uname --nodename` does return `steamdeck` so that could be an option. 

![image](https://user-images.githubusercontent.com/10786508/159522908-86f9677f-0b5f-4d55-add2-0ed85d57255b.png)
