### ISSUE TITLE
SMAPI is broken on the Steam Deck in gamescope

### ISSUE THREAD

**Issue by bpenda** [Pathoschild/SMAPI#833]
**Describe the bug**
When launching SMAPI on the steam deck in gamescope, the console window is incorrectly focused. The game window is not visible. 

**To Reproduce**
Exact steps which reproduce the bug, if possible. For example:
1. Install SMAPI on the stem deck2. 
2. Run stardew valley. 

Expected: the game window is visible
Actual: the console window is visible

**Comment by Pathoschild** [comment]
Hi! Make sure you follow all the steps in [the install guide](https://stardewvalleywiki.com/Modding:Player_Guide/Getting_Started#Install_SMAPI), which includes the steps to hide the console window on Steam Deck.

**Comment by bpenda** [comment]
Oh that's awesome, thank you!
