### ISSUE TITLE
SMAPI 3.14.0 hitches every 10 minutes

### ISSUE THREAD

**Issue by Yagisan** [Pathoschild/SMAPI#842]
**Describe the bug**
SMAPI was updated from 3.13.4 to 3.14.0. No other mods were updated. Now SMAPI hitches every 10 minutes in game.

**To Reproduce**
1. Upgrade to SMAPI 3.14.0
2. Load save.
3. Begin playing.
4. Hitch occurs every 10 in-game minutes.

**Log file**
SMAPI Log: [https://smapi.io/log/b61d2f64e04a46a7aac9e3bc73d5e87a](https://smapi.io/log/b61d2f64e04a46a7aac9e3bc73d5e87a)

**Video Footage of bug**
You can see the bug in action at [https://www.youtube.com/watch?v=RESupn5K7_w](https://www.youtube.com/watch?v=RESupn5K7_w) (45 second long video)

**Comment by DanielleTlumach** [comment]
You have broken some mods files.
I think that's what causes SMAPI every 10 minutes.

**Comment by DanielleTlumach** [comment]
> You have broken some mods files.
> I think that's what causes SMAPI every 10 minutes.

Here :

```
02:49:06	INFO	SMAPI	Found 124 mods with warnings:

02:49:06	ERROR	SMAPI	   Skipped mods

02:49:06	ERROR	SMAPI	   --------------------------------------------------
02:49:06	ERROR	SMAPI	      These mods could not be added to your game.

02:49:06	ERROR	SMAPI	      - CJBCheatsMenu because it contains files, but none of them are manifest.json.

02:49:06	ERROR	SMAPI	      - CJBItemSpawner because it contains files, but none of them are manifest.json.

02:49:06	ERROR	SMAPI	      - GreenhouseGatherers because it contains files, but none of them are manifest.json.

02:49:06	ERROR	SMAPI	      - IslandGatherers because it contains files, but none of them are manifest.json.

02:49:06	ERROR	SMAPI	      - NoclipMode because it contains files, but none of them are manifest.json.

02:49:06	ERROR	SMAPI	      - Root because it contains files, but none of them are manifest.json.

02:49:06	ERROR	SMAPI	      - SpriteMaster because it contains files, but none of them are manifest.json.
```

**Comment by DanielleTlumach** [comment]
Also it says that you can update 6 mods..

**Comment by Yagisan** [comment]
I appreciate your attempt at helping, however your assumption is incorrect.

The skipped mods are simply because, those folders contain only the config.json files.

The 6 non-updated mods were intentionally not updated to minimise changes in load order, to definitively identify SMAPI as the cause.

Updating the 6 mods that were not updated, doesn't change the fact the **SMAPI 3.14.0** is producing unplayable hitching, and **SMAPI 3.13.4** does not. This is a SMAPI regression.

**Comment by Pathoschild** [comment]
Hi!

First, try these common fixes to see if they make any difference for you. These might be needed even if you only updated SMAPI (e.g. a graphics utility may see the new SMAPI version as a different app and apply different settings).

* [Set the processor affinity](https://www.thewindowsclub.com/processor-affinity-windows) for `StardewModdingAPI` to 2 or higher.
* [Set the process priority](https://winaero.com/change-process-priority-windows-10/) for `StardewModdingAPI` to High.
* Under [_game doesn't launch_](https://stardewvalleywiki.com/Modding:Player_Guide/Troubleshooting#Game_doesn.27t_launch) in the troubleshooting guide, try _Run the game on your dedicated graphics card_.
* Temporarily disable your antivirus and other security software.
* Temporarily remove all mods except SMAPI and Error Handler. If that fixes it, one of your mods might be causing lag.
* Temporarily disable MSI Afterburner and RivaTuner if you have them installed (which you do).

If none of those made any difference, come ask in [#using-mods-help on the Stardew Valley Discord](https://stardewvalleywiki.com/Modding:Community#Discord), mention you already tried those fixes, and we'll add you to the performance thread.

It's not strictly a regression in SMAPI 3.14.0; I've gotten reports from users with performance issues in 3.13._x_ but not 3.14.0, vice versa, or in both. I'm focusing on some mod updates for SMAPI 3.14 first, but I'll be investigating all of the performance issues for the affected players in that thread right after that.

**Comment by Pathoschild** [comment]
I'll close this since it's not a specific dev task, but see the previous comment for the Discord link if you still need help!
