### ISSUE TITLE
Steam Deck Power Consumption without added mods

### ISSUE THREAD

**Issue by KylerN45** [Pathoschild/SMAPI#844]
**Describe the bug**
With the vanilla Stardew Valley executable, the steam deck appears to consume approximately 6W of power. However, when adding SMAPI (no additional mods), the wattage increases to about 20W, reducing battery life considerably!

**To Reproduce**
Exact steps which reproduce the bug, if possible. For example:
1. Install vanilla Stardew Valley
2. Open Game, enable Performance overlay, observe ~6W power consumption
3. Close game
4. Install SMAPI
5. Ensure SMAPI is configured to skip_terminal (SteamOS would fixate on the terminal, not the actual game itself)
6. Launch Smapi, enable performance overlay, observe ~20W power consumption

Additional photos incoming (unable to at present).

If testing users are required (due to general unavailability of the Steam Deck), feel free to let me know. I have a few years experience in Linux debug (GUI + CLI) and can lend a hand where necessary.

**Comment by Pathoschild** [comment]
Unfortunately I don't have a Steam Deck to look into that myself, so it's not a fully supported platform. I updated #632 to cover Steam Deck though, and pull requests are welcome if any developer with a Steam Deck wants to contribute any changes needed!
