### ISSUE TITLE
Incorrect SMAPI Version Number in File Properties

### ISSUE THREAD

**Issue by RyanWalpole** [Pathoschild/SMAPI#856]
**Describe the bug**
SMAPI 3.15.0 contains the wrong version number in the executable properties:

I've been making a mod manager and it has an internal SMAPI version detection that retrieves the version from the file information which then compares it to the most up to date version number on nexus mods, meaning even though SMAPI is up to date, because the executable's version number is incorrect, it thinks there is a newer version available.

**To Reproduce**
Exact steps which reproduce the bug, if possible. For example:
1. Right click on StardewModdingAPI.exe
2. Click "Properties"
3. Click "Details" tab
4. Observe incorrect file/product version number.

**Screenshots**
![image](https://user-images.githubusercontent.com/69621127/177661668-542dc3d7-be5d-40a9-8ac6-11b481372b4e.png)

**Comment by Pathoschild** [comment]
Hi! I downloaded SMAPI 3.15.0 from the [Nexus mod page](https://www.nexusmods.com/stardewvalley/mods/2400/), ran the installer, and the installed file's version matches as expected:
> ![](https://user-images.githubusercontent.com/230581/177662231-bf162843-c53d-4852-87f7-ac4c3b3ccd6b.png)

The version is [set by the release scripts](https://github.com/Pathoschild/SMAPI/blob/3.15.0/build/windows/set-smapi-version.ps1), so it should never be out of sync. SMAPI will also [assert that all its DLLs have the right version number](https://github.com/Pathoschild/SMAPI/blob/3.15.0/src/SMAPI/Program.cs#L142-L157) on startup.

If you still see the same issue on your end, can you come ask in [#making-mods on the Stardew Valley Discord](https://smapi.io/community#Discord]#using-mods) so we can run some tests? (Feel free to ping me there with `@Pathoschild#0001`.)

**Comment by RyanWalpole** [comment]
Interestingly, if I launch the Windows SMAPI installer from the bat file it does install 3.15.0 but when I launch the bat script programmatically it seems to latch on to an older copy of the SMAPI installer in a completely other folder, despite the file path being completely different.

Either way, sorry for the confusion - seems my PC is just having a stronk today and it's an isolated/local issue.
