### ISSUE TITLE
Log parser doesn't correctly handle invalid content packs

### ISSUE THREAD

**Issue by ellipszist** [Pathoschild/SMAPI#860]
**Log file**
https://smapi.io/log/f72cf058ae124e98bb024e485fccf9c9

**Screenshots**
![image](https://user-images.githubusercontent.com/43781364/179805211-8dbada15-ae70-4164-b9ec-3612a3fbddc2.png)

**Comment by Pathoschild** [comment]
Fixed and deployed. Thanks for reporting it!
