### ISSUE TITLE
Adding Exact coordiantes to world_clear/ability to remove permanate bushes

### ISSUE THREAD

**Issue by omegahack0** [Pathoschild/SMAPI#861]
for example being able to type 'world_clear "farm 47 55" everything' to clear everything from that tile on your farm such as individual permanent bushes. 
currently the closest thing you can do is 'world_clear farm everything' which will remove ... everything. Alternatively I could see the option for 'world_clear farm permanent_bushes' might be able add in.

**Comment by atravita-mods** [comment]
Destoryable Bushes already had that as a feature: https://www.nexusmods.com/stardewvalley/mods/6304

**Comment by Pathoschild** [comment]
Hi! The SMAPI console commands mainly serve as (a) quick debugging for mod authors, and (b) an escape hatch if something goes very wrong in a player's save. More flexible customization like that is best handled by more specific mods (like [Destroyable Bushes](https://www.nexusmods.com/stardewvalley/mods/6304) in this case).
