### ISSUE TITLE
Terminal doesn't exit when the game is closed normally

### ISSUE THREAD

**Issue by sleepingdragoninn** [Pathoschild/SMAPI#868]
Hey there! I'm on Windows 11 with [Terminal](https://github.com/microsoft/terminal) and i've noticed that the SMAPI terminal stays open after the game is closed, even when the game exits with normally (e.g. by pressing the "exit" button or using ALT+F4)

Would it be possible to have the terminal `exit` when there's a nominal exit code?

(Personally i'd love to have something like `SKIP_TERMINAL` on windows, but that's a whole other thing)

**Comment by Pathoschild** [comment]
Hi! SMAPI can't choose whether the terminal stays open. The upcoming SMAPI 3.16.0 will now set an exit code when it closes though, which the OS can use to decide whether the console window stays open. For example, Windows Terminal can be configured via _Settings > [terminal type] > Profile termination behavior_:

> ![](https://user-images.githubusercontent.com/230581/183545479-b8853406-9bfb-4b99-96db-daca9c9979b8.png)

**Comment by sleepingdragoninn** [comment]
Minor note - If anyone else finds this issue because they want to hide the terminal window on windows, you can use [RBTray](https://rbtray.sourceforge.net/) which works very nicely.
