### ISSUE TITLE
Cannot move the cursor in selection interface

### ISSUE THREAD

**Issue by LynnXie00** [Pathoschild/SMAPI#871]
**Describe the bug**
I'm using the latest 16.0 version of SMAPI on Win11. I cannot move my cursor freely to select an item under two circumstances:
1. When I donate something to the library, and the item selection interface shows up, the cursor cannot move, but I can use WASD to move my cursor from the left most to the right most of my inventory.

2. When I construct farm buildings at the carpenter's store, I need to select a location for the new building. But  I cannot move my cursor at all, so I cannot build farm buildings in Stardew Valley when launched with SMAPI.

I'm sure it's not because of any mods I installed, because I removed all mods and the same bug still occurs. 

I'd appreciate it if anyone can tell me how to fix it.

**Comment by Pathoschild** [comment]
Hi! See [_Cursor gets stuck on museum or build screen_](https://stardewvalleywiki.com/Modding:Player_Guide/Troubleshooting#Cursor_gets_stuck_on_museum_or_build_screen) in the troubleshooting guide for help fixing that.

If you have any other questions, come ask in [#using-mods-help on the Stardew Valley Discord](https://smapi.io/community#Discord) and we'll be happy to help! The GitHub issues here are only used to track specific development tasks, so most modders who could help won't see questions here.
