### ISSUE TITLE
"DLL couldn't be loaded."

### ISSUE THREAD

**Issue by Mykkapop** [Pathoschild/SMAPI#887]
Does anyone know how to help me?
![Screenshot_20221124-193117](https://user-images.githubusercontent.com/119015514/203870605-7f5b68ac-d462-4512-b83c-546c0c085585.jpg)

I really don't I really don't know what to do, because I can't play with these mods. (Game on Android) I can't play with these mods either because the DLL doesn't load or because I have to update the mods and when I update they don't load the DLL

**Comment by Pathoschild** [comment]
Hi! Can you come ask in [#modded-game-support on the Stardew Valley Discord](https://smapi.io/community#Discord)? Feel free to ping me there with `@Pathoschild#0001` if you don't get an answer.

(You have SMAPI on Android, which is [a separate port](https://github.com/ZaneYork/SMAPI-Android-Installer/). I also only use GitHub tickets to track specific development tasks, so most users who could help don't watch these.)
