### ISSUE TITLE
Mod texture edits cut off on SMAPI 4.0.0-alpha.20221205

### ISSUE THREAD

**Issue by ellipszist** [Pathoschild/SMAPI#888]
**Describe the bug**
Looks like SMAPI 4.0.0-alpha.20221205 is not patched like SMAPI 3.18.1?

**To Reproduce**
1. Install [Elle's Town Buildings](https://www.nexusmods.com/stardewvalley/mods/14524).
2. Create a new save.
3. Walk to 'The Pelican Town Community Center'.
4. Error occurs.

**Log file**
[SMAPI log](https://smapi.io/log/85debaca4a6e40528513812d7425f73f).

**Screenshots**
![image](https://user-images.githubusercontent.com/43781364/205805493-873ea64c-c71d-4809-a232-1263290cfea1.png)

**Comment by Pathoschild** [comment]
This was fixed via #886 and included in later SMAPI 4.0.0 alpha builds. Thanks for reporting it!
