### ISSUE TITLE
smapi 3.18.1 wont install on linux

### ISSUE THREAD

**Issue by djdunn** [Pathoschild/SMAPI#890]
**Describe the bug**
smapi wont install on linux

$ ./install\ on\ Linux.sh
Failed to create CoreCLR, HRESULT: 0x8007054F

**To Reproduce**
run install on Linux.sh

**Log file**
doesn't get far enough to run the smapi log, was trying to reinstall smapi.

**Screenshots**

**Comment by Pathoschild** [comment]
Hi! Can you come ask in [#modded-game-support on the Stardew Valley Discord](https://smapi.io/community#Discord)? Feel free to ping me there with `@Pathoschild#0001` if you don't get an answer.

(I only use GitHub tickets to track specific development tasks, so most users who could help don't watch these.)
