### ISSUE TITLE
About the available Mod model posted to the marketplace.

### ISSUE THREAD

**Issue by TMThong** [Pathoschild/SMAPI#893]
The problem I mean is that the SMAPI Mod templates I use it with, the default target framework is NET Framework 4.5.2
While SMAPI uses net5.0 how can I use the template smoothly in Visual Studio 2022?

**Comment by Pathoschild** [comment]
Hi! There's no official SMAPI template, and the unofficial one you found is very outdated. You can follow the steps in the [mod author guide](https://stardewvalleywiki.com/Modding:Modder_Guide/Get_Started) to create the project directly instead. If anything is unclear, feel free to ask in [#making-mods on the Stardew Valley Discord](https://smapi.io/community#Discord) and we'll be happy to answer your questions.
