### ISSUE TITLE
Outofmemoryexception 

### ISSUE THREAD

**Issue by Reenx99** [Pathoschild/SMAPI#897]
I am using a translator in case the text is not very clear
Yesterday, Tuesday, January 24, I updated smapi
I played a bit, and then added mods
The mods are
-Oasis greenhouse
-Automate
-content patcher
-longevity
-look up anything
-npc map locations
-skull cavern elevator
-stardew valley expanded 
-uiinfosuite2
All have the mods extra that require
I don't know what the problem is and in blogs and others they don't give me an answer or a way to fix it

**Comment by Pathoschild** [comment]
Hi! I'll close this since it's not a specific development task, but can you come ask in [#using-mods-help on the Stardew Valley Discord](https://smapi.io/community#Discord) so we can run some tests? If you don't get an answer, you can ping me there with `@Pathoschild#0001`.
