### ISSUE TITLE
LooseSprites/Emojis is currently stored in Chatbox.emojiTexture and not accounted for in the asset propagation

### ISSUE THREAD

**Issue by atravita-mods** [Pathoschild/SMAPI#912]
https://github.com/Pathoschild/SMAPI/blob/08f65a108ac2a5b9f07569845a81221e4a5222f7/src/SMAPI/Metadata/CoreAssetPropagator.cs#L390

**Comment by Pathoschild** [comment]
Added in `develop` for the upcoming SMAPI 3.18.6. Thanks for reporting it!
