### ISSUE TITLE
Smapi

### ISSUE THREAD

**Issue by Bunny478** [Pathoschild/SMAPI#923]
**Describe the bug**
A clear and concise description of what the bug is. Provide any other details you think might be relevant here.

**To Reproduce**
Exact steps which reproduce the bug, if possible. For example:
1. Load save '...'.
2. Walk to '....'.
3. Click '....'.
4. Error occurs.

**Log file**
Upload your SMAPI log to https://smapi.io/log and post a link here.

**Screenshots**

**Comment by Pathoschild** [comment]
Hi! There's no description, so I'm not sure what issue you're asking about. However, see [Modding:Help](https://stardewvalleywiki.com/Modding:Help) for the best places to ask if you're having trouble!
