### ISSUE TITLE
ColorfulConsoleWriter does not remember setting from installer

### ISSUE THREAD

**Issue by Martmists-GH** [Pathoschild/SMAPI#946]
**Describe the bug**
In the installer I select the "Light text" color scheme, but while the game is running it uses the "Dark text" color scheme.

**To Reproduce**
Exact steps which reproduce the bug, if possible. For example:
1. Select Light text during installing
2. Run the game through SMAPI
3. You should see dark text

Termite color settings:
```
[colors]
background=rgba(53, 6, 4, 0.9)
foreground=#c5c5c5
cursor=#c2ad8d

color0=#000000
color1=#882d1f
color2=#d52918
color3=#dd7922
color4=#e38c74
color5=#f4cc3d
color6=#f5cf89
color7=#c5c5c5
color8=#594240
color9=#ab1206
color10=#ad351d
color11=#ac5b48
color12=#ad6524
color13=#c18853
color14=#c6b579
color15=#c7c0bf
```

**Log file**
N/A

**Screenshots**
![Screenshot_20240411_144919](https://github.com/Pathoschild/SMAPI/assets/16361449/1e9044ff-057a-4ffa-8fc6-e3254b461830)

**Comment by Pathoschild** [comment]
Hi! The installer just toggles the color scheme in the game folder's `smapi-internal/config.json` file. If the `ConsoleColors` > `UseScheme` setting is changed from `AutoDetect` to `DarkBackground`, then the installer itself is working fine.

If that's the case, it's likely that your custom Termite color settings are overriding the colors set by SMAPI. You can change the specific colors used by each theme in the SMAPI settings if needed.
