### ISSUE TITLE
SMAPI Installer Doesn't Detect Steam Flatpak Install Folder

### ISSUE THREAD

**Issue by PhasecoreX** [Pathoschild/SMAPI#948]
**Describe the bug**
When installing SMAPI to a Flapak Steam Stardew Valley, it will not automatically detect the install folder, despite https://github.com/Pathoschild/SMAPI/commit/76e08fc58b75be3dbcd852bfe53dfed40987871d

**To Reproduce**
1. Install Linux, Flatpak, Steam in Flatpak, and then Stardew Valley in Steam in Flatpak
2. Download the latest release (4.0.7 in this case)
3. Extract and `cd` into the folder
4. Run `./install\ on\ Linux.sh`
5. Press 2 and enter to select `Light text on dark background`
6. Be forced to type the file path to the game directory, as the SMAPI Installer couldn't find it automatically.

**Log file**
It's the installer, so no log file(?)

**Screenshots**
![Screenshot_20240425_183013](https://github.com/Pathoschild/SMAPI/assets/10203357/9810e276-819f-4b51-ac09-2a49990051da)

**Other notes**
If I do `file "$HOME/.var/app/com.valvesoftware.Steam/data/Steam/steamapps/common/Stardew Valley/Stardew Valley.dll"`, that file does exist.

I asked on the discord and one person (Yariazen) responded but didn't really know why this was happening. And then that `#making-mods-general` channel had like a hundred other messages going on at the same time so the conversation got lost. There should probably be a forum type thing in there instead of one channel for everything.

**Comment by Pathoschild** [comment]
Fixed in `develop` for the upcoming SMAPI 4.0.9. Thanks for reporting it!
