### ISSUE TITLE
Rebase custom Harmony build onto Harmony v2.3.x

### ISSUE THREAD

**Issue by Lordfirespeed** [Pathoschild/SMAPI#951]
Title, if possible! I'd really love to be able to utilise `AccessTools.DeclaredIndexer` and similar in my projects ❤️ 
I'm not sure where the code lives for the custom Harmony build that SMAPI uses, or I might have a go at the rebase myself and open a pull request.

**Comment by SinZ163** [comment]
It uses https://github.com/Pathoschild/Harmony which has already been updated for 2.3.3, however it is statically compiled and stored as binary in this repo in https://github.com/Pathoschild/SMAPI/tree/develop/build which hasn't been updated since 2.2.2

**Comment by Lordfirespeed** [comment]
Oh, interesting! Might you know if there's any particular reason the binary in this repository hasn't been updated?

**Comment by Pathoschild** [comment]
Hi! The update to Harmony 2.3.3 is on the `update-harmony` branch; it's currently queued for the upcoming SMAPI 4.1.0.

**Comment by Lordfirespeed** [comment]
Awesome! ♥️
