### ISSUE TITLE
I did a clean install of Stardew Valley and SMAPI, but it says there's no manifest in the folder

### ISSUE THREAD

**Issue by kasdfi9sdf8** [Pathoschild/SMAPI#963]
![화면 캡처 2024-09-12 110741](https://github.com/user-attachments/assets/26b508eb-e8b6-4312-914f-48e313c0f3c1)

I downloaded the developer version of SMAPI and searched through the folders, but it's not there.

I'd appreciate your help

**Comment by Pathoschild** [comment]
Hi! You can delete those folders to remove the errors. (See "Mods go here:" at the top of the SMAPI console log to find the `Mods` folder.)

SMAPI itself isn't a mod, so it shouldn't be in your `Mods` folder. You can delete the installer folder after you run the installer.
