### ISSUE TITLE
ModBuildConfig 4.3.0: ContentPacks IgnoreModFilePatterns attribute not working as expected

### ISSUE THREAD

**Issue by b-b-blueberry** [Pathoschild/SMAPI#965]
**Expected:**
Using `ItemGroup` `ContentPacks`, including a CP project in the same solution would copy both C# and CP components to a parent folder when the C# project is built, ignoring paths and patterns given in the `IgnoreModFilePatterns` and `IgnoreModFilePaths` attributes on `ContentPacks`.

**Issue:**
Solution projects included in `ContentPacks` will deploy all files and folders to the output folder, regardless of attributes given in the main project `ContentPacks` or the CP project `PropertyGroup`.

**Reproduce:**
1. Create solution including multiple projects buildable with ModBuildConfig,
2. Add `ItemGroup` `ContentPacks` to the main project, including any other projects,
3. Build main project, bundling all files from included projects.

**Attachments:**
Minimum repro solution with basic C# and CP projects  
[Solution.zip](https://github.com/user-attachments/files/17320234/ModBuildConfig.test.zip)

**Other info:**
Possible cause?  
<https://github.com/Pathoschild/SMAPI/blob/66d9e82fffb61c6cf3347c9f7278bc56b0687aae/src/SMAPI.ModBuildConfig/DeployModTask.cs#L125-L127>  
<https://github.com/Pathoschild/SMAPI/blob/66d9e82fffb61c6cf3347c9f7278bc56b0687aae/src/SMAPI.ModBuildConfig/DeployModTask.cs#L151-L153>

**Comment by Pathoschild** [comment]
Fixed via 50303796f32e449f9763704879386d2d511d60f8 in mod build package 4.3.2. Thanks for reporting it!
