### ISSUE TITLE
Split screen games crash on event end

### ISSUE THREAD

**Issue by RealWhimsy** [Pathoschild/SMAPI#966]
**Split screen games crash on event end**
When playing local co-op (split screen) with two controllers the game crashes after returning home from any event (e.g. Flower Dance, Luau). If the players decide to not attend the event and "sit out" the day, the crash does not occur. Crash happens immediately after loading back to the farm from the event (in the case of for example the Luau event, the player is placed in front of their house at 10PM).

**To Reproduce**
Exact steps which reproduce the bug, if possible. For example:
1. Progress any game until an event starts (tested with Flower Dance and Luau)
2. Start local co-op (split screen) and enter the event with both players
3. Complete the event until players get "sent home"
4. Game crashes (could not find key in tileSheet dictionary)

**Log file**
https://smapi.io/log/8880daaec5be4e8e9332aca5632c7530

**Screenshots**
None

**Comment by RealWhimsy** [comment]
See #964 for potential fix

**Comment by Pathoschild** [comment]
Fixed in the upcoming Stardew Valley 1.6.9 and SMAPI 4.1.0. Thanks for reporting it!
