### ISSUE TITLE
Multiplayer issue with console command 'debug child'.

### ISSUE THREAD

**Issue by Rupurudu** [Pathoschild/SMAPI#969]
**Describe the bug**
Running the console command `debug child` as a farmhand who does not have any children should create a children for them. Unfortunately doing that creates a children for the main farmer, not farmhand. 

Advancing the age of the farmhand's children and creating a children with `debug pregnant` works as expected.

**To Reproduce**
Exact steps which reproduce the bug, if possible. For example:
1. Create a new multiplayer save.
2. Join the save from a second Stardew Valley instance (connect with 127.0.0.1).
3. Create a farmhand.
4. Run `debug houseUpgrade 2` from both main player and farmhand's console to upgrade the house and farmhand's cabin.
5. Run `debug marry Haley` from farmhand's console to marry Haley. (Or your preferred marriage candidate)
6. Sleep with both players to advance to the next day.
7. Run `debug child` from farmhand's console.
8. See that the child is created at the main farmer's house (inside crib) and not the farmhand's cabin.
9. The created child should be spawned inside farmhand's cabin.

**Comment by Pathoschild** [comment]
Hi! The `debug child` console command is part of the game, not SMAPI. I added a fix in the upcoming Stardew Valley 1.6.14 though.
