### ISSUE TITLE
Error to build on MacOS

### ISSUE THREAD

**Issue by Guiihslherme** [Pathoschild/SMAPI#970]
I install the SMAPI, and when I will run the game, have this error and the SMAPI archive is moved to trash. Im using MacOS Sequoia 15.1.1

<img width="252" alt="Screenshot 2024-11-28 at 17 20 28" src="https://github.com/user-attachments/assets/f98e5d84-3cfc-495d-ad02-d2e560ca5211">

SMAPI Log.

Last login: Thu Nov 28 17:15:36 on ttys003
guilherme@Guilhermes-MacBook-Pro ~ % /Users/guilherme/Library/Application\ Support/Steam/steamapps/common/Stardew\ Valley/Contents/MacOS/StardewModdingAPI ; exit;
zsh: killed     

Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]

**Comment by Pathoschild** [comment]
Hi! Installing the latest SMAPI 4.1.8 (just released today) should fix compatibility with the new macOS security restrictions. If you still need help, feel free to ask on the mod page instead!

**Comment by ziyike** [comment]
macOS Ventura here, it took me two and a half hours to finally confirm the game won’t run with smapi installed, and I have updated to the latest 4.1.8. Tried everything with disabling gatekeeper, removing any com.apple.quarantine xattr, entering safe mode then deleting any unwanted plots… there is still the popup saying the file is broken, it will harm your system blablabla, the only difference with this posted issue is that it does not say malicious, but the file is downloaded at an unknown date. I don’t know what to do now. The game and smapi was uninstalled and reinstalled many times, tried every combination I can think of.

**Comment by chenczn3528** [comment]
macOS M2  Sonoma 14.5 
<img width="294" alt="image" src="https://github.com/user-attachments/assets/4aa7f4e7-6977-4a19-a0c9-b5de3a0f181d">
Logs: 
/tmp/open-smapi-terminal.command ; exit;
/Users/chen/Library/Application Support/Steam/steamapps/common/Stardew Valley/Contents/MacOS/StardewValley: line 196: 50812 Killed: 9               ./StardewModdingAPI "$@"

Saving session...completed.

**Edit:** 
[discord](https://discord.com/channels/137344473976799233/1312885102807744563/1312979723407724585)
When I install 4.1.7 and run the following code in the terminal, it works.
`codesign --force --sign - "Library/Application Support/Steam/steamapps/common/Stardew Valley/Contents/MacOS/StardewModdingAPI"`

**Comment by nat986** [comment]
Hi @Pathoschild , I attempted to install SMAPI 4.1.8 fresh on Stardew Valley on Mac running Sequoia 15.1.1 today, received warning: 
<img width="372" alt="image" src="https://github.com/user-attachments/assets/683cd2e6-c90d-471f-9aec-8da34e645452">

**EDIT** : The stardewvalley Discord has a megathread for troubleshooting this issue, including a workaround with involves installing 4.1.7 (which worked for me!)

**Comment by Pathoschild** [comment]
Hi! The latest [install guide for macOS](https://stardewvalleywiki.com/Modding:Installing_SMAPI_on_Mac) should fix that.

Note that these GitHub issues are only used to track planned technical work, so you won't get a quick response here. See [Modding:Help](https://stardewvalleywiki.com/Modding:Help) for the best places to ask support questions.
