### ISSUE TITLE
macOS 15.1.1 malware detection binning error

### ISSUE THREAD

**Issue by Not-Joshing** [Pathoschild/SMAPI#971]
**Describe the bug**
macOS identifies "StardewModdingAPI" as malware and bins it. I realise this was already addressed in SMAPI 4.1.8, but it has reappeared. I'm not a developer, but it might be a Notarization error?

**To Reproduce**
This happened on an M3 Apple Silicon MacBook Air on macOS Sequoia 15.1.1 (24891). I've opened Stardew from the Dock shortcut made by Steam. The error seems to occur during the terminal sequence.

**Log file**
I can't find SMAPI-crash.txt or SMAPI-latest.txt. I believe this is because it's an operating system problem rather than a crash.
I was using SMAPI 4.1.8 (the latest version as of this post). Please ask if more information is needed.

**Screenshots**
Here's a screenshot of the binning notification.
![macOS StardewModdingAPI  malware  deletion](https://github.com/user-attachments/assets/d286aaf6-682c-4429-9baa-f81996dad48b)

**Extra**
I've tried to find the solution independently and follow the issue etiquette, but I may have made a mistake. Let me know if I've missed something.

**Comment by weiwentao996** [comment]
me too

**Comment by jennifer-drew** [comment]
This happens for me too. It works for me in 4.1.8-alpha.20241127, but not in the final release of 4.1.8.

**Comment by Pathoschild** [comment]
Hi! This should be fixed in the upcoming SMAPI 4.1.9, which adjusts for the new macOS security restrictions.

**Comment by Not-Joshing** [comment]
> Hi! This should be fixed in the upcoming SMAPI 4.1.9, which adjusts for the new macOS security restrictions.

Thank you for everything you do for Stardew.
